### ISSUE TITLE
JetEngines | Listing | Dynamic Field

### ISSUE THREAD

**Issue by jonastoa** [Crocoblock/suggestions#1004]
Adding "text before" & "text after" for Dynamic Field.
This function is available for for Dynamic Term & Dynamic Meta, but not in Dynamic Field.

Though, icon is available, but sometimes text is better.

**Comment by Floydtm** [comment]
@jonastoa, hi! For a dynamic field you can use this option http://prntscr.com/rh8v20

**Comment by jesskiri** [comment]
@Floydtm But then, you can't style the "text before" or "text after" like you can in Dynamic Term widget

**Comment by Floydtm** [comment]
@jesskiri, hi! Use css.

**Comment by jesskiri** [comment]
@Floydtm Yes and I guess I could also use PHP instead of all of Crocoblock plugins... that is not the point!

Elementor is built with multiple styling settings so you won't have to rely on CSS, the same way Crocoblock is built so you won't have to code php.

The 'text before' and 'text after' option is available in Dynamic Term and Dynamic Meta, so that would also be a more consistent experience for the users to add it to Dynamic Field.

Also, if I style the 'text before' Dynamic Term with Elementor presets, I would have to recreate the styling manually for Dynamic Field and it wouldn't update consistently if I changed Elementor presets.
