### ISSUE TITLE
JetWooBuilder changes shop hooks

### ISSUE THREAD

**Issue by RuP3rlt** [Crocoblock/suggestions#1015]
**Describe the bug**
I use JetWooBuilder and Advanced Product labels (But I tried MANY badges/labels plugins).
Problem is, JetWooBuilder changes shop hooks to it's own and therefore none of the badges/labels plugins work anymore since they can't find hooks. 

**To Reproduce**
1. Create JetWoo template for product block.
2. Create badge/label

**Expected behavior**
Hooks should not be changed to anything else, making this plugin incompatible with other many plugins.

**Additional context**
Is there any way where I can change hooks back?

**Comment by UraraReika** [comment]
Hello @RuP3rlt!

JetWooBuilder is a plugin built on standard Woocommerce for use in the Elementor environment. These two plugins are the main guidelines and are fully compatible with them. There is also compatibility with our other products and individual translation plugins. As for all other Wordpress plugins and directly the plugins associated with Woocommerce, we cannot provide compatibility with each of them. In particular, those hooks for which you speak are provided for the necessary work of our plugin.

JetWooBuilder is also built on the basic Woocommerce functionality and minimally customized, and if some plugin extends the Woocommerce functionality or adds something to it, then in this case, everything will work with our plugin.

It should be added that since we work directly in the Elementor editor, it should be borne in mind that your plugins do not have compatibility with it and an alternative way to display in the editor. But on our part, you can use widgets to display labels https://prnt.sc/ri8gkp.

**Comment by RuP3rlt** [comment]
Hello @UraraReika , fair enough, that explains it, thank you.
As for your labels plugin, I did try it, unfortunately it does not have the functionality I need.

Thank you.
