### ISSUE TITLE
JetMenu ignores visibility conditions and hides the menu item completely

### ISSUE THREAD

**Issue by MrTyree** [Crocoblock/suggestions#1110]
JetMenu compatibility issue using the following plugins:
- If Menu – Visibility control for Menu Items 
- Nav Menu Roles WooCommerce Memberships

**To Reproduce**
1. Download a menu visibility plugin like the ones mentioned above
2. Go to _Appearance_ >> _Menus_ >> setup a condition on a menu item such as _display for logged in users_.
3. Add the the JetMenu _Hamburger Menu_ element to the frontend.
4. You will see the problem, the menu will ignore the conditions previously setup.

**Expected behavior**
The goal is to hide a menu item based on conditions, however **the JetMenu plugin ignores conditions and hides the menu item completely no matter the conditions**. Unless the conditions are off, the menu item will show which, defeats the purpose of having conditions.

**Comment by pedrostein** [comment]
+1 it would also be excellent if there would be an option to set rules and conditions directly in the JetMenu without the need of some third party plugins. Similar the way it is possible in Max Mega Menu.

**Comment by Floydtm** [comment]
@MrTyree, hi! I checked your case and I can say that everything works fine. Perhaps the problem is only on our site. If the problem persists, please contact our support team.
@pedrostein, At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
