### ISSUE TITLE
Custom Query Id Field on Listing Grid

### ISSUE THREAD

**Issue by ktgb** [Crocoblock/suggestions#1138]
I Use Jetengine to show my posts on different pages. 

Now, i have a very special query and for this, i need a field in listing grid, were i can add a custom query id. Is it possible?

In Elementor Post grid, you have the option to enter a custom query id. The same query field id field, i need for jetengine listin grid.

**Comment by Floydtm** [comment]
@ktgb, hi! Could you describe the request in more detail? if you can attach screenshots or video. which option do you specifically miss?

**Comment by ktgb** [comment]
Hey, thanks for reply.

In Elementor Post grid, you have the option to enter a custom query id. 

![epa](https://user-images.githubusercontent.com/64144493/80497818-3dd38600-896b-11ea-9e15-ce8e2fc9250e.png)

I need the same feature on jetengine listing grid. 

**The Reason why:**

Elementor Post grid has a option to enter a custom query id. So good, so far.

I would like to filter my grid with jetsmartfilter. To filter the elemetor post grid,  i must enter "jet-smart-filter" in query id field.

Than you can filter elementor post grid with jetsmartfilter.

The problem is that i am already using the field for the query id and therefore i cannot use the jetsmart filter in connection with elementor post grid. 

(I use the query id filed for my special query to show related posts from 3 different post types.)

For this reason i would like to use the jetengine listing grid because it works automatically with jetsmartfilter. But here ist the problem, that i have no field to enter my custom query id which i need. 

My Question: 

Is there a option to enter a custom query id in jetengine listing grid to show my special query?

**Comment by Floydtm** [comment]
It seems to me that you can link the filters and grid listing in this way http://prntscr.com/s82599 http://prntscr.com/s825tr and this will work. Let me know if this solves your problem.

**Comment by ktgb** [comment]
Thanks for help, but this was not the perfect solution for me. 

I have solved my problem with this manual [https://crocoblock.com/knowledge-base/articles/jetengine-listing-grid-widget-how-to-display-dynamically-related-posts-on-the-single-post-page-template/](url)

**Comment by Highway596** [comment]
Hello,

I'd like to resurrect and second this suggestion made by ktgb. 

The lack of a Query ID in the JetEngine Listing Grid is denying users the option to set custom PHP actions to modify the JetEngine widget queries via functions.php. 

While, as Floydtm states, a user can link the JetSmart filter widgets to the Listing Grid via similar Query IDs, the lack of a query ID in the listing widget itself denies the user the functionality that Elementor provides here: https://developers.elementor.com/custom-query-filter/#Filter_Posts_by_Post_Meta_in_Portfolio_Widget

This Elementor functionality is VERY powerful as it allows expanding on the functionality built into the widget. In my instance, I'm in need of filtering an archive template which a typical pre_get_posts will not do. Having a Query ID and the related functionality that Elementor provides, I would be far more able to modify the Listing Grid queries.

This image shows the ID of the Listing Grid
![ID of Listing Grid](https://user-images.githubusercontent.com/63313783/107140559-07566e80-68e0-11eb-9c13-7de9492db874.jpg)
However the Elementor action will not function on it due to the lack of corresponding functionality in the JetEngine plugin
![Non Functioning Action](https://user-images.githubusercontent.com/63313783/107140562-09203200-68e0-11eb-9683-0cd277e1c354.jpeg)
A simple pre_get_posts will function fine on the Listing Grid's queried posts when using the post title, date, etc however sorting by post meta data is not working. I suspect that the similar functionality that Elementor provides on their widget would allow me to do so with JetEngine's Listing Grid.
![Basic pre_get_posts](https://user-images.githubusercontent.com/63313783/107140563-09b8c880-68e0-11eb-9627-e77219b35c02.jpeg)

EDIT: After dropping an Elementor "Posts" widget into the page and filtering using their strategy (query ID on the widget and action in the functions.php file) I was able to sort successfully using the pre_get_posts $query modifications that are not functioning on the JetEngine Listing Grid. Maybe I'm missing something but this lack of functionality is massive blind spot for customizing queries via PHP on a JetEngine Listing Grid in an otherwise fantastic plugin.

**Comment by formulaclick** [comment]
Query ID should be available as Elementor does in its "Posts" widget. We can't make all queries we would like to do.... It's fustrating.

**Comment by Gabrymi93** [comment]
After the Query Builder there is still no possibility to query JetEngine listings as Elementor does with an easy Custom ID Query?
Please this is such an important feature and don't think it's so complicated to realize. 
Am I missing this functionality in the release of Query Builder?

**Comment by jtas01** [comment]
Yes, elementor's custom query is great. And would love to have the same in JetEngine as well.

**Comment by formulaclick** [comment]
No updates about this? Query Builder is not solution when there is a complex query.

**Comment by bortraws** [comment]
Yes please, a Query ID in listing Grid that can refer to a Custom Query written in PHP.

We now use Query Builder with an Advanced SQL Query but this doesn't work with Pagination and Smart Filters.

**Comment by Andreas2209** [comment]
Is there an update? I am facing the same issue, i have an Advanced SQL Query for a listing grid and can´t make my Smart Filters to work...

**Comment by kaskad88** [comment]
@bortraws @Andreas2209 Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue

**Comment by stasonua0** [comment]
Even the wretched "Post" widget from Elementor can do this. Consider adding such functionality.

**Comment by Ayleen555** [comment]
6 years later in this function still does not exist...
