### ISSUE TITLE
Automated filter indexing for JetSmartFilters

### ISSUE THREAD

**Issue by petranca** [Crocoblock/suggestions#1159]
If products/posts/attributes are added or changed frequently, it is tedious for the user to manually reindex the "JetSmartFilters" each time using the "Index Filters" button. In addition, the user does not always have the access rights to these filter settings.

It would be helpful if this could be done automatically, e.g. via a cronjob.

**Comment by numanagit** [comment]
+1 to this. It's not a complicated feature and I think its very important

**Comment by NicoDilo** [comment]
+1 Too !! It's an essential feature, without it, the indexer is useless

**Comment by totomuc** [comment]
+1. Please consider this feature or at least add the possibility to CRON the index update.

**Comment by petranca** [comment]
Maybe it would make sense, if the filter is updated automatically when the defined data source of the filter is edited or filled with new data. For example, if a checkbox list filter was defined  with taxonomy > category, the filter index should automatically reindex itself when a new category is created or edited. The same with posts, custom fields etc....

**Comment by Floydtm** [comment]
Guys, we understand that this is very important to you. However, we cannot do this right now because it takes a lot of time. But we will try to do this in the future. Right now you can use [WP Crontrol](https://wordpress.org/plugins/wp-crontrol/) plugin https://prnt.sc/u69a1b

**Comment by KrzysztofMaciejewskiCOM** [comment]
+1 to implement this in JetSmartFilters - its critical function 

Thanks!

**Comment by paulherzlich** [comment]
+1 Please. Really needed. Customer doesn't understand why displayed filter counts aren't accurate.

**Comment by pierrehansen** [comment]
Yes, please! Customer is complaining. It's an absolute must have.

**Comment by pierrehansen** [comment]
Are you planning to add this in the near future? Isn't this very easy to implement? My client is waiting, asking. Don't want to change his rights to administrator. Thanks!

**Comment by ingramleedy** [comment]
+1

**Comment by deepwaterpixel** [comment]
Since this "takes a lot of time", and I did find this solution elsewhere I have decided to mature it a bit and provide the code to fix this:


Crocoblock:
```
// Schedule the daily update if not scheduled
if ( ! wp_next_scheduled( 'Crocoblock_Index_Update' ) ) {
    wp_schedule_event( strtotime('23:30:00'), 'daily', 'Crocoblock_Index_Update' );
}
// Run the indexer function call
function cb_update_index_update(){
   jet_smart_filters()->indexer->index_filters();
}
// Hook into the Crocoblock Indexer
add_action( 'Crocoblock_Index_Update', 'cb_update_index_update' );
```

The original post that provided this solution recommended modifying WPCron with a plugin and manually calling the following chunk:

`jet_smart_filters()->indexer->index_filters();`

>Average Users:
>You will want to create a WP Cron and add the single line above to the configuration and run it either daily, hourly, or whatever interval suits your need.  I have attached a screenshot showing the setup in WP Crontrol.
<img width="934" alt="Screen Shot 2021-03-09 at 11 24 06 AM" src="https://user-images.githubusercontent.com/54284392/110511603-0032a400-80ca-11eb-8f6a-60da7ee05114.png">


I can't find the original thread I found this in, but it appears that possibly a Crocoblock dev or agent provided this function call.  My code simply makes the CRON creation automatic, and daily around 11:30pm server time.  I have implemented mine on an hourly basis because items are continually added to the post type the filters are attached to them.  I did not test this code, because I have already modified Crocoblock's plugins enough as it is haha

**Comment by paulherzlich** [comment]
Thanks for laying out for a very average user. Much appreciated.

**Comment by maurocarreraok** [comment]
+1 kinda urgent.

**Comment by DevDietheR** [comment]
What's the update on this one? It's been a long time,  Please prioritise this

**Comment by nreljed** [comment]
#3465

**Comment by deepwaterpixel** [comment]
It has been 133 days since I found this thread and commented with a solution that could be implemented quickly by the developers.  It has been 452 days since this thread was reported on Apr 24, 2020.  Can we tag a dev and get this fixed?

Edit: I came back here because I noticed another build of mine was not indexing filters automatically and I thought "surely they haven't sat on the solution for 4 months?!"  And yet, here I am.  Implementing my hacky fix so a client is satisfied.  Disappointing!

**Comment by oliveandlake** [comment]
I've just run across this problem. We have a client who has a real estate website an uploads multiple properties per day. It's a bit annoying that at the end of the day, we have to task one of our team to remember to click the button to index them. I mean surely, this should be automated via a cron job shouldn't it?

**Comment by oliveandlake** [comment]
I contacted support about this issue. They said that they would release a new version later this month to address this issue!

**Comment by SaidBahaDev** [comment]
@deepwaterpixel thank you , when i run jet_smart_filters()->indexer->index_filters();

i got an erreor Fatal error: Uncaught Error: Call to a member function index_filters() on null

**Comment by deepwaterpixel** [comment]
@SaidBahaDev -- this should only happen if there is a conflict or the function has been removed/renamed by the devs.  I checked the changelogs for JSF [here](https://crocoblock.com/changelog/?plugin=jet-smart-filters) and didn't see any mention of a change to the indexing of filters, so my bet is on a conflict.  Try using Query Monitor to suss out the problem specifically, but unfortunately I won't be able to help too much since this is a Crocoblock problem and not mine to solve.

If you're not comfortable debugging the problem, then you might want to consider the manual solution: updating it by clicking the button.  This isn't a great experience, but it's at least reliable.  If I recall correctly, the "Index Filters" button uses the `index_filters()` function, so if the red "Index Filters" button works for you, then it should work in the CRON job.

Devs, I see that you've communicated with @oliveandlake about this problem, and that it will be solved soon.  As you can see, their needs imply that a daily update might not always solve the problem, so the interface you throw together to control the CRON should allow for a frequency to be chosen (by minute, by 15 minutes, by 30 minutes, hourly, every 3 hours, etc.) in addition to setting this up for a daily run.

**Comment by claudiovsky** [comment]
fixed with today update!

**Comment by deepwaterpixel** [comment]
I have updated to the latest version and can confirm after adding/removing some CPTs with indexes attached, and it appears to update the index when a CPT that's registered is updated.  Probably hooked on update_post, which is a great way to ensure that post indexes are updated as soon as posts are updated.  Love the implementation, Crocoblock -- much better than an additional CRON job!  Now... to remove those CRON jobs on existing site and get them all updated!

I know that I was pretty harsh in my criticism given the amount of time that has passed since this issue was originally raised, but I have also worked at a small software company (15 ppl max) and understand the constraints that having dozens of products can present.  I am so grateful to see my problems resolved, but I am also a customer and hope to see major functional issues like this addressed with a bit more urgency.  Still, I am now satisfied with this fix!

If you've been waiting on this, go ahead and update -- it works a treat compared to the "old way".

**Comment by alican532** [comment]
After enabling the "Use auto re-indexing" feature, the filtering feature does not work. I turned off "Use auto re-indexing" but everything broke. Filters are not working now. No indexes are visible.

**Comment by chikazeseo** [comment]
> After enabling the "Use auto re-indexing" feature, the filtering feature does not work. I turned off "Use auto re-indexing" but everything broke. Filters are not working now. No indexes are visible.

Have you found a solution to this issue? I'm facing the same problem as you

**Comment by RuanPienaarCode** [comment]
+1

**Comment by Crocoblock** [comment]
@RuanPienaarCode 
This feature was added in the JetSmartFilter 2.3.3 https://i.imgur.com/L41ZbOf.png

**Comment by Crocoblock** [comment]
@chikazeseo, if you have an issue with the auto-indexer, please contact our support team regarding this case: https://crocoblock.com/help-center/. create a ticket including access details for your site where the issue occurred to ensure we can help you.
