### ISSUE TITLE
JetEngine Listing grid - Order Terms by Custom Meta Field

### ISSUE THREAD

**Issue by primozkosta** [Crocoblock/suggestions#1225]
I suggest adding option to order Terms by Custom Meta Field. This is already possible for Posts but not for Terms.

Currently JetEngine Listing has following options for Terms order:
-Name
-Slug
-Term Group
-Term ID
-Description
-Parent
-Count
-None

There is no option to display Terms in custom order. Having the option to order Terms by Custom Meta Field would solve this.

**Comment by Semonxue** [comment]
I'm using listing for my custom terms. The order is very important for normal usage. Is this a bug? Please fix it.

**Comment by uiliw** [comment]
Any news?

**Comment by kay742** [comment]
Hey @uiliw, @Semonxue and @primozkosta, maybe you saw this already, also leaving this for others. You can do this with the custom Query builder. You can choose to order by [string|numeric|clause] meta value. Then pick the custom query as your source when adding the listing grid.

**Comment by primozkosta** [comment]
Hey @kay742, thanks for the info. Very valuable! Will try it out.

**Comment by samuelbauer-io** [comment]
> Hey @uiliw, @Semonxue and @primozkosta, maybe you saw this already, also leaving this for others. You can do this with the custom Query builder. You can choose to order by [string|numeric|clause] meta value. Then pick the custom query as your source when adding the listing grid.

I am running latest version JetEngine 3.0.1 and there is no "order by [string|numeric|clause] meta value" option in Query Builder for Terms - Are you really sure? 
Anyway - @MjHead , for me not a single kind of order works for Terms in query builder. How can that be possible?

**Comment by MjHead** [comment]
v. 3.2.5

**Comment by demon19851027** [comment]
Hello, tell me how to solve the problem? I have created categories and each of the categories contains its own subcategory. And it turns out that in the form on the user's side, they are displayed in one list. And according to the idea, it should work a little differently. 

The user must select the main category, after which an additional field with a list of subcategories should appear. And there is no such thing in your plugin! Your plugin displays all categories and subcategories together. And as a result, it turns out to be a long list of taxonomies in which the user can simply get lost.

We are talking about the type of field: **Select**

**Comment by iso9001muc** [comment]
When I use the custom query builder I can order by meta values, but when I use JetSmartFilters on the same page, the filters does not work anymore. Only the query settings are taken into account, not the filters anymore. Is this a known bug?
