### ISSUE TITLE
Pagination Broken with JetSmartFilters for Elementor Pro Archive Widget

### ISSUE THREAD

**Issue by spinetrak** [Crocoblock/suggestions#1376]
The JetSmartFilter works more or less, in that it filters the archive posts by category, as intended. 

It does not work, when one tries to apply a filter after having navigated to say /page/4

More importantly, one a filter has been applied, the resulting navigation URLs for archive are invalid, for example the URL for page 4 is https://hsk1830.de/wp-admin/admin-ajax.php/page/4 

See https://hsk1830.de/aktuelles

**Comment by realstephenzhao** [comment]
As far as I know, Jetsmartfilters can only work with Pagination(Filter) widget from itself currently. It can't work with default archive pagination(From Elementor Posts/Archive Posts or Posts Pagination from Jetblog) when you navigate by link.

**Comment by noxdiurna** [comment]
I tried pretty much every possible variables. I created Listing and tried to import items thru Product Archive, Archive, Listings widgets etc with all types of pagination options, including the standard one, the posting pagination widget and also pagination widgets. I also tried the entire configuration with all types of different configuration excluding Ajax as I can't use that for SEO and caching problem with my website. 

For now, I think that I need to implement unwanted load more button in order to avoid all pagination but I really hope that this will be solved quickly as it does fundamentally compromises the reason why the filter exists to begin with.

**Comment by Floydtm** [comment]
Use pagination from filters with other providers

**Comment by marwacyrine** [comment]
In fact the default wordpress paginator does not use ajax.
You can change the filter to add reload button. You can also hide it (css) and trigger the click on filter value change. But, you will have issue with empty pages if you have less results than the current page offset.

The best solution is to use **JetSmartFilter pagination component** : 
https://crocoblock.com/knowledge-base/articles/jetsmartfilters-how-to-use-ajax-pagination/

**Comment by RJJuk** [comment]
So, if i want full functionality of product i biught i must bought [JetWooBuilder]. And after that what, I'll find out that basic functionalities need another two?

**Comment by RJJuk** [comment]
So, as I understand it, to have the full functionality of the product I bought, I have to buy another one with a paginator [JetWooBuilder]? Because otherwise it's just a prosthesis? Does this chain end at some point?
