### ISSUE TITLE
JetWooBuilder Product Grid / Category Grid - Consistent Naming...

### ISSUE THREAD

**Issue by ryanerwin** [Crocoblock/suggestions#1378]
I think that the names in the Products Grid and Category Grid widget should be consistent.

In The Products Grid you have: `Order By` but in the Category Grid widget you call this `Sort By`
Meanwhile `Order By` on the Category Grid maps to `Order` in the Products grid.

Seems that the Products Grid is a bit more polished, and Category Grid should probably be updated a bit to match the names and field order of the Products Grid widget.

Not a huge issue, but to me it just doesn't look very professional not make it consistent.

![image](https://user-images.githubusercontent.com/2156415/83625622-7136af80-a5be-11ea-96b1-d97714d7681c.png)

**Comment by NeoAcla** [comment]
this is the same situation with the Active Filter widget and Active Tags, they were almost the same usage but the Active Tags has better options when customization is a concern in the content area. Since its part of the JetWoobuilder, maybe you can include to check this as well.

![Capture](https://user-images.githubusercontent.com/19571084/83659199-47888300-a5d4-11ea-8fb7-110ab4da7aa3.JPG)

Thanks
