### ISSUE TITLE
Add a clear and fitting title for the feature request

### ISSUE THREAD

**Issue by naveenmettu** [Crocoblock/suggestions#1436]
**I'm using listing items to create a custom grid** 

- Listing item has only two options, either to disable or enable open link in new tab option
- The problem with this is, if I enable every item click opens in a new tab (which isn't user friendly)
- If I disable this, user can't just right click on the item in listing grid to view it in a new tab. He has to click on the item & it will open only in the current tab. 

Please fix this issue ASAP, as it is a user interactivity bug. Thanks
===================================
![Screen Shot 2020-06-10 at 6 43 08 PM](https://user-images.githubusercontent.com/29507494/84484303-71cee600-ac4f-11ea-9b21-83482c0fa530.png)
![Screen Shot 2020-06-10 at 6 43 43 PM](https://user-images.githubusercontent.com/29507494/84484312-74314000-ac4f-11ea-8c2b-67d443291ec4.png)

**Comment by realstephenzhao** [comment]
If I am not wrong, it is designated to behave like that because it would add anchor tags to each list items by enable this option. It is useful in some situations but not in yours.
To avoid this, just disable this option and set permalink in link option of each element(widget) such as thumbnail, title and others.

**Comment by Floydtm** [comment]
@naveenmettu, hi! This is not a bug. to do what you want you need to make links on the desired item in the listing
