### ISSUE TITLE
JetBooking: import/export iCal availability

### ISSUE THREAD

**Issue by Rubenzella** [Crocoblock/suggestions#1557]
Nowadays it's common practice to have your properties listed in different sites. To keep your calendars updated everywhere booking systems use iCal format to sync.
* plugin should generate an iCal link that can be imported to other booking systems
* plugin should be able to import an iCal link from another source

**Comment by WardenCommander** [comment]
following for updates

**Comment by cedaly1968** [comment]
Bi-directional sync with a third-party calendar is somewhat required.  The Jet Appointment calendar is actually a subset of the service provider calendar.  For example, I own a recording studio and have my own calendar, the studio calendar syncs appointments into MY calendar, and I may add on my calendar events like Vacation Time, Studio maintenance and cleaning, or private appointments that should sync back to the Jet Appointment as "unavailable" blocks.  I should not need to fill out a form on the Jet Appointment calendar or even access the application for the primary calendar to update the Jet Appointment calendar.  The objective is to integrate and simplify the studio owner business giving customers access to a calendar that shows availability in studio.

**Comment by UraraReika** [comment]
We already had this functionality since iCal option, but in the lates release we made this even better please check out our articles about it:
- https://crocoblock.com/knowledge-base/articles/jetbooking-how-to-transfer-bookings-from-google-calendar-via-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-reverse-booking-and-google-calendar-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-two-way-booking-and-google-calendar-ical-synchnization/

Please take a note that you can make such integration with every service that provide iCal functionality.
