### ISSUE TITLE
Adding custom field to product grid

### ISSUE THREAD

**Issue by noxdiurna** [Crocoblock/suggestions#1579]
Hi. First off, loving the plugins and the support. :-)

Anyway, I was hoping to acheive something that I thought very simple but apparently, I'm having difficulties to do so either with ACF or with JetEngine.

I wish to add a custom field made with JetEngine to product grid widget from JetWooBuilder. Currently, we have the choice to display either the product title, categories, tags, price, rating, SKU, cart butto, whishlist, and even the quickview but I wish to be able to add a new field or a custom taxonomy made from the JetEngine. 

This feature is critical for e-commerce sites selling multiple brands as we wish to display not only the product name but also the brand and the a simple model description. 

I hope this feature makes its way up to the future updates. 

Thank you.

**Comment by noxdiurna** [comment]
Anyone?

**Comment by Floydtm** [comment]
@noxdiurna, hi! I understand that this is very important for you, but there is no way to add a custom field to the product grid widget. To solve your request, you need to create a custom archive template using the jetwoobuilder and jetengine plugins

**Comment by noxdiurna** [comment]
Hi. I understand your proposal and it's technically easier to do that, especially if you have all the necessary plugins (which is my case). But while I can create a general product archive or category archive with your idea with all the information that I wish to display, it seems to me that I can't easily custom that template for other query such as upsell recommandations. If I'm wrong please do let me know. thank you.

**Comment by noxdiurna** [comment]
I followed your recommendation and tried to replace the normal JetWoo Builder's product grid with listing widget with JetEngine. Then I encountered another problem with that with pagination and Smart Search. 

https://github.com/Crocoblock/suggestions/issues/1376

As much as I love Crocoblock, I get the impression that I'm just running around a loop without a solution with this one.

**Comment by Floydtm** [comment]
Unfortunately I do not know how you have everything configured on your site. Please contact our support team. They will help you set up everything. Thank!

**Comment by eybel** [comment]
I just submitted a ticket about this. I thought that when I clicked on any elementor pro widget or any other widget that I could just simply hit the Dynamic Data icon to find the Custom Field Key and just show that extra data but its not working and the weird part is that it does work on the preview! but not on live page.

My client needs to show Financial information on each Product Loop Item but if we cant have a custom field (that the customer can fill out on the product edit page) then this wont be possible and we have to deal with global items instead of personalized items.

I believe this is the biggest change that jetwoobuilder should bring. The possiblity to allow those Custom Fields (that woocommerce already offer) to be shown on the grids.

Showing on each card the Brand, the savings, the payment options, the cities where its available, its important. Each product has different information and some of that information, for my customers is important to be shown on grids.

I hope this gets worked on because woocommerce already offers those custom fields, because all widgets do load Dynamic Data but the Loops wont show it on the live page (they do on preview, weird)

I will have to install jetengine (2nd plugin) to only achieve this.

**Comment by techiebraj** [comment]
@eybel Same situation here. I want to show a shortcode below the PRODUCT GRID ITEM, e.g. https://prnt.sc/1g56wrp but Jet WooBuilder doesn't allow custom fields. Isn't there any solution yet? @Floydtm

**Comment by eybel** [comment]
Try with jet listing ítem in Jet Engine. I made my look cards there.

**Comment by techiebraj** [comment]
@eybel Yes, Jet listing Grid does the job. But this should also be in Jet woo Builder where we could add a custom field. And in Jet WooBuilder there should also be an option to use LOAD MORE if someone wants LOAD MORE instead of Pagination. Anyway, thanks!

**Comment by danielmachado77** [comment]
Hi @TechieBraj . Can you tell me how was the way you choose to solve your problem? I have the same here.

**Comment by beamkiller** [comment]
Hi @danielmachado77 . You can create a template override.

So for example in my case I wanted to add a second price which is the wholesale price to the grid.
So I did an overwrite in my child theme for this file:
`/wp-content/plugins/jet-woo-builder/templates/widgets/global/products-grid/item-price.php`
`/wp-content/themes/astra-child/jet-woo-builder/widgets/global/products-grid/item-price.php`
