### ISSUE TITLE
Feature Request: Ajax Add to cart in Quick View Popup on Shop page

### ISSUE THREAD

**Issue by NeoAcla** [Crocoblock/suggestions#1623]
Hi Devs Team,

Few days ago, i ask for a support on how to fix my issue regarding Add to cart button in a Quick View popup.
But it seems that the issue is has no fix instead i was ask to go here and request this feature.

Below is the response of Veiki.

Hi neo,

Take my apologies for misinforming you!

Actually, I asked our developers,
and Add to Cart really will not work by AJAX in a popup.
Please, leave a request here:
https://github.com/CrocoBlock/suggestions/issues
and our developers will try to implement the feature.

Add to Cart will work by AJAX on the Single product page,
but not in a popup.

------end message----

I will try to explain here for everyone's information, what I am trying to achieve.

I have a custom Shop page using jet woobuilder, using product grid, I enable the quick view, then created a popup for Quick View template. Everything is working fine except when you click the Quick View button it will popup and load the single product but once you hit the Add to cart button from the Quick View it will add to cart but at the same time it will redirect you to the single product page. Which is a bit annoying because we know that one of the main purpose of the Quick View is to avoid leaving on the current page but you still have the ability to add them to cart and continue shopping.

Hope you get my point.

Thanks in advance.

**Comment by Fulcanelli60** [comment]
@NeoAcla, I have the EXACT same problem.

I don't know what the guys at Crocoblock are talking about because it definitely is possible to have Ajax add to cart in a popup - I have been using Yith's QuickView without issue for a long while that does exactly this (and it leaves the popup open in case you need to choose another selection, which is needed function in a wholesale store).

There are other QuickView popups which also use ajax for the Add to Cart - Barns2Media for example (but their popup closes once the product has been added) so I don't know why Crocoblock find it so difficult.

I just spent days perfecting a layout using the product grid in WooBuilder (the archive template lacks the back-order stock badge that the product grid has) on an Elementor template. Got the QuickView button working perfectly and position correctly on all screens and thought I was done. To my horror I discover that it redirects to the product page when add to cart is clicked. Noooo!

I can't use Yith instead (or any other QuickView plugin) to overcome this problem because _none_ of them work with woobuilder templates or product grids. They will happily work with Elementor Pro Archive template but not Jets. Sooo...

As it looks like this is unlikely to be fixed I will have to abandon Jet plugins altogether as this is a complete dealbreaker. I'll have to try and style Elementors rather basic product archive using something like Ele Custom Skin purely so I can go back to using the Yith Quick View plugin, but I doubt I'll be able to have it looking quite as nice. Unfortunately functionality is more important that cosmetic appearance so no choice.

Crocoblock if you are reading this go and buy Yith's plugin and study the code because I can assure you that Ajax works just fine on Add To Cart buttons in a popup. You are basically crippling your own product by failing to provide this basic function.

**Comment by Fulcanelli60** [comment]
@NeoAcla if you are desperate I have found a work around until Crocoblock decide to add this feature. 

You'll need the Yith QuickView plugin. It still doesn't work on the product grid when used for the Products template BUT it has a shortcode and that _does_ work on Jets Archive page (and of course Elementors Archive template).

Therefore create an archive template in Woobuilder and set it in Woocommerce settings as the custom archive page. Emulate your design as best you can from the product grid and add the shortcode where you want it. No need for any parameters, just the basic code. It will have the settings you have set in Yiths plugin. Viola, QuickView with Ajax and you can set it to not close the window afterwards.

Admittedly I prefer the design from the Woobuilder Product Grid with the Jet Popup QuickView but this is near enough and just needs a few CSS tweaks to get it looking as before. I only used the Popup for the Quickview so that has been deactivated until Crocoblock fix this feature.

Hopefully now they have seen it is definitely doable they will add this function asap. :)

**Comment by rtpHarry** [comment]
@UraraReika What do these tags "pending" "ready for release" mean, as its now 2022 and I've just encountered the same problem.

Followed this tutorial:

https://crocoblock.com/knowledge-base/articles/how-to-create-a-product-quick-view-with-jetwoobuilder-and-jetpopup/

And ended up with an "add to cart" button that is wrapped in a `<form>` tag pointing at the product single url, so when I try to use the quickview it doesn't work how I would expect and just quickly add a product to the cart.

It seems like maybe there is some missing documentation. From looking at the changelog I can see in v1.12.1 this line:

` * Fixed: Close quick view popup after adding product to cart;`

Which sounds like ajax add to cart should work.

**Comment by UraraReika** [comment]
Hello @rtpHarry !

If the issue is closed then this tags means nothing. 

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team.

Thank you!

**Comment by rtpHarry** [comment]
I worked with support and they found the setting "Use AJAX Add to Cart" was not checked:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/1038062/182601774-78b0e7c6-aa66-4b5f-8074-d4f8cdcab722.png">

This fixed the issue I was experiencing.

It is not mentioned in that tutorial so it should probably be updated.

**Comment by UraraReika** [comment]
> I worked with support and they found the setting "Use AJAX Add to Cart" was not checked:
> 
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/1038062/182601774-78b0e7c6-aa66-4b5f-8074-d4f8cdcab722.png">
> 
> This fixed the issue I was experiencing.
> 
> It is not mentioned in that tutorial so it should probably be updated.

This tutorial has nothing related to Single AJAX Add to Cart functionality so it is not mentioned.

**Comment by rtpHarry** [comment]
I was just sharing what fixed things for me.

I wasn't really trying to get any support, sorry for polluting this issue thread, I just wanted to round it out for anyone that ended up on the same journey as me:

  - I followed the tutorial. 
  - When I tried it out and clicked the add to cart button in the popup it redirected to the product single.
  - I wanted it to just add to cart and stay on the page. 
  - I ended up on this thread trying to find a solution

The solution is that checkbox in the image, and it's not covered in the tutorial.

In my opinion, having the quickview quick to use is an essential part of the quickview functionality.

**Comment by sabbirahasanhabib** [comment]
> I was just sharing what fixed things for me.
> 
> I wasn't really trying to get any support, sorry for polluting this issue thread, I just wanted to round it out for anyone that ended up on the same journey as me:
> 
> * I followed the tutorial.
> * When I tried it out and clicked the add to cart button in the popup it redirected to the product single.
> * I wanted it to just add to cart and stay on the page.
> * I ended up on this thread trying to find a solution
> 
> The solution is that checkbox in the image, and it's not covered in the tutorial.
> 
> In my opinion, having the quickview quick to use is an essential part of the quickview functionality.

Can you plz clarify how do you solve this brother? I was using archive product template and product loop widget for the pop up..but the add to cart redirects to single product page
