### ISSUE TITLE
JetEngine - Do not store media, which is to be uploaded to media library by the form, until Submit button is clicked

### ISSUE THREAD

**Issue by ihslimn** [Crocoblock/suggestions#1638]
If the media field in the form has Insert attachment option enabled,
media will be uploaded to the media library _before_ the click on the Submit button.

Can behavior be changed so that the file is not added before submit or deleted if the user left the page without submitting the form? (Also, if the user chooses another file)

**Comment by RibeiroM4E** [comment]
Adding more info to Ihslimn´s request:

People registering at my website are being able to upload images through the media field without clicking at the submit button. So, when they are chosing images through the media field, all those images are uploaded to the media library at Wordpress. The correct way to upload those media files should be only after they click at the submit button and get stored at its respective post.

This is a common feature in ACF, for example.

Also, I´ve received this answer from Kate at Croco:
 
"You are correct, once the user chooses an image or a file, it automatically is being uploaded to the Media Library (as it has to be stored somewhere). If you want it to be uploaded ONLY after a user clicks on the Submit button you should use the "Cache form output" option in the Form widget Content settings. But be ready that there might be a situation when the user filled out the form and have chosen the wrong format of, let's say, an image -> he'll get the error message and will have to fill out the form one more time. So, I would recommend you to specify what formats of media files users are allowed to upload through the form."

So, there is a big issue with that.

If we activate that option at the frontend Edit Form, all the info which is stored at the CPT is not shown to the user. I´ve deactiveted it and I could see the info again. How can we let that option activated and in the same time, at the Edit Form, the filled info is shown to the user?
 
Also, with that option activated, there is no preview of the image and some of the conditional logic don´t work.
 
PS.: Should be great when the user changes that image through the Edit Form if it is replaced, instead of letting the old image stored at the media library. In fact, that image should not be stored at all at the media library (as commented above).

**Comment by nreljed** [comment]
#3885

**Comment by girafffee** [comment]
This behavior was fixed in JetFormBuilder (since version 2.1.0)
