### ISSUE TITLE
Making Plugins automatically compatible with JetWooBuilder templates

### ISSUE THREAD

**Issue by Hameedhudeen** [CrocoBlock/suggestions#1666]
Hi,
I have been using JetWooBuilder to build my custom product page and shop page template for a while.
I noticed a lot of plugins lost compatibility with the custom templates.

Take for example, recently I installed [this product waitlist (Back in stock notifier) plugin](https://woocommerce.com/products/woocommerce-waitlist/), which inserts a product subscription button into the single product page using add to cart hooks. But since I'm using a custom product page template, the plugin can't insert the subscribe button using hooks.

I think this can be sorted out if we integrate the default woocommerce product page hooks like these:
https://www.businessbloomer.com/woocommerce-visual-hook-guide-single-product-page/

into the JetWooBuilder elements. I.e, including "woocommerce_before_add_to_cart_button", "woocommerce_after_add_to_cart_button", along with the JetWooBuilder Add to cart elementor element.

Please let me know your comments on this. I think this can solve majority of plugin compatibility issues easily.

**Comment by UraraReika** [comment]
@Hameedhudeen, hi!
The reason is not in the templates themselves, but in the widgets that use, but in our plugin, when creating widgets, we use default Woocommerce functions to ensure maximum compatibility with the Woocommerce plugin itself, as well as the themes that use it. 
This means that all hooks and filters provided by Woocommerce in their areas will work and can be used side by side with our widgets. The hooks( `woocommerce_after_add_to_cart_button, woocommerce_before_add_to_cart_button` ) you cited were tested with our widget and everything worked as it should.
