### ISSUE TITLE
Докрутить элемент Хотспот в JetElements

### ISSUE THREAD

**Issue by smoookeee** [CrocoBlock/suggestions#19]
Приветствую, по элементу хотспот сделал мини-обзор сравнения этого элемента в исполнении JetElements и  PowerPack. Интересует 2 момента: 1-картинка вставляется не полностью и размывается 2-лаги и задержки при выставлении меток и  подгрузке фона-картинки, собственно само видео по траблам по ссылке: 
https://www.dropbox.com/s/7smahmm3g5c6un2/Video_2019-02-12_155332.wmv?dl=0﻿

**Comment by CrocoBlock** [comment]
Dear customer, 

Thank you for sharing this information. 

Please, note, that this log is used mainly for the feature requests, all the issues should be processed in our support help desk https://kava.ticksy.com/ . It is important as we can't reproduce the issue from our side, so the issue might be caused by conflicts on your end. Please, make sure to submit a ticket and let our support team handle this case. 

Also, please, pay attention that it is recommended to submit feature requests in English only, as it is important for every member of the community to understand the feature to prevent duplicated requests. 

Best regards from CrocoBlock team
