### ISSUE TITLE
Check out and Cartpage support for Germanized and GermanMarket

### ISSUE THREAD

**Issue by fatjay1979** [CrocoBlock/suggestions#1920]
Some Country like Germany have special rules for e-commerce. That means you need to show specify information
all the time on the Products and in the Cart.  
For this reason ( and others )  Germanized and GermanMarket have been made. In Germany 
every WooCommerce pages uses one of those plugins. So its really IMPORTANT that those plugins
work with your Cart and Checkout Widgets. As a German Shop you cant run a website without it.
Here the Links to the Plugins 

https://vendidero.de/woocommerce-germanized
https://marketpress.de/shop/plugins/woocommerce/woocommerce-german-market/

**Comment by tomherold** [comment]
Yes, please -you have the best checkout tool.

**Comment by UraraReika** [comment]
Hello @fatjay1979 !

During the development of the functionality of custom woocommerce pages, we did not pay any attention to third-party plugins like the ones you gave as an example. Even though they are necessary in your country. But everything that has been done fully complies with the standards of woocommerce and fully supports its functionality, because we did not rewrite it, but only divided it into parts for easy customization.

Also, our team has not come across such plugins and does not know its capabilities that are needed for the functioning of a store in your country. Everything should work well initially. But if something is wrong, could you please specify the places so that we can adjust the compatibility.
