### ISSUE TITLE
JetProductGallery for Woocommerce Single template

### ISSUE THREAD

**Issue by Rstoelwinder** [CrocoBlock/suggestions#1933]
Hello dear Dev Gods,

We, as in me and my designpartners would love to use your JetProductGallery in the Single product for our Woocommerce shops. Unfortunately this is not quite possible at the moment since you have to set a specific product ID for each gallery on the specific Single template.. I hope this message is clear enough yet, I will post a couple of pictures down below.

![image](https://user-images.githubusercontent.com/63161353/94678275-80382f00-031e-11eb-918d-69f25adb61f4.png)
The product ID you have to add for the JetProductGallery to get the correct pictures.

![image](https://user-images.githubusercontent.com/63161353/94678621-13716480-031f-11eb-98ab-dac311a18b3c.png)
We would like the JetProductGallery to automatically grab the images from the product like the text, price and main image blocks do.

I don't check GitHub that often, if you have any questions because I am unclear or you just want a quick chat, send an email to info@yoursim.store

Thanks in advance! Kind regards from the Netherlands, Roelof Stoelwinder

**Comment by UraraReika** [comment]
Hello @Rstoelwinder!

Despite the fact that the widget has the Product ID option this does not mean that this field is required. This option is made so that you can use these widgets anywhere on your site. But if you leave this field blank and use it on Single Product Template widget to automatically pull the needed pictures.
