### ISSUE TITLE
Compatibility with WooCommerce Product Bundles

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#2002]
We need to add a second add to cart button just after the first product description.
https://woocommerce.com/products/product-bundles/
As the Product bundles output is hooked in to the add to cart button hook it also shows all individual items descriptions - which we don't want in the top section.

There is a addon to do this, but it doesn't work with your templates
https://github.com/somewherewarm/woocommerce-product-bundles-top-add-to-cart-button/blob/master/woocommerce-product-bundles-top-add-to-cart-button.php
It does work if we revert to the default woo template.

Also the Add to cart button  itself doesn't work with Product Bundles.

**Comment by UraraReika** [comment]
Hi @pumpCMS !

The functionality of the plugin you have given does not work, because the hook that is used in the `'woocommerce_single_product_summary'` plugin is absent from us, since this whole block is detailed into separate widgets and is not needed.

You can use the existing hooks: `'woocommerce_before_single_product', 'woocommerce_after_single_product'`, or rewrite the template of one of the widgets to add the hook you need using `do_action ('woocommerce_single_product_summary');`.
