### ISSUE TITLE
JetEngine: Listing Grid "Inject alternative listing items" in last position

### ISSUE THREAD

**Issue by petranca** [CrocoBlock/suggestions#2086]
Until now there is no possibility to display a (static) item as "Inject alternative listing items" in the last position. We can "only" set the position number or display it in the first position.

However, if the number of posts (e.g. products or by filtering) is dynamic, it would be good if you could set a static item always at the last position of the listing grid. 

It would be sufficient, for example, if you could only enter "-1" for the position number or if you enter "99999" although there are not so many posts.

**Comment by zanga7** [comment]
![Screenshot at Nov 01 15-28-30](https://github.com/user-attachments/assets/b5260c79-ec26-46b9-a16a-51b33fcfad94)

I see this as done, but cannot achieve it. Is there a guide?
Currently, the -1 is showing on the first page of the pagination rather than the list of all items on the page pagination page.
