### ISSUE TITLE
Ability to add coupon form below checkout order review.

### ISSUE THREAD

**Issue by TODO4EVER** [CrocoBlock/suggestions#2283]
Hey, I can't add the coupon form below the checkout order review in the checkout page. https://i.imgur.com/lpDuaxf.png
While it can be done. Clicking on apply coupon places the order. https://i.imgur.com/MSHH1y9.png
Placing it this way, break the widget, I can't style it at all, and it automatically opens without having me click on "Click here to enter your code". I thought this was a bug but I asked support about it and they said it is NOT a bug, and it is a new feature that I can request right here, so here I am.
My issue in action: https://i.imgur.com/kRw4RNT.gif

**Comment by UraraReika** [comment]
Hello @TODO4EVER !

Basically it's not a bug as not a feature. To be clean lets go through functionality. We have two fields for picking templates, and one of them has description https://prnt.sc/w6ztnv, about widgets that you should use in this template. This description not for description you literally should use it in this template, because Checkout template is wrapped in form tag, what makes whole this template a form and according to markups rules you can't put form in to other form. My point that not only    Coupon form, login form from widgets of checkout page, all the forms.
