### ISSUE TITLE
JetWooBuilder - enhancement

### ISSUE THREAD

**Issue by Phukit** [CrocoBlock/suggestions#2302]
Hi,

I would like to put forward a new enhancement for the plugin.

Everything is all over the place.  Can we simply consolidate things and make things easier please.

1. Combine woo page builder and the Jetwoobuilder settings tab together under one roof, and simply have the woo page builder menu item that has the pages tab and the settings tab.

2. After combining them can we move the menu item ' woo page builder' under the elementor menu item of 'templates' 

This would make things much much easier, faster and productive when creating pages and having to switch between all these setings/pages.

3. can you put a back to builder button on each page editor screen.  So when you are done editing that page it is easier to go back to the builder and start a new page or edit the settings.

4. can we have a widget to move the woocommerce notices to a different location and disable the default location.

Thanks and is a great plugin!

**Comment by UraraReika** [comment]
Regarding points 1 and 2. Due to Jet Dashboard this two sections cannot be merged, because we try to separate widgets settings and templates. Same thing with Elementor menu item. We keep our functionality separate from other things in one place, so you can easily find any functionality connected to our products.

Basically we don't edit page content directly, in plugin we override Woocommerce template in which insert the custom template made with Elementor. In this case we cannot achieve what you want but in the future we will implement kind of similar functionality when you can open template edit page from Woo Page Builder menu item, which has this button.

As for notices we will rework them in the future updates. You can track updates in this issue https://github.com/Crocoblock/suggestions/issues/2249.
