### ISSUE TITLE
Jet Dashboard generating errors

### ISSUE THREAD

**Issue by ciprianpentelescu** [CrocoBlock/suggestions#2342]
Notice: Undefined index: product_category in /wp-content/plugins/jet-elements/includes/modules/jet-dashboard/inc/license-manager.php on line 335

The error shows in admin when in debug mode. Im using the latest version of the plugin.
Here:
		return array(
			'key'     => $filtered_license['licenseDetails']['license'],
			'product' => $filtered_license['licenseDetails']['product_category'],
			'type'    => $filtered_license['licenseDetails']['type'],
			'expire'  => $filtered_license['licenseDetails']['expire'],
		);

**Comment by UraraReika** [comment]
Hello @ciprianpentelescu! Reactivate your license key.

**Comment by Brink67** [comment]
Hello, how do we reactivate the license key?

**Comment by UraraReika** [comment]
@Brink67 please contact our support team they will help you.

**Comment by Brink67** [comment]
Actually, I already figured it out. Jet-Engine alone is not enough to "reactivate" a license. I installed the Jet-Theme-Core and realized immediately how the license worked. It has just been a couple years since I originally installed and I forgot about the theme core because I only use the Jet-Engine portion on this particular site. Thanks

**Comment by webcoreinc** [comment]
Crocoblock / Jet Plugins are complete garbage and will crash your site. They conflict with just about everything.

These plugins cause fatal errors on about every update. We are considering legal action against the company for damages.
