### ISSUE TITLE
PAYMENT GATEWAYS IN JetEngine FORMS

### ISSUE THREAD

**Issue by EvgenDoman** [CrocoBlock/suggestions#2401]
I wanted to see payment gateways for visa cards and other cards in general. As well as such payment systems as Yandex money and qiwi.Very lacking

**Comment by natuliazh** [comment]
Послностью согласна с Евгением!

**Comment by stasonua0** [comment]
+1

**Comment by FrencharmeMedia** [comment]
Yes!! would be awesome to have payment possibilities like (paypal/stripe/mollie) inside formbuilder
i know you have a paypal feature to copy inside but would be awesome to have it directly inside because i need a solution without woocommerce (because not possible with woocommerce). Otherwise great job!

**Comment by bellotaweb** [comment]
+1 for adding a Stripe payment gateway to Forms

**Comment by debihazelden** [comment]
I'd like to see Stripe available in Jet Engine forms. At the moment I have to go with Piotnet Forms and ACF as Piotnet does Stripe transations and also Piotnet doesn't integrate fully with Jet Engine. I'm using their form to Submit a Post and it won't save a Jet Engine repeater. It would all be so much easier if I could just use Jet Engine as the form to submit post and take payment!

**Comment by EvgenDoman** [comment]
+1 for adding the Yandex. Money payment gateway

**Comment by MathiasVignes** [comment]
+1 stripe payment gateway or woocommerce

**Comment by Noob86** [comment]
+1 (or as many as possible) for adding Mollie to Jet Formbuilder! 🙏🏼🙏🏼

**Comment by Floydtm** [comment]
https://crocoblock.com/knowledge-base/articles/jetengine-how-to-add-payment-gateway-to-the-form/

**Comment by MjHead** [comment]
We added Stripe gateway (https://jetformbuilder.com/addons/stripe-payments/) and WooCommerce checkout action (https://jetformbuilder.com/addons/woocommerce-cart-checkout-action/) as addons for JetFormBuilder. At the moment we not planning to add any additional gateway because of heavy load with other features. When we'll finish all already planned improvements we'll return to this issue.
