### ISSUE TITLE
Show users on maps listing with JetEngine

### ISSUE THREAD

**Issue by simonvanoordt** [CrocoBlock/suggestions#2415]
**FEATURE REQUEST/BUG**
Make it possible to show users on maps as well. Right now, the we are able to show custom post types on maps, but not users. This restriction seems artificial. Please add support to show users on maps as well.

**Why?**
First, many people on facebook are interested in this feature and it saves the need to buy expensive plugins that do almost the same thing as JetEngine's Maps Listing widget.

Second, implementing this feature should be **low effort high reward**. JetEngine already supports user listings, so almost the entire infrastructure for this feature is already there.

**Comment by davedenis** [comment]
100% agree on all points. Adding a field to a user and allowing the User post type to be put on a map seems like low hanging fruit.

**Comment by LiciMay** [comment]
I am surprised this is not possible yet? This should not be hard to fix. I have a client that shows users on maps but I used a custom solution. Would be really neat to do it with jet engine in the future. Then users can update their own address as well. If I may add, it would be nice to use the default address field from WordPress and woocommerce as well if possible. Otherwise, a custom field from the profile builder would do

**Comment by rentaterry** [comment]
+1

**Comment by bennybersier** [comment]
Please pretty please 😀 
Would be very useful when creating a mini membership project

**Comment by futureyoon** [comment]
Hi 
I would like to check with @simonvanoordt 
when you mentioned 'user' means the author of the post? and ensure to display the author profile picture (WP native) on the map as a marker? 

I posted this question on FB https://www.facebook.com/groups/CrocoblockCommunity/permalink/4003662549725136 
I just wanted to confirm this is the same request. so that we can combine the effort. 

Thank you! Cheers!

**Comment by simonvanoordt** [comment]
@futureyoon "when you mentioned 'user' means the author of the post?" Yes a user could definitely the author of a post, it could also be someone with a different user role.

"and ensure to display the author profile picture (WP native) on the map as a marker?" Yeah I agree, it would be handy if support for native wp fields is included to avoid duplicate meta fields that hold the same information

**Comment by futureyoon** [comment]
Thank you for the confirmation! We need this feature! 
+1

**Comment by julianderyk** [comment]
+1

**Comment by kaskad88** [comment]
Added in JetEngine 2.8.5

**Comment by simonvanoordt** [comment]
Awesome, I'll try it on a client's website tomorrow!
