### ISSUE TITLE
Add payment integration for booking form

### ISSUE THREAD

**Issue by flyingcompass** [Crocoblock/suggestions#245]
Ability for user to submit payment when submitting booking form, possibly tie into Woocommerce payments, or directly with PayPal, Stripe, etc.

**Comment by MPHood** [comment]
+1

**Comment by vargasraquel** [comment]
+1

**Comment by smarthaha** [comment]
+2

**Comment by MjHead** [comment]
Done

**Comment by UraraReika** [comment]
This functionality has been present in the plugin since version 2.0.0. For more details, you can use the following articles: https://jetformbuilder.com/features/how-to-configure-payment-gateways/, https://jetformbuilder.com/features/how-to-store-paypal-payments-from-wordpress-form-in-database-tables/ .

There is a small tweak when using the booking action with payments. For booking action, you need to set up an event to prevent conflicts with payments. The event is set as follows:

- Press Edit Conditions & Events button on the action - https://tppr.me/2MwSTs
- Switch to Events match tab - https://tppr.me/OhNYWl
- Select DEFAULT.PROCESS - https://tppr.me/bDGmM and press update to save

If everything is okey you will see selected event on the action component card - https://tppr.me/QQwaBF 

Please [contact](https://support.crocoblock.com/support/home/ ) our support team  if you have any difficulties.

Thank you!
