### ISSUE TITLE
JetWoo: issues with custom my account page endpoints

### ISSUE THREAD

**Issue by getwebcare** [CrocoBlock/suggestions#2574]
Recently custom my-account endpoints were introduced and that is awesome. However, I have a few problems.

**1. My Account Dashboard Template / works great.**

**2. My Account Orders Endpoint Template / works but has issues.**
"My Account → Orders" endpoint does not show template when there is no order.

And shows template when there are orders.

"My Account → Orders → View Order" endpoint does not show template when viewing order.

**3. My Account Downloads Endpoint Template / Same issues as Orders, does not show template when there are no orders.**

**4. My Account Address Endpoint Template / works but has issues.**
"My Account → Address" endpoint works fine.

"My Account → Address → Change Address" endpoint does not show template.

**5. My Account Edit Account Endpoint Template works but after saving changes redirects to dashboard without any notification of saved changes.**

**6. The payment-methods and add-payment-method endpoints are missing completely from JetWooBuilder options.**

payment-methods

add-payment-method

**Comment by getwebcare** [comment]
I am sorry, my mistake. Crocoblock support helped me. Turns out I did not use the My account content widget properly. Using the widget fixed everything.

**Comment by VaniaRensi** [comment]
Hi, I'm having issues too in working with endpoints. Could you please explain what your error was?

**Comment by getwebcare** [comment]
Yea, I used the wrong widget on my-account page.
So the way it should be in WooPagebuilder:
Your create My Account page in jetwoo and then use only Myaccount Dashboard widget for that page.
Then with other account pages you simply use the corresponding widgets and style how you like it. Once done you set the endpoint pages in woocommerce -> settings -> JetWooBuilder options.

**Comment by VaniaRensi** [comment]
Oh! Thank you! I'll check it now on my website!🙏🏻

**Comment by VaniaRensi** [comment]
Nope, it doesn't work for me...  I'll stick to the other method explained here 
https://www.youtube.com/watch?v=d6seAhww8Qs&t=383s&ab_channel=Crocoblock
and wait for a video tutorial on endpoints 🤷🏻‍♀️

Thanks anyway!

**Comment by kervis** [comment]
i have the same problem, how fix?

**Comment by VaniaRensi** [comment]
Hi, I asked for support at CrocoBlock and gave them the website credentials. They fixed the problem and when I asked them for explanation they pointed out this setting has to be this way in order for endpoints to work.

I hope this can help you!

![Schermata 2021-03-31 alle 11 18 19](https://user-images.githubusercontent.com/81430689/113121321-cfe6ad00-9212-11eb-940d-aec608d5f598.jpg)

**Comment by ClearianDev** [comment]
VeleaWeb,
 
 I cannot thank you enough for the kindness of posting this solution.  I've spent hours baffled by this and almost undertook Paul C's (WPTuts [great guy and vids]) approach using code and the functions.php page.  Two backup restores and hours later I found your post.  Thank you so much.
 
 Patrick

**Comment by ideabusiness** [comment]
Help please, I'm getting crazy!

I have an issue when I call "edit" an address.
It returns to first selected table (dashboard) and there is no way to edit.

If I **Enable custom my account page endpoints** in WooCommerce => JetWooBuilder it works but no more in my tabs and once I've edited an address it loads a page named "my-account/edit-address".

How can I solve this issue please?

**Comment by UraraReika** [comment]
@ideabusiness please contact our support team.

**Comment by Hurcann** [comment]
Hello, 

I'm having similar type issues that I've now been working on for weeks (I'm embarrassed to say). 

I have a long dialogue open with Crocoblock support but at this point they're just copy/pasting the same response over and over. I'm hoping someone might be able to help here. 

I followed the new crocoblock tutorial for making endpoint templates in jet woo builder and assigning them in woocommerce settings.

I then created a new menu with the endpoint templates. 

I created a seperate jet woo page for "My Account" --> I inserted the vertical mega menu in one column and the "My account content" widget in the other column (just like in the tutorial). 

The issue I cannot solve is --> there is no automatic connection between the menu I created and inserted and the my account content widget. The only thing that loads (automatically, not connected to the actual menu button) in my account content widget is the dashboard. Please see the attached photo for how it looks. 

The menu items do not display the endpoint templates I created. 

I did have some slug/permalink issues that I thought would solve the problem but did not. All my slugs match through woocommerce and the endpoint template. 

I'm hoping someone can at least lead me in a direction to try something new to fix it because I'm ready to pull my eyeballs out over this problem :) 

Thank you.

<img width="1143" alt="Screen Shot 2021-11-03 at 1 18 58 PM" src="https://user-images.githubusercontent.com/93670341/140150743-35e85a0a-2136-4dac-a23d-974f2ed81bbb.png">

**Comment by ClearianDev** [comment]
Hi,I assume you are using the Profile Builder function.  If so, did you perform the initial task of "Import Presets" described in the tutorial video(s) for "Front End Post Submissions" or "Profile Builder?"Thanks,Patrick Cunningham Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Hurcann ***@***.***> Date: 11/3/21  10:25 AM  (GMT-08:00) To: Crocoblock/suggestions ***@***.***> Cc: ClearianDev ***@***.***>, Comment ***@***.***> Subject: Re: [Crocoblock/suggestions] JetWoo: issues with custom my account
  page endpoints (#2574) 
Hello,
I'm having similar type issues that I've now been working on for weeks (I'm embarrassed to say).
I have a long dialogue open with Crocoblock support but at this point their just copy/pasting the same response over and over. I'm hoping someone might be able to help here.
I followed the new crocoblock tutorial for making endpoint templates in jet woo builder and assigning them in woocommerce settings.
I then created a new menu with the endpoint templates.
I created a seperate jet woo page for "My Account" --> I inserted the vertical mega menu in one column and the "My account content" widget in the other column (just like in the tutorial).
The issue I cannot solve is --> there is no automatic connecting between the menu I created and inserted and the my account content widget. The only thing that loads (automatically, not connected to the actual menu button) in my account content widget is the dashboard. Please see the attached photo for how it looks.
The menu items do not display the endpoint templates I created.
I did have some slug/permalink issues that I thought would solve the problem but did not. All my slugs match through woocommerce and the endpoint template.
I'm hoping someone can at least lead me in a direction to try something new to fix it because I'm ready to pull my eyeballs out over this problem :)
Thank you.

**Comment by Hurcann** [comment]
No I'm not. I'm using JetWooBuilder widgets in combination with the woo page builder templates.

**Comment by Green-Angels** [comment]
Hi Hurcann,

I have exactly the same issue, there is no automatic connection between the mega menu and content profile widget..  Have you found a solution to your problem ?

**Comment by Green-Angels** [comment]
I found it. It justs because i changed before all my account terms.. 

For all people who will have an issue to connect their account mega menu with the content profile widget : 

> Go to General Woocommerce Settings 
>  Go to "Terms Account" 
You have to copy all woocommerce terms (address etc) and paste for your menu urls. 

https://domain-name/my-account/**term-you-defined**/

**Comment by kelvintai** [comment]
how do i customize my-account/edit-address/billing/ and/shipping? as there are no editor or template for them. anyone has any idea?

**Comment by ClearianDev** [comment]
Crocoblock WooBuilderSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: kelvintai ***@***.***> Date: 5/15/22  10:39 PM  (GMT-08:00) To: Crocoblock/suggestions ***@***.***> Cc: ClearianDev ***@***.***>, Comment ***@***.***> Subject: Re: [Crocoblock/suggestions] JetWoo: issues with custom my account
  page endpoints (#2574) 
how do i customize my-account/edit-address/billing/ and/shipping? as there are no editor or template for them. anyone has any idea?

**Comment by kelvintai** [comment]
> Crocoblock WooBuilderSent from my Verizon, Samsung Galaxy smartphone -------- Original message --------From: kelvintai ***@***.***> Date: 5/15/22 10:39 PM (GMT-08:00) To: Crocoblock/suggestions ***@***.***> Cc: ClearianDev ***@***.***>, Comment ***@***.***> Subject: Re: [Crocoblock/suggestions] JetWoo: issues with custom my account page endpoints (#2574) how do i customize my-account/edit-address/billing/ and/shipping? as there are no editor or template for them. anyone has any idea? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

This is a blank reply right?

**Comment by ClearianDev** [comment]
Hey,

Sorry about that.  I just replied to the email - which is a no-go with Git.

To modify pages within the "Account" group, you can use Crocoblock WooBuilder - which has a number of additional custom template options like Cart and Checkout, etc.  I believe WooBuilder is included with the Jet Engine app.  There are great YouTube videos from Crocoblock and a guy named Paul from WPTuts.  E.g. https://www.youtube.com/watch?v=Q6lBJZ_BR_A 

Good luck,

Patrick

**Comment by ClearianDev** [comment]
P.S. To find WooBuilder, mouse over the Crocoblock menu item in the WP Admin dashboard.  You'll see it there.  No idea why they put it there.  P.S. Crocoblock apps work primarily with Elementor Page Builder - although some work with Gutenberg.

**Comment by kelvintai** [comment]
Yes, am currently using Woo Page Builder. Everything is fine with it except under My Account >  "Edit" Address > Address (Billing & Shipping) Form. I can't seem to find anywhere to customize this particular form.

**Comment by ClearianDev** [comment]
Oh... that...  

That's a task that has to be hand-coded via the functions.php file - and ideally within a child theme functions.php file.  Otherwise updating your theme/Wordpress version can/will overwrite/delete your customization.  

https://stackoverflow.com/questions/42341548/add-a-custom-field-to-woocommerce-billing-form
