### ISSUE TITLE
Jen Engine Forms PDF Generator Email

### ISSUE THREAD

**Issue by stasonua0** [CrocoBlock/suggestions#2609]
Hello, consider generating the content of the letter in a PDF file and sending it to the mail as an attachment

/*Оригинал*/
Здравствуйте, рассмотрите возможность генерировать содержимое письма в ПДФ файл и отправлять его на почту как вложение

**Comment by kochhase** [comment]
very complex. I use gravity forms with the there pdf generator for that kind of things.

**Comment by stasonua0** [comment]
Users of the Dynamic OOO and Piotnet add-ons already have this opportunity, so I want any Crocoblock to keep up)

**Comment by NeoAcla** [comment]
Been waiting this since last year for PDF.

i check Dynamic OOO seems promising, but it seems they are more focus on PRO version of Elementor with their high end widgets you need to have a Pro version of elementor before you can use it.  Unlike Crocoblock you can use all their widget whether you are using Elementor Free or Pro version. Specially now, Elementor Pro are going to change their pricing.

Anyway, hope Crocoblock can catch up also to the effects of Dynamic OOO specially on the Dynamic Posts v2. This is where crocoblock is a bit behind in terms of effects features

**Comment by serg-pervushin** [comment]
+1

**Comment by BatcomAus** [comment]
Most form makers have this functionality, or you can talk to someone like E2PDF and get them to integrate their plugin with yours. Also there are multiple requests similar to this, can't someone from Crocoblock tidy it up so we only have to vote on 1

**Comment by gguzzman** [comment]
I ask you, is there a long way to go for this function of Jet Engine Form ->>> PDF Generator?

**Comment by WordpressTodayAgency** [comment]
Any updates on this request?

**Comment by Crocoblock** [comment]
Hello! I am glad to inform you that we have just released the PDF Attachment Addon. Feel free to [check it out](https://jetformbuilder.com/addons/pdf-attachment)
