### ISSUE TITLE
Infinite scroll (and other Listing Grid capabilities) for Products Loop

### ISSUE THREAD

**Issue by hybridmuse** [CrocoBlock/suggestions#2638]
Please add the same Infinite scroll capabilites from Listing Grid to Products Loop.

In fact, it would be make sense to have all Listing Grid features into Products Loop. For now, the only content options for Products Loop are the switcher options.

Thank you

**Comment by UraraReika** [comment]
Hello @hybridmuse!
In 1.7.5 version of JetWooBuilder we added compatibility with JetEngine listing. It means that if you create listing for Products then in editor you can use Archive Product WIdgets, and when you create listing for Product Categories - you can use Archive Category Widgets. Then of course you put this listing in listing grid, make it carousel with any option and query it whatever you want. But in this case you couldn't use template switcher because it different widget.

**Comment by tizum** [comment]
hello guys, i was looking for this solution and i ended up getting here, this is a great idea.

i need to display all my products when accessing the shop page, because i made an exclusive design with quickview option using archive item from jetwoobuilder when clicking on the add to cart button, but i am having trouble showing all my products and organizing them using product loop widget

please add more features to it as it has in listing grid for jetengine, because working with the customization of woocommerce products is very difficult, even using jetengine, as it loses some features, such as the option to add products to the cart without reloading the pages using the listing grid.

Thank you, have a great day!

**Comment by hybridmuse** [comment]
It is unfortunate that there are so many listing widgets, yet all only provide a small subset of functionalities. Wouldn't it be simpler for both the devs and us jet users to have 1 universal way of listing content, with all required functionalities (custom templates, infinite scroll, filtering, etc), that would support Post Types, Taxonomies, Woo Products, and every other type of data?

**Comment by UraraReika** [comment]
> hello guys, i was looking for this solution and i ended up getting here, this is a great idea.
> 
> i need to display all my products when accessing the shop page, because i made an exclusive design with quickview option using archive item from jetwoobuilder when clicking on the add to cart button, but i am having trouble showing all my products and organizing them using product loop widget
> 
> please add more features to it as it has in listing grid for jetengine, because working with the customization of woocommerce products is very difficult, even using jetengine, as it loses some features, such as the option to add products to the cart without reloading the pages using the listing grid.
> 
> Thank you, have a great day!

Ajax add to cart functionality works proper.

**Comment by UraraReika** [comment]
> It is unfortunate that there are so many listing widgets, yet all only provide a small subset of functionalities. Wouldn't it be simpler for both the devs and us jet users to have 1 universal way of listing content, with all required functionalities (custom templates, infinite scroll, filtering, etc), that would support Post Types, Taxonomies, Woo Products, and every other type of data?

The most universal way to listing your content is JetEngine and with last JetWooBuilder update it can use Archive widgets in Listings templates which make Woo Products listings more flexible.

**Comment by hybridmuse** [comment]
Thank you for getting back @UraraReika 
I'm sorry I had misunderstood your first comment.
Really glad to see the Listing Grid becoming more and more powerful!
This is exactly what I hoped for. Cheers

**Comment by hybridmuse** [comment]
Could you just specify how to link the Listing Grid to the JetWooBuilder Quick View popup?
Is there a special Custom Selector Trigger?
Thank you

**Comment by hybridmuse** [comment]
Also, when using Listing Grid for products now all Woo-related JetSmartFilters seem to not work?
Image filter, price range, etc.

**Comment by UraraReika** [comment]
> Could you just specify how to link the Listing Grid to the JetWooBuilder Quick View popup?
> Is there a special Custom Selector Trigger?
> Thank you

For now, in this case you need to create quick view popup like for Listing grid. That mean you need to create popup content from scratch with dynamic widgets.

**Comment by UraraReika** [comment]
> Also, when using Listing Grid for products now all Woo-related JetSmartFilters seem to not work?
> Image filter, price range, etc.

You need assign filter for listing grid, because you put woo builder widget to listing grid, so from now on it is listing, and you should filter listing

**Comment by hybridmuse** [comment]
Thank you for the guidance, it's all working perfectly! This new integration is really a game changer for our shop :)

**Comment by hybridmuse** [comment]
Just a notice, JetReviews aren't working for now inside Single Product Popups using JetEngine.
It says "JetReviews unavailable for this type of post".
