### ISSUE TITLE
JetEngine Forms: Send an OTP Code to verify the User's Email Address After Registration.

### ISSUE THREAD

**Issue by Andy-roberts-101** [CrocoBlock/suggestions#2647]
Can The JetEngine Forms Send an OTP Code to verify the User's Email Address After Registration?

![OTP DEMO](https://user-images.githubusercontent.com/79126415/108015704-d6401180-7036-11eb-91bc-0263ba688e64.png)

**Comment by Miguel2162** [comment]
The OTP verification or the implementation of email verification by token or link would help, it is something that they have pending for the part of registration and user login

**Comment by lifeact** [comment]
+1

**Comment by mgrant0** [comment]
I also need something like this to validate that the person submitting the form is indeed the person who owns the email address.

**Comment by maurocarreraok** [comment]
+1 There should be a way to send an email for account activation or something... And as bonus Social Registration integrated with FormBuilder :D

**Comment by liranbp** [comment]
+1

**Comment by CarrnellTech** [comment]
+1

**Comment by pgjdh** [comment]
+1

**Comment by panathos** [comment]
+1 we need this

**Comment by jorgesan07** [comment]
+1 🤞

**Comment by olpo24** [comment]
+1

**Comment by putrawmedia** [comment]
+1

**Comment by morosmo** [comment]
+1

**Comment by salahalldhabi** [comment]
+1

**Comment by breakused** [comment]
+1

**Comment by olpo24** [comment]
That would be very useful for jetformbuilder too!

**Comment by arekuki** [comment]
+1

**Comment by pauserratgutierrez** [comment]
OTP, 2FA email / SMS for Registration and Login is a must. Have a look at Microsoft's login system too, where there's no need for password anymore, a mail is sent with a code that you use as your temp credentials.

Here's a summary of similar requests:
https://github.com/Crocoblock/suggestions/issues/4581
https://github.com/Crocoblock/suggestions/issues/4093
https://github.com/Crocoblock/suggestions/issues/3893
https://github.com/Crocoblock/suggestions/issues/2960
https://github.com/Crocoblock/suggestions/issues/4628

**Comment by unitedonline** [comment]
It has been over two years and everyone is patiently expecting this. Do we have any news on this?

**Comment by mishave** [comment]
+1.2

**Comment by salahalldhabi** [comment]
+1

**Comment by unitedonline** [comment]
OTP via VIBER / SMS etc. This is a must for verifying registered users especially for posting classified ads.

**Comment by sekhsoyebali** [comment]
+1

**Comment by ninjamasterchris** [comment]
+1

**Comment by ninjamasterchris** [comment]
I found this. Maybe it helps. 

https://www.youtube.com/watch?app=desktop&v=Ylx1MWK57oM

**Comment by girafffee** [comment]
Hi everyone)
Currently, a 3.2.0 version has been published that includes the ability to perform almost any action (including user registration) after verifying the email address.

It works like this:
1. User enters login and email address
2. The entered address receives a letter with a link
3. When clicking on the link, registration takes place.
(more details [here](https://jetformbuilder.com/features/how-to-create-registration-form-with-email-verification/))

The only action with which verification **_will not work is User Login_**, which is available in JetFormBuilder PRO. In short, this is due to security reasons. Therefore, we will need time to implement two-factor authorization via email
