### ISSUE TITLE
News, popular, bestseller badges on product images

### ISSUE THREAD

**Issue by Magn2871** [CrocoBlock/suggestions#2680]
It would be very much appreciated if we could get the opportunity to add more badges to the products. Right now we can only add a badge for sale. I would like to add a badge for "new products", "Popular" products and so on. I know that this would increase the conversion rate for e-commerce shops.

Best regards
Magnus Guldbech
www.guldbech.dk

**Comment by P-happiness** [comment]
+1
I agree 100%.
Until now I'm forced to apply a sale price to each New product in order to display a custom "NEW" badge in my Custom template "New Arrivals" based on Tag Taxonomy.
Mine is just a trick, but this is not the proper way to organize a shop.
A New product shouldn't be on sale at first place... 
I hope in this feature...

**Comment by 79ho3ein** [comment]
+1
This is a great idea. I hope it will be added soon.

**Comment by Lonsdale201** [comment]
+1

**Comment by UraraReika** [comment]
Hello @Magn2871 !

You can use this [solution](https://github.com/UraraReika/jet-woo-builder-custom-product-badges) in closest time will be added to [Crocoblock DevTools ](https://crocoblock.com/freemium/tools/).
