### ISSUE TITLE
JetBooking add a way to block booking on certain days.

### ISSUE THREAD

**Issue by NicolasMarkl0** [CrocoBlock/suggestions#2701]
Where the feature should be:
JetBooking Plugin in the Post Type of the Booking Instances

What it should do:
The feature should enable you to block the booking unit or instance from being booked on certain days. 

Example:
We provide Coworking Spaces. We do not want anybody to book on the weekends. We have a room which is reserved for a customer on tuesday. So you should not be able to book it on tuesday. Because it is every tuesday we do not want to book it for every week seperatly. 

Thank you!

**Comment by sandornemeth86** [comment]
I hope Crocoblock team picked this up and will integrate it soon. I wouldn't have thought that this feature is not included in JetBooking. Please if you can, take this issue seriosly, because considering that this is a booking plugin, this feature should be a really basic one.
I bought the license and I am waiting. There is no workaround at this point.

Many thanks.

**Comment by ghost** [comment]
This would be a great addition to the booking plugin

**Comment by BlueteraLLC** [comment]
I agree.  This should be an option.

**Comment by UraraReika** [comment]
Hello everyone!

This functionality was presented in 2.5.0 version. You can fell free to check it out.

Thank you!
