### ISSUE TITLE
Add to Cart (Archive) - Change/Edit the button label "Add To Cart"

### ISSUE THREAD

**Issue by Ven3NuM** [CrocoBlock/suggestions#2722]
There is no way to change/edit/translate the "Add to Cart / Select Options" button label.
It could be nice to have the ability (maybe at Content Tab), to change the label's value directly or get the value from "Dynamic Tags"

**Comment by UraraReika** [comment]
Hello @Ven3NuM !
To achieve needed result you can use this plugin https://wordpress.org/plugins/wc-custom-add-to-cart-labels/. Despite old updates everything works as should!

**Comment by mikblizz** [comment]
Bought the JetWooBuilder for custom e-commerce pages very strange that it does not have the possibility to change the Text on the "Add to cart" button. I use Elementor and I have not seen that before since all other plugins I have tested has it. This should be implemented more plugin just slow down the site

**Comment by kochhase** [comment]
Yes I can find an way to change the Add to cart text. https://wordpress.org/plugins/wc-custom-add-to-cart-labels/ is to old to use an other Plugins are not working. I only see Add to cart or "In den Warenkorb" CSS ist not working as well.

**Comment by dbfischer** [comment]
+1
I also want to change the text only on this button (and not generally) or use the cart icon instead
or best: free icon and free text
