### ISSUE TITLE
Add monthly booking option

### ISSUE THREAD

**Issue by timo-mediad** [CrocoBlock/suggestions#2771]
Hello,

i can see that by now you are able to switch between daily and weekly bookings for the jetBooking Plugin.

I want to request a function where i am able to switch to a monthly booking. So a user can only book a room for full month periods. Similiar when someone would rent a flat/house.

**Comment by ewebtechsuk** [comment]
I really need this option, this will be a gamechanger, please crocoblock team if you can look into this I am sure this is very easy to do.

**Comment by Msirprism2** [comment]
Yes, much needed.

**Comment by Savit52flutter** [comment]
Hi, any update on this feature?

I would love to get this plugin but I need this to make the purchasing decision.

Regards

**Comment by UraraReika** [comment]
Thanks for the feedback and sorry for the late reply!

Unfortunately, we do not plan to introduce such functionality into our plugin. However, we recommend you to use our Documentation for JetBooking calendar JS API, where you can find examples of how you can customize the calendar so that it works the way you need it. 

For example, here is the easiest solution to your problem:
```
add_action( 'wp_footer', function () {
	echo '<script>
		jQuery( document ).on( "jet-booking/init", () => {
			window.jetBookingState.filters.add( "jet-booking/input/config", ( config ) => { 
				config.batchMode = "month";
				
				return config;
			} );
		} );
	</script>';
} );
```

Simply add this to your `functions.php` file in child theme.

If you have more complex requests I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.
