### ISSUE TITLE
Report an annoying problem with all crocoblock plugins

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3057]
I work with the hello elementor template. And unfortunately all the buttons (like the Add to Cart or Apply Coupon button) when clicked, the margins turn black. And I have to go through all of them, outline:none;  give and this is very time consuming. Of course, apparently this problem only exists in the Windows Chrome browser. Please check. Thank you.

**Comment by UraraReika** [comment]
Thanks for the feedback.
Please follow guidelines for opening a new feature request, so we can help you better. 
This report is missing key information:
* Steps to reproduce the behavior.
* Expected behavior.
* Screenshots

Without it - it is hard for us to filter and prioritize the requests.  Thank you for your understanding.

**Comment by 79ho3ein** [comment]
Like this photo: https://prnt.sc/11x1clz
When the buttons on jet plugins are clicked, their margins turn black.

Thank you for your attention

**Comment by kamyabnazari** [comment]
I have also the same problem. The jet search widget turns its margin black.

**Comment by UraraReika** [comment]
This problem not about plugin, but about theme you use. If we take Hello Elementor theme then we can find [this styles](https://tppr.me/ilzjO). And this is [theme styles ](https://tppr.me/5blns) for sure.
