### ISSUE TITLE
Please improve the appearance of the variable product box.(jet woobuilder plugin)

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3148]
Currently this box does not have a good user interface. Especially in Firefox browser : https://prnt.sc/12ax5nw
I have suggestions for this section that I offer to you :
1- Please enable this so that we can customize more. Just like a payment part : https://prnt.sc/12ax5nw
2- Please allow us to align the text with the variable option.As shown in the image, the text is higher than the variable option : https://prnt.sc/12axkfk
3- Please move the hover or active mode to the variables field so that we can style it separately : https://prnt.sc/12axufc
4- Please add this feature so that we can place the desired icon for this section, such as the svg icon : https://prnt.sc/12ay5se
5- The last thing that matters is that when the variable option is enabled, the available options have a very inappropriate context.
It would be great if we could edit these fields, because it already has a very old and inconvenient user interface.The desired section is specified in the image : https://prnt.sc/12ay1vr
This personalization can include: background color, hover or active mode, border, etc.

Thank you for your efforts

**Comment by 79ho3ein** [comment]
@UraraReika 
It also has a color background that is not adjustable. And it must be changed with code : https://prnt.sc/12b72ny

Thank you for your attention.

**Comment by UraraReika** [comment]
This widget is complex and unites all the things connected to single add to cart and how its transform depending on product type and product condition. First off all the ui that you see in different browsers it's how browser itself render default html elements. 

1 - you can customize select element quite good. 
2 - You can do it with the help of css, we will not add controls because of specific elements position and this will cause more problems.
3 - need more details
4 - we will not add this
5 - need more details

And use our templates for creating issues.
