### ISSUE TITLE
Report a bug in the jet search plugin.please check

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#3357]
The cancel search button has many bugs.I will report these bugs below. Please review and resolve them. https://prnt.sc/13frlh1

1- Sometimes it does not display properly. That is, it is not displayed at all.
2- Sometimes displayed as two dot (..). The bug is too bad.
3- This button (Close Search Button) does not exist in the Firefox browser!
In general, this section has a lot of bugs that need to be thoroughly investigated.

Finally, I had a request ..
Please add this feature so we can customize the search cancel stall.
Customizations such as:
Resize, change color, load custom icon and position.

Please check. Thank

**Comment by Floydtm** [comment]
1 - we have no problem with this (because the plugin does not have this icon in the settings)
2 - the icon can be added from the theme itself
3 - it depends on the browser. 
Have you contacted our support team? 
Why do you write requests without understanding how our plugins work? 
Most of your requests are solved with simple settings.
Thank you!
