### ISSUE TITLE
Query Builder - SQL - AND/OR

### ISSUE THREAD

**Issue by hum-bug** [CrocoBlock/suggestions#3372]
Hi,

I like the new query builder function but the SQL option seems to be missing AND/OR capability which is a basic but important part of SQL queries. 

Here is an example query I want to do where I'm a CCT is linked with a BuddyPress group.  It works manually but no way to enter this into the Query Builder that I can see. 

```
SELECT
    wpqo_jet_cct_example.name, wpqo_jet_cct_example.date,  wpqo_bp_groups.name

FROM
    wpqo_bp_groups_members, wpqo_bp_groups, wpqo_jet_example
WHERE
 wpqo_bp_groups_members.user_id = 1 AND 
    (wpqo_bp_groups_members.is_admin = 1 OR wpqo_bp_groups_members.is_mod = 1) AND
(wpqo_bp_groups_members.group_id = wpqo_jet_cct_example.group_id) AND
(wpqo_bp_groups_members.group_id = wpqo_bp_groups.id)  
```

(note my user_id  =1 would actually be current logged in User ID so I would be using one of the variables in the query builder for this). 

At the moment because there is no AND/OR option I can't create this query in the query builder.

Thanks,

Paul

**Comment by hum-bug** [comment]
Another option could be to add the option to put in the raw SQL code and insert dynamic variables. This would be a really powerful feature as would be easy to get custom data and then use Crocoblock listing grid to display it nicely without much work.

**Comment by ssoronid** [comment]
+1

**Comment by kaskad88** [comment]
Added in JetEngine v3.2.0

**Comment by xitromedia** [comment]
This should be setable not only globally for all WHERE clauses but also between them, to be able to make more complex queries.

Also it would be great in that context if WHERE clause items could be made dependent on the existence of the query variable when using the query variable macro. Currently the query variable must always exist because it is always included in the query. But e.g. when using jetengine in connection with jetsmarfilters query variables may or may not be submitted. 

I used a workaround for these fields with LIKE as compare operator, but that results in a senseless xxx='%%' and slows down the query. And when using the equal operator  "=" i get no results when using an AND connection and when the query variable does not exist, although the query would return items without existing query variable, which is wanted for dynamic queries with query variables.
