### ISSUE TITLE
JetWooBuilder - Ability/Widget to fetch a single attribute to design a product loop 

### ISSUE THREAD

**Issue by decorear** [CrocoBlock/suggestions#3403]
Im trying to design a product loop by adding a badge of single attribute on top of a product picture.
For example, for a glossary store, the weight attribute of a product is needed to show on all packages.

Please add a widget or ability to fetch data from woocommerce product attribute to show in any location on the Woobuilder page, so i can move it on top of a product feature image to design a product loop.

I already talked to Julia, and she said this functionality is not available at the moment.
![Screen Shot 2564-06-01 at 16 55 41](https://user-images.githubusercontent.com/2740376/120304736-4038aa00-c2fa-11eb-82f7-9ddcc253f72c.png)

**Comment by Floydtm** [comment]
You are right, now there is no such functionality. However, this can be done with jetengine. I will not argue because I do not know how everything is set up. You can also try to rewrite the widget template and display the information you need. I need to send you back to the support team so that we can study the request on your site. Thank you!
