### ISSUE TITLE
JetSmartFilters - Range price filter with tax option

### ISSUE THREAD

**Issue by Steriotis** [Crocoblock/suggestions#350]
When you making a price range filter for WooCommerce products, the dynamic **WooCommerce min/max prices** selection applies the prices without tax included.

Please add the option to select and apply the  **WooCommerce min/max prices** with tax include/exclude from the price range filter.

**Comment by SargasTM** [comment]
it's impossible to do
this is not even implemented in the woocommerce itself

the problem is that each product may have a different tax
example on a standard woocommerce shop with a standard range Filter by price

there are 3 products with these prices
<img width="613" alt="image" src="https://user-images.githubusercontent.com/5094971/205045988-1adc45e3-69ea-49c0-851f-0e311c6b5e19.png">

on the frontend prices and a range filter look like this
even sorting by price looks wrong
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/5094971/205046784-099f6954-45db-4a62-9dda-483e99d322c9.png">

this is because glasses have a lower price than a belt, but the tax is higher

for woocommerce this is normal behavior
we use the methods and functions of woocommerce, so the JetSmarFilters have the same behavior
