### ISSUE TITLE
Display the remaining special sale time in the jet woobuilder plugin

### ISSUE THREAD

**Issue by alexandra9941** [CrocoBlock/suggestions#3720]
hi😊
It's amazing to add the "Sales Countdown Timer" feature to jet woobuilder. I recently installed the jet woobuilder plugin but surprisingly did not find this feature.
. Lack of this feature and the like in jet woobuilder can cause users to distance themselves from this plugin. This feature is available in most store theme. Of course, there are plugins for this, but why shouldn't jet woobuilder have it?
For special sales products, the expiration time is considered. This feature displays this expiration time to users,To know what time is left from the special sale.
![Screenshot (93)](https://user-images.githubusercontent.com/87675033/126839168-35432478-eb61-4ddb-8b44-00e87786c33b.png)
This feature is required for the jet woobuilder plugin. Because the jet wobbler must meet the needs of a store site. 
I hope I have convinced you. thanks

**Comment by UraraReika** [comment]
Hello @alexandra9941 !

You can use JetElements widget Countdown timer in combination with elementor dynamic tags functionality.

**Comment by 79ho3ein** [comment]
hello @UraraReika 
Wouldn't it be better to have this feature directly in the jet woobuilder?
It really does not make sense to install an additional plugin for just one feature. This is one of the most important features that jet woobuilder lacks. Every store site has this feature. Because this is a feature that is very important for users, because with it users see when there is a product discount left.
If this feature is added to the product grid widget, it will be great. I will show you an example of what I saw on a website, I hope it is convincing :
![Screenshot (94)](https://user-images.githubusercontent.com/77163248/127043989-f5505ec5-b81f-45b9-8223-85a0eb4abd6b.png)
Finally the decision is with you...
thank you

**Comment by UraraReika** [comment]
This issue has been closed due to inactivity. If this issue is still actual, please, create the new one.
