### ISSUE TITLE
Appointment reservation system/addon

### ISSUE THREAD

**Issue by mustafamohsen** [Crocoblock/suggestions#378]
I’ve noticed the recent addition to CrocoBlock family **JetBooking**

I suggest a more general booking system, which may be used for booking appointments, hotel rooms, clinic visits, or whatever

Some suggested features:
- Multi-asset booking (multiple rooms, doctors, coaches, etc)
- Connecting to payment system (WooCommerce etc)
- Custom calendars for each asset

**Comment by mustafamohsen** [comment]
Here are some other suggested features:

* Defining multiple types of resources to book. For example, a shared clinic will have several rooms, and several doctors, which might need to be reserved interchangeably
* Set different reservation statuses (unconfirmed, tentative, confirmed, canceled,...etc.)
* Connect to a product (WooCommerce?) for ticket reservation
* Export event to iCal and Google Calendar

**Comment by mustafamohsen** [comment]
I'm willing to collaborate with your team on this project in analysis and design, possibly user testing. I have quite an experience in the matter. If interested please let me know

**Comment by aksamitnaya** [comment]
We’re really grateful for your idea! Indeed, we’re planning to create such an addon, however, we supposed it to be done as a standalone plugin, not as a part of JetBooking. Currently, we’re finishing a development cycle concerning JetEngine 2.0 version, the release of 1st stable version of JetBooking and some other parts of Crocoblock as a whole. Once everything is done, we’re going to start working on the new addon, hopefully, it could be done within a few next weeks. We will continue cooperation with you during the process of its development.
 
The only point is that we’d like to make the development of this addon as public as possible and engage more people to collect information and feature requests from a wider audience. 
So, you’ll be able to leave all your offers and functionality suggestions regarding the Appointment plugin here. We, on our part, will provide you with the most detailed feedback about the development process. Also, we’ll provide with plugin’s working versions when they are ready. 

We’re open to any suggestions from your side and we’d appreciate if you provide your ideas in detail, so we could start working on the Appointment plugin.

Thank you in advance!

**Comment by mustafamohsen** [comment]
@aksamitnaya 
Sounds great! Yes, I believe it should be a standalone plugin. And yes, more openness to public will provide you greater opportunity for feedback and feature development from actual users

And yes, I will work on a document explaining features in details, with a few use cases for demonstration

And also yes, I appreciate keeping me updated with development status

Please expect that document within a few days, which I'll post here for discussion and further development by you and the community

**Comment by mustafamohsen** [comment]
# Appointment Management System

## Use Cases

1. Meeting reservation
Employee A wants to schedule a meeting with employee B. A will need access to B's calendar, and will probably also need to reserve a company resource (meeting room). Room (as a resource) reservation is subject to avaiabilty. B shall be notified via emaiil (or whatever)

2. Service session reservation
Client wants to reserve a coaching (or conaulting, tutoring, etc) session with a coach. (S)he need to go to his/her website and find an available spot, pick the reservation, and go to payment (WooCommerce or such)

3. Resource reservation
A coworking space facility that has a number of shared resources (e.g. Meeting room), where service subscribers need to reserve in advance before using it

The previous scenarios describe to reserve time spot (Scenario #2), a resource (Scenario #3), and both (Scenario #1)

## Suggested features

* Reserving appointments with notification to calendar owner, and iCal/Google Calendar integration for both
* Ability to make paid appointment with WooCommerce integration
* Ability to reserve resources (room, coffee machine, microphone, etc) either on its own or as a feature of the appointment
* Ability to update appointment status (unconfirmed, tentative, confirmed, canceled,...etc.)
* Setting rules for cancelation/rescheduling

These're my basic thoughts, I'll keep updating it

**Comment by mustafamohsen** [comment]
## More features

* Ability to select service type in the appointment (message, acupuncture, etc), with price setting for each, and allowing multiple services per appointment
* Customizable display of the appointments in front end (Month view, Week view, List view, etc)

**Comment by crypto-vault** [comment]
I find JetBooking a bit loosely coupled since it has no knowledge of other components like woocommerce for a more manageable booking system. 

A more integrated bookings system would be great, but make it more horizontal so that it could be used for different areas of business like accommodation, services, rentals, etc. 

So instead of just supporting calendar based appointments, where people have to select a date (and time) it should also support fixed date bookings. This is specially interesting for tours where the tour occurs at a predefined date (or date range). Also it should should support multiple predefined dates for the same event. This could be achieved with woocommerce variations but the new booking engine could be a wrapper to it. 

One of the features it should also support is the ability to add options to a product with their own price. For example “extra bed”, “welcome pack”, etc. That’s currently only possible with the addition of other plugins. 

I’ve done project development management for building booking systems from scratch so have extensive knowledge of the requirements of those systems. Count me in if you need more input.

**Comment by mustafamohsen** [comment]
@crypto-vault 
Good point

 @MjHead Please let us know how we can help

**Comment by mustafamohsen** [comment]
@MjHead would you provide us some update on this addon?

**Comment by MjHead** [comment]
@mustafamohsen Hi! Sorry for delay. Unfortunately release of JetEngine 2.0 took more time than we planned, so that why we can't start working on JetAppointment on that time we expected. Now we working on JetEngine 2.1. When we'll finish with it, I'll check all suggestions about Appointment plugin and determine features set for first plugin version. The I'll check if have all required functionality in JetEngine and JetSmartFilters plugins (because Appointment plugin will use these plugins as base). If JetEngine and JetSmartFilters will have all required functionality, we'll start working on Appointment plugin. I hope all of this will take 2-3 weeks.

**Comment by crypto-vault** [comment]
@MjHead Where will you draw the line between appointment plugin and booking plugin? Will JetAppointment allow bookings up to the hour when JetBooking is up to the day? I wonder for example for tours. If we have a tour you can select freely which day and hour we would use JetAppointment, but if it’s a multi day tour we would use JetBooking? Would it make sense to have a single plugin. Or you plan many different features that it makes sense to have separate plugins?

**Comment by MjHead** [comment]
@crypto-vault we are planning to make completely different UI/UX for Appointment and Booking. Also its a completely different logic in the code - checking availability, creating slots. So if we'll combine this in single plugin, mostly we'll need to write 2 different code bases inside on plugin. This could make a negative impact on plugin stability, performance issues etc.

**Comment by monkychilote** [comment]
Hi, good morning. I bought the complete crocoblock package a while ago, the truth is that I congratulate you because you have done a very good job. A little more support material is missing in Spanish but otherwise it is fine. My question goes on the side that the JetBooking plugins to create room or hotel reservations is great for the flexibility it gives to be able to create your own CPT and each of the dynamic fields associated with the reservation, but many of my clients request me that can be paid totally or partially, in addition to making the reservation. I have seen that several users ask for the same thing and I would like to know in which state the possibility of integrating this tool is, since the only way to be able to pay electronically in CLP, Chilean Pesos, is to integrate a payment gateway of Chilean banking media, compatible with woocommerce, which cannot be done at the moment. I would be grateful if you could indicate the possibility of integrating this functionality in the near future.

Thank you and very kind for your time.
