### ISSUE TITLE
Jetengine Dynamic field: Set character length to display in dynamic field

### ISSUE THREAD

**Issue by RodSuper** [Crocoblock/suggestions#396]
Hi,

I'm using the Dynamic field widget to display tags of a post. These tags are selected as checkboxes in the backend. However, this can create an issue as seen in the screenshot.

<img width="1241" alt="Screenshot 2019-07-26 at 20 18 40" src="https://user-images.githubusercontent.com/47865142/61972911-05210d80-afe3-11e9-9070-1d19c74d7429.png">

I wish you could set the character length to display. This will prevent the design from breaking.

Thanks in advance,
Roderick

**Comment by MjHead** [comment]
Hi @RodSuper. Sorry for delay with this issue. We trying implement it for 2.1 release and find that this implementation causing more problems than resolve. Its related with a lot of filtering and customizing options for dynamic field. That's why could be a lot cases when limiting characters output could break outputted HTML tags. So for such cases as your maybe will be better to limit output with custom CSS, for example something like this:
```
.jet-listing-dynamic-field .jet-listing-dynamic-field__content {
    max-width: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

**Comment by chiku789** [comment]
Hi I had raised a similar question and you have provided this code but now it's not working. Can you please update it.
https://gist.github.com/MjHead/812147fc2837e9420220848afaa682a7

**Comment by fakharbj** [comment]
This option appears in the list after you enable the Trim string callback toggle in the JetEngine > JetEngine Dashboard > Modules > External Modules tab. It displays the pieces of text from meta fields, options, etc., trimmed by the chosen String length value.
Enabling the Filter field output option allows you to display "Trim string callback" in the Dynamic Field widget of jet-engine.
