### ISSUE TITLE
Long term apartment booking rentals

### ISSUE THREAD

**Issue by ewebtechsuk** [CrocoBlock/suggestions#3965]
Just wandering if the crocoblock team can implement apartment booking for long term rentals like 3, 6,12 or 24 months and have the checkout field auto calculated when the user selects the rental term field. Also the pricing field to be calculated as monthly rental prices rather than nightly bookings

**Comment by Msirprism2** [comment]
Up ?

**Comment by ewebtechsuk** [comment]
Any updates?

**Comment by UraraReika** [comment]
Thanks for the feedback and sorry for the late reply!

Unfortunately, we do not plan to introduce such functionality into our plugin. However, we recommend you to use our Documentation for JetBooking calendar JS API, where you can find examples of how you can customize the calendar so that it works the way you need it. 

Although in situations of more complex requests we highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.
