### ISSUE TITLE
JetSmart Search: Allow to use JetEngine Listing to display result

### ISSUE THREAD

**Issue by jacktaffa** [CrocoBlock/suggestions#3987]
Can be possible to enable customization  result items on JetSearch  with Listing Settings? 
In particulary when you have a CPT or a CCT  with a lot of metas that probably should be better to show on search preview.

Also, Can be possible to enable to show realtime results on a  listing grid on the page? For example if I don't want to search using JetSmartFilters because it filter's my listing grid.  But if I'm showing a bit of my products on my catalogue but I want them to allow to search in realtime on that page all products.

**Comment by salbatyku** [comment]
+1 good request, i'm building a new website right now, an ecommerce and the clients wants to show for example the image of the brand instead of the product. I'm unable to bring taxonomy image to search result (at least from the front end point of view). The Listings module is one of the best from crocoblocks. If you guys could make it in such way so we can include it in search/cart-page (display a listing instead of that ugly table of products), etc. There could be a lot of good usage.

**Comment by MjHead** [comment]
Added with 3.4.0 update
