### ISSUE TITLE
Nested Repeater for jetengine

### ISSUE THREAD

**Issue by conradnoah** [CrocoBlock/suggestions#4024]
It would be great if you could allow for nested repeaters like they do in advanced custom fields. There is many use cases I have looked for this solution and it will make the jetengine plugin much better.

**Comment by nreljed** [comment]
#3514

**Comment by MolyMalon** [comment]
Totally agree!! I'm solving many fields with ACF even though I'm looking forward to doing it with Jet fields.
It would be great to be able to add repeatable fields inside other repeatable fields.

When in business projects the Companies can give you the option of being able to add different addresses but we cannot give the possibility of being able to add different telephone numbers and emails within these addresses since we do not have this possibility.

It would be great, as conradnoah says, to be able to limit how many repeater fields the user can add.

I still have to use ACF :( with its group of fields and repeatable fields,,,,,,, we need this versatility with Crocoblock fields,,, in the backend!!!

Many thanks..

**Comment by EliasAAA** [comment]
Is there any progress with this ?

**Comment by MolyMalon** [comment]
https://github.com/Crocoblock/suggestions/issues/3514

**Comment by josharroo1** [comment]
+1 for this. Completely necessary for more complex data management. Any workarounds in the meantime?

**Comment by MolyMalon** [comment]
I have found a solution while Crocoblock implements this functionality: https://www.gravityforms.com/add-ons/limit-submissions/

**Comment by MolyMalon** [comment]
> +1 for this. Completely necessary for more complex data management. Any workarounds in the meantime?

https://www.gravityforms.com/add-ons/limit-submissions/

**Comment by IFTTD** [comment]
It's been a couple years any Idea if Nested repeater fields is even going to be implemented. Seems Nested repeaters should be an essential.

**Comment by Crocoblock** [comment]
Hi
I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/784)
