### ISSUE TITLE
show bookings in profile

### ISSUE THREAD

**Issue by dehaas1982** [CrocoBlock/suggestions#4119]
Hello, i'm building a booking website with Jet Booking and Jet Engine. Does anyone of you have any idea to show the bookings in the user's profile? i can't find a way yet. Any help is welcome.

Regards,

Jeroen

**Comment by Hammer-ger** [comment]
You can do it with querry builder.
You have to create a sql querry.

But your booking-tabel has to be filled with the right data to connect with the users.

But be carefull you can't build a proper booking-Website with jetBooking, because there are a few major issues with jetBooking at the Moment.

I Hope they Will Update the Plugin and then it will ne very powerful i think.

**Comment by dehaas1982** [comment]
thank you Hammer!

i will try to create it. Allready contacted the Crocoblock support but there is still no update for it. 
keep you posted
