### ISSUE TITLE
Private/Individual Calendar for each user

### ISSUE THREAD

**Issue by SirL0fty** [CrocoBlock/suggestions#4138]
Hi,

I am creating a website for holiday home owners to rent out their properties similar to airbnb and would like the feature to allow each registered owner to have access to their own private calendar where they can add their availability. All these calendars would be searchable and the user can add and book out dates in there own account.

Happy to provide more details if needed.

Thanks

**Comment by Hammer-ger** [comment]
Hey,

This is allready possible.
Each coustomer has its own "Hotel" stored in a coustom data store.

Then you can realise it with a Special bookingform build into a listinggrid, That only shows the "Hotel" wich is stored in the users data store.

I would wait to use jetBooking for a real world project because at the Moment it is to buggy.
We uesed it one season and are looking for alternatives. When crockoblock Update jetBooking and put a Little Bit of Love to, than it would be absolut perfect. But at the moment it is no good choice to use in real world.

Best regards

**Comment by SirL0fty** [comment]
Thank you for your reply. Yeah Crocoblock looked really good for my needs to start with but there is a lot going on and it seems hard for a novice to get along with. I have just purchased Homey to try and so fair that looks really promising.

thanks
