### ISSUE TITLE
Add ability to change gallery direction in Single Images widget - JetWooBuilder

### ISSUE THREAD

**Issue by DmitryBychenko** [CrocoBlock/suggestions#4220]
Currently it is possible to choose the direction of the gallery just 1 time for all devices.
In reality being able to have gallery in different places (left, right, bottom) for different devices is logical and obviously expected.

[https://prnt.sc/1xe3lnr](https://prnt.sc/1xe3lnr)

Desktop has large screen, so we can place gallery on the side (left or right).
Smartphones have small screens, so in order to save room it is expected to place the gallery under the main image.

Please, add the ability to change location of the gallery for different devices.

For example, be able to set gallery on the left for desktop,
And on the bottom for smartphones.

**Comment by UraraReika** [comment]
Hello @DmitryBychenko !

Unfortunately this functionality can be implemented due to  Elementor restrictions. But there is hook which you can use to change direction in mobile view `jet-woo-builder/jet-single-image-template/navigation-direction`. This hook takes thumbnails direction value. Then you can use this [wp function](https://developer.wordpress.org/reference/functions/wp_is_mobile/) and change thumbnails direction.

If you are having difficulties with code implementing feel free to contact our support team.
