### ISSUE TITLE
Color swatches capability in the product grid widget / jet woobuilder plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4247]
hello
Today, the Color swatch feature is one of the most important parts of products in online stores And has been used on many websites.
Unfortunately, this feature is not available in jet woobuilder at this time. If this feature is added to the product grid widget, it will be a big step in the development of this plugin.
This feature is really a simple feature! **Using this feature in the product grid widget, we only inform users that these colors are available.**
Please look at these two pictures : https://prnt.sc/1xzikap & https://prnt.sc/1xziq07

As you can see in the pictures above, Color swatches are just a display aspect. Using them, the user is informed what colors are available from each product ...

What you need to customize this feature in the product grid widget :
1- size
2- border radious
2- border
4- Position of colors (Left, right, horizontal, vertical, up, down)
5- Number of shows (For example, we can specify that only 3 colors be displayed. If more, + is displayed instead of the fourth color. Like this : https://prnt.sc/1xzjvqb )

Please review this offer. Really needed. thank you🌹

**Comment by UraraReika** [comment]
Hello @79ho3ein !

You can use this [solution](https://crocoblock.com/troubleshooting/articles/fail-to-add-attractive-variation-swatches-to-woocommerce-archive-page/) for now.

**Comment by 79ho3ein** [comment]
thank you dear @UraraReika. Yes, I was aware of this solution. **But do you plan to localize this in jet woobuilder?**

**Comment by Lonsdale201** [comment]
> Hello @79ho3ein !
> 
> You can use this [solution](https://crocoblock.com/troubleshooting/articles/fail-to-add-attractive-variation-swatches-to-woocommerce-archive-page/) for now.

Dear @UraraReika. With all due respect. I am impressed by what you are doing, and there are few other development teams in this field who are as conscientious and listen to the community. However, it is important to note that this topic is a priority here and on your Facebook pages. You should hold a poll on this topic. One of the best arguments in your favour is that you have your own system that covers a significant part of the needs as far as the frontend part of webshops is concerned. Indeed, there is a way to bundle variationswatches with Jetwoo, but if you look it up it's a hassle. People like it when everything runs smoothly, and they don't have to fiddle around with files and write lines of code. That's why they use elementor, and that's the convenience they pay for. I think you could fit a "JetSwatches" into your portfolio, combined with your other extensions. You wouldn't need to rely on a 3rd party in this case, but could go all in-house. 

**Thank you for your work.**

**Comment by 79ho3ein** [comment]
hello @Lonsdale201, Thank you for your participation.
I believe jet woobuilder has the best developer. They really respect the opinions of their users. This is quite evident in recent updates.
But yes, the possibility of Color swatches is really essential. At #361, it has the highest turnout, and many users want this feature in the jet woobuilder. I think the developer intends to add this feature. Because #361 is pending. But the time is not clear. Another month, or another year.
**It should be noted that in this issue, I did not mean to suggest this Color swatches, to develop this feature on a single product page. Rather, it was developed in the product grid widget, so that we could display the available colors of each product to users.**
Either way, Color swatches are really needed. Whether for a single page or for the Product grid widget. Personally, I am counting the moments to add it.
I think your suggestion about creating a poll is great. With polls, things are going well.

thank you

**Comment by UraraReika** [comment]
Now this task is not in priority so please stay tuned.

I merged this issue with #361, which is on the same subject so we could deal with it more efficiently.
