### ISSUE TITLE
Jetbooking - Call webhook after checkout is completed by the user

### ISSUE THREAD

**Issue by nathannsc** [CrocoBlock/suggestions#4250]
[Jetbooking]

Hello everyone, about the google calendar integration, is it not weird that the webhook is called BEFORE the checkout is completed?

In this case, an event is created in google agenda before a person pays or completes the checkout. Meaning that a user can create many events in the google agenda without actually confirming the reservation.

It makes more sense to call the webhook after the checkout is finished - has someone been able to call a booking webhook after or at the thank you page?

**Comment by UraraReika** [comment]
Hello @nathannsc, thanks for the feedback.

If you setup your form actions like this https://tppr.me/4k7y then you definitely will not be able to call webhook after checkout. Because this webhook would works before you even get the checkout page. 

You can setup google calendar integration with the help of Appartment booking action like this
- https://tppr.me/e6ERn
- https://tppr.me/JWxum
- https://tppr.me/caKDZ
- https://tppr.me/VhUeF

Then you will be able to see it like this https://tppr.me/6yjFc in checkout page and this https://tppr.me/Eobu4 in thank you page.

Or you can use this article to achieve your goals https://woocommerce.com/document/webhooks/

Thank you for your understanding.
