### ISSUE TITLE
JetAppointment: Ability to give Non-Administrator user roles access to managing the appointments

### ISSUE THREAD

**Issue by IFTTD** [CrocoBlock/suggestions#4286]
Tight now an Editor can not manage appointments. Having access for other user roles to manage the appointments is definitely needed. At the moment only an administrator can do this.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin
You can install the user role editor plugin and configure the user rights you need.

**Comment by 23Chromosomes** [comment]
Please add this, it's actually mind-boggling how this isn't a feature. Any admin that gives his clients editor or store manager for WooCommerce accounts are simply locked out of using the appointment system. I can't give clients admin roles on these sites.

Using the user role editor plugin is not the solution, because you need to give manage_options for appointments to be available, and this also gives the account access to many other things they shouldn't have.

**Comment by awebguy99** [comment]
I completely agree with @23Chromosomes . This should be in core already!
I think most if not ALL digital agencies / web design companies do NOT give full admin rights to our clients (because that would be a recipe for disaster / broken site / more support issues).
We NEED to allow uses with Editor role access (or at least have a filter or something) to view/use appointments in the backend.

Come on @Crocoblock, please up your game, it's 2024.
