### ISSUE TITLE
Metafield for Dynamic Gallery

### ISSUE THREAD

**Issue by Andrenalina** [CrocoBlock/suggestions#4369]
Good morning!

My proposal is the following:

I am working on a project for a real estate agency. I have implemented a custom post type for the properties with a series of custom fields. Among them, a gallery field to load the images of the properties.

I've included a meta field that loads the dynamic image gallery for me and I think it would be very interesting if, in addition to the gallery, I could add a metafield with the information on the number of images as pagination. That is to say:

"Showing image 1 of 5, 2 of 5, 3 of 5, 4 of 5 and 5 of 5", for example.

This would be very interesting for projects that have an image gallery and the user can see at a glance how many images the gallery has without having to see thumbnails.

DEMO: ![Number-images](https://user-images.githubusercontent.com/83453925/142612271-0d5d4fd7-ff77-43eb-87bc-ceba076359d1.jpg)

For my part, that's it. Thank you for your attention.

You have a good day :)

Greetings!

**Comment by nreljed** [comment]
I encountered this problem here #4070 
and I tried to find a solution ... but I encountered only.. problems :( 
especially if your images are already uploaded in "Media ID" value
at the moment no way is possible to do what you want
unless this SOS call is heard by the concerned developers who have the power to change things.

If you look at all the issues that I post you will realize that I am only focusing on real estate site projects.
and jetengine has a lot of problems with this type of projects
maybe you will find answers to other problems.
if not, let's pray while waiting for a real awareness of the real problems that jetengine still neglects today
