### ISSUE TITLE
JetEngine:being able to add woocommerce products with profile builder

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#4390]
Hi crocoblock team 
Im working on a multi vendor website and I want to let vendors to upload their products from the profile (designed by jet engine) 

woocommerce can add variable products with different properties and costs، it will be wonderful, if it be done by jet engine forms. As the result we can design a profile like dokan plugin with the help of jet engine 

Please consider this necessary option, i saw this option in ACF frontend form which has completely woocommerce compatibility

Thank you

**Comment by mehdimoradi1500** [comment]
Hi @MjHead will you please consider this option for jet engine?

**Comment by Michaelgimii** [comment]
+1
It is great for users to be able to register their products on the website like a "store plugin". (Sales cooperation)

**However, to complete this feature, we need several features :**
1- Users can register a variable product.
2- After the user has added the product, it will be reviewed by us (the store manager) and will be published on the website after approval.
3- After confirming the product inserted by users, that product should be included in the WooCommerce product list: https://prnt.sc/20xdhz5
4- In the Products section, in front of the upload products, the username that registered it should be displayed : https://prnt.sc/20xdir8
5- In the WooCommerce products section, we need a new filter. So that we can filter products based on sellers. **For example, I just want to see the products that user x has posted on the website.**

hello @kaskad88 Please check these items. We really need them. thanks

**Comment by MjHead** [comment]
WIll be added as separate Post Submit action on next JetFormBuilder update

**Comment by mehdimoradi1500** [comment]
Thank you, I've been waiting for almost long time
