### ISSUE TITLE
Remove crocoblock productname in JetSmartFilter filter result URL string

### ISSUE THREAD

**Issue by pjfc** [CrocoBlock/suggestions#4482]
For some reason the original post [Crocoblock/suggestions/issues/243] was closed although (at least part of the) problem is not fixed.

In my case the slug is: /shop/jsf/jet-woo-products-grid/tax/

The fact that Crocoblock productname is in the url is a big no-no, and should be fixed with priority. Reasons:
- It looks unprofessional
- It is bad for SEO
And less important but more of an irritant:
- I do not want to advertise Crocoblock in every filtered URL

I would advise to choose a neutral term like 'filter' instead of '/jsf/jet-woo-products-grid' (or similar brand names depending on the object that is being filtered), and additionally the option to rename that part of the slug to something appropriate for the site in question.

As an aside: 
I also have no idea why the word 'tax' is at the end of the slug, but that may be specific for my site and not related to this issue.

**Comment by hamed-azimi** [comment]
Users really don't care and don't want to see jet-smart-filters or jet-engine or tax_query and... in the URL. Instead, they want to see very short and clear URLs.

Instead of:
site.com/?jet-smart-filters=jet-engine%2Fdefault&_tax_query_brand%5B0%5D=43&_tax_query_material%5B0%5D=9&_tax_query_color%5B0%5D=153

They want:
site.com/brand/lg/material/metal/color/black/

(very clean, short, and user-friendly)

The way it currently is, is very confusing, with an ugly URL, which is also not good for SEO. Imagine we want to share a URL of a page, where products are filtered based on 12 different fields/attributes. We end up having an essay instead of a short URL, which the user will have absolutely no clue what the URL is talking about.

On top of that, it is against the security in cases where we fully hide any evidence showing our website is based on WP. It literally exposes the fact that we use WP, and even some of the plugins we are using. Increases the change of attacks.

**Comment by ofmarconi** [comment]
1+

**Comment by BaronVonDerpsalot** [comment]
+1

**Comment by webdocdisain** [comment]
+1

**Comment by shahzaib786** [comment]
+1

**Comment by TipoSamuel** [comment]
It would be great to address this request because through these URLs we can make use of buttons with links or parts of the menu to direct the user to the page with the filters defined as we wish. 

A function that I consider super relevant but because the URL is not currently SEO-friendly and shows sensitive information such as the use of wordpress, name of plugins like "jet-smart-filters" and "jet-engine" makes it unusable.

**Comment by realstephenzhao** [comment]
And in this issue: https://github.com/Crocoblock/suggestions/issues/2660

**Comment by MjHead** [comment]
From 3.1.0 is possible with Alias functionality

**Comment by pjfc** [comment]
Hi Andrew @MjHead ,
I guess you're referring to this beta discussion:
https://github.com/Crocoblock/suggestions/issues/6509

Great that it looks like it will be solved soon!
