### ISSUE TITLE
Align add to cart buttons in products grid

### ISSUE THREAD

**Issue by guimontenegrodev** [CrocoBlock/suggestions#4487]
Hi, Crocoblock team!
It would be nice if we could align the "add to cart" button to the bottom of the row in the products grid widget. There is the option to equal column height, but unfortunately the button doesn't get affected by it.

Here's an example of what i'm talking about:

![example](https://user-images.githubusercontent.com/95832091/145313800-f71c565e-6dab-4901-bcac-786c07a2d045.jpg)

Thank you for the wonderful plugin!

**Comment by UraraReika** [comment]
Hello @GuiWP !

In situation with Products Grid widget we cant provide such an option because of presets and orders functionality. It's hard to calculate depending all options in which moment we need to implement this functionality. So in your situation I can suggest you to add some styles for this layout.

```
.jet-woo-product-button {
    margin-top: auto;
}
```
