### ISSUE TITLE
Add PDF mapping/generation to JetFormBuilder submissions

### ISSUE THREAD

**Issue by seangolding1987** [CrocoBlock/suggestions#4536]
I'd love to see this kind of functionality added to JetFormBuilder
https://ninjaforms.com/docs/pdf

One of my clients has a comprehensive online form. They would ideally like it filled out and then to receive an email with the submission entries in an attached PDF. The PDF could have company logo on it also. They have told me this will save them significant time. 

I'm going to have to move to Ninja Forms to achieve this, but would love to stick with JetFormBuilder. 

Thanks!

**Comment by D3663** [comment]
I second this request for JetEngine Forms. It can be used it many different scenarios.

Here is a tutorial that WPTuts did on a different plugin that has this.

https://www.youtube.com/watch?v=2qjpXPb7zvo

**Comment by Kezaro** [comment]
I would also like to request this feature. If implemented with Jetformbuilder or as a separate tool, it will allow the ability to use stored meta fields to create PDF documents. ie. 

- Auto Generated PDF Reports (Ability to create PDF Template from meta Jetengine fields and use it from the backend or from Jetformbuilder) 

Feature 1. Have a feature similar to Jetengine Query builder, that would allow for selecting meta fields from the database to use with predefined and/or user created PDF Templates that can produce a PDF document to print or email

Feature 2. Integrate with Jetformbuilder on the website, so that after a user fills out a form, there can be an option to generate a PDF with the fields of the form (based on the form and PDF template selected for the form at creation) and email it to client so they can print and hand into the Banks/Government Offices/Insurance Agents Etc...

These features can have many applications. I notice it was assigned to @girafffee last year which is great, any update on this so far?

**Comment by Crocoblock** [comment]
Hello! I am glad to inform you that we have just released the PDF Attachment Addon. Feel free to [check it out](https://jetformbuilder.com/addons/pdf-attachment)
