### ISSUE TITLE
Enable adding Custom Icon/logo on the JetMenu Bar itself

### ISSUE THREAD

**Issue by RoldanAncajas** [Crocoblock/suggestions#467]
Enable adding Custom Icon/logo on the JetMenu Bar itself.

If you notice most website have all there company logo side by side the Navigation menu. It sometimes replaces the home button/icon.

![4EF54451-AB0E-4511-A0DD-85CC703C4D5E](https://user-images.githubusercontent.com/48211630/63646317-1fb1e800-c743-11e9-93e5-ebd1400eda64.png)
![ADA618E4-80C3-4887-9F28-ECA4ACA42E13](https://user-images.githubusercontent.com/48211630/63646318-1fb1e800-c743-11e9-92ca-c933471e5155.png)
![CD7F5866-DC1F-497E-8011-F52F8234425B](https://user-images.githubusercontent.com/48211630/63646319-204a7e80-c743-11e9-88da-f2c7908f0e2e.png)

Best Regards,
Roldan
www.adamsproject.ph

**Comment by Floydtm** [comment]
@RoldanAncajas, Hi! It seems that your request needs another plugin. Use the [jetblocks](https://crocoblock.com/plugins/jetblocks/) plugin to build a header

**Comment by RoldanAncajas** [comment]
Hi Floyed,

Yes. Possible. But what we need is the capability putting our own logo in
line with the menu bar, just like any other website not just random font
awesome icons.

**Comment by Floydtm** [comment]
@RoldanAncajas, Hi! We will not add this for the menu at this time. There are other ways to realize your request. Thanks you!

**Comment by RoldanAncajas** [comment]
Ok Floyd.

Well then, I will just retract my subscription and find plug-ins that is
capable of doing this. I cannot afford to spend for another plug-in just
for a simple feature.

Thank you!

**Comment by aksamitnaya** [comment]
@RoldanAncajas We understand your concerns, however, please kindly note that we collect all feature requests here, on Github, in order to form our roadmap and indicate the directions of the development process. All the requests are prioritized by the popularity, relevance, and resources we’ve got.
Currently, we’re working on our plugins improvement as well as on developing brand-new ones. Your request is saved and our team will work on it in the future as soon as we can. 
Thank you for your patience and for understanding!

**Comment by RoldanAncajas** [comment]
Hi Flyod,

Thanks for your reply.

I have actually done a turn around by doing hardcoding tweaks instead.

I’ll still wait for your updates though.

Best Regards,

Roldan

**Comment by shinTM** [comment]
v2.0.4
