### ISSUE TITLE
Hover-in and hover-out delay settings in the Revamp JetMenu

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#4716]
It would be very appreciated if the Revamp mode of the JetMenu had the settings to control the hover-in and hover-out delay (the setting for time delay for opening and closing of the menu).
The default menu has the option to set the "Mouse leave delay". I would like to have an identical control in the Revamp mode as well as the control for the hover-in delay.

**Comment by hamed-azimi** [comment]
This indeed is a must, and warmly appreciated if added.

Lack of these options increased the chance of accidental opening of the menu, as well as the buggy closing of it, and as a result, brings a very bad user experience.

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by hamed-azimi** [comment]
Adding a single option to let us set a delay on hover-in and hover-out can solve a huge problem. Not sure why you close this easy feature request and leave us to deal with an annoying issue that we constantly receiving complaints about.

**Comment by PPharma** [comment]
Please implement this. Its critical for us. This functionality should never have been removed. I'd say this is a bug report rather than a feature request. 

The problem here is that the menu opens even if the user is quickly hovering over the menu and never intended to open the menu. We have a big menu that fills up a lot of screenspace. So without meaning to do so the user has blocked their screen.
Adding to this is that the menu will not close easily, which makes users really annoyed and angry. We get so many complaints because  the entire website is really hard to use due to this issue.

Please add options to stop the menu from opening immediately and to make the menu close quickly whenever the user hovers OR clicks outside of the menu.
The legacy version of jetmenu had these options for good reason. Now that these are gone in the revamped version, its a major issue.

**Comment by SINFOUND** [comment]
We need this issue resolved! Please crocoblock address this and solve our headache.
