### ISSUE TITLE
Allow multiple weeks bookings

### ISSUE THREAD

**Issue by ghost** [CrocoBlock/suggestions#4742]
When only week booking mode is enabled users should be able to book for N weeks

**Comment by UraraReika** [comment]
Hello @creativeprogramming! Thanks for the feedback and sorry for the late reply!

Unfortunately, we do not plan to introduce such functionality into our plugin. However, we recommend you to use our Documentation for JetBooking calendar JS API, where you can find examples of how you can customize the calendar so that it works the way you need it. 

For example, here is the easiest solution to your problem:
```
add_action( 'wp_footer', function () {
	echo '<script>
		jQuery( document ).on( "jet-booking/init", () => {
			window.jetBookingState.filters.add( "jet-booking/input/config", ( config ) => { 
				config.batchMode = "week-range";
				
				return config;
			} );
		} );
	</script>';
} );
```

Simply add this to your `functions.php` file in child theme.

If you have more complex requests I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.

**Comment by UraraReika** [comment]
Hello @creativeprogramming! Thanks for the feedback and sorry for the late reply!

Unfortunately, we do not plan to introduce such functionality into our plugin. However, we recommend you to use our Documentation for JetBooking calendar JS API, where you can find examples of how you can customize the calendar so that it works the way you need it. 

For example, here is the easiest solution to your problem:
```
add_action( 'wp_footer', function () {
	echo '<script>
		jQuery( document ).on( "jet-booking/init", () => {
			window.jetBookingState.filters.add( "jet-booking/input/config", ( config ) => { 
				config.batchMode = "week-range";
				
				return config;
			} );
		} );
	</script>';
} );
```

Simply add this to your `functions.php` file in child theme.

If you have more complex requests I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/ 

Thank you for your understanding.
