### ISSUE TITLE
Filters don't work on Elementor Popup

### ISSUE THREAD

**Issue by hamed-azimi** [CrocoBlock/suggestions#4749]
Hello,

I use JetSmartFilters to add product filters.

When I directly add the widgets/filters in an Elementor template, everything works just fine.

But when I add those filters inside a popup created by Elementor Popup, it doesn't work.

(In this article you mentioned the filters still don't work inside Elementor Popup, but it works in JetPopup: https://crocoblock.com/troubleshooting/articles/cannot-display-smart-filters-in-popup/)

But it's better to have the support for Elementor Popup as well and make it an option for each person to choose which Popup system they want to use. In our case, for example, we need to avoid adding more plugins, especially when we already have 99% of the features of that plugin built-in into another plugin that we are already using.

Hopefully, you have a fix for this, as it is critical for us to get this work with Elementor Popup, as we want to have a useful mobile version of our filters.

Thanks

**Comment by 79ho3ein** [comment]
Hi, #3146

**Comment by Medienor** [comment]
You need to use JetPopup

**Comment by Michaelgimii** [comment]
> You need to use JetPopup

Yes, but it does not make sense to install an additional plugin for a simple feature. While elementor has pop-up.
The less plugins, the better.
I think Crocoblock does not intentionally add this feature. Because it wants to keep users dependent on their plugins. Otherwise, we all know that adding this feature is not a difficult task for such a large company.

**Comment by nreljed** [comment]
welcome to all of you

n° #3865 here 🙋

you are a bit late 😅

now folder "filters on elementor pro popup"

contains 3 complaints

you have to find other people and tag them to pass this request 🙏

the more people ask for this integration, the more it will be taken into account

**Comment by nreljed** [comment]
another solution is in the case where the crocoblock team absolutely wants jetpopup to be considered as an alternative to elementor popup.

it is also their right to defend jetpopup because :) 

yes, jetpopup also does things that even elementor popup won't be able to do.
at some point or time of any project..
you will surely have to call

![Capture d’écran 2022-01-29 191855](https://user-images.githubusercontent.com/82481592/151673056-c0e717e9-a4c5-4fdd-a052-962516989bee.png)

in this case you will have to install jetpopup..

the best answer to this dilemma (to have 2 popup builders)

is to update jetpopup to the same level as elementor..

- possibility of preveiw post #4622
- rearranging the options menu to simplify them
- take SEO into account ([Why Elementor Pro Popups Are Terrible For SEO](https://www.youtube.com/watch?v=3X0T2M0Pi1Y))
- probably new settings (animations etc)

a little facelift to bring jetpopup up to date 📆 
and definitely bury elementor popup enterrer⚰ 

In both cases there is an important decision to be made.

upgrade jetpopup to the next level and keeping the crocoblock ecosystem alive.
or 
just make jetsmartfilters compatible with elemetor popup

**Comment by 79ho3ein** [comment]
Friends, jet smart filters will support elemental pop up in the future, but it will take time. Developers response :

**Floydtm**
Guys, you must understand that this takes time. In addition to requests for the git, our team also has a road map. Right now you can use jetpopups they are compatible with our filters. You can also wait until your request is completed. Thank you!

**Comment by MjHead** [comment]
fixed with 2.3.10

**Comment by steve-ryan** [comment]
Does it support elementor popups?

**Comment by aalexandr21** [comment]
@steve-ryan 
yes

**Comment by steve-ryan** [comment]
> @steve-ryan 
> yes

Unfortunately have tried and isn't working

**Comment by aalexandr21** [comment]
@steve-ryan 

Please, contact [our support team](https://crocoblock.com/help-center) regarding this case and create a ticket including access details for the site where the issue occurred to ensure we can help you.
