### ISSUE TITLE
Suggestions for developing a product list widget + bug

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#4780]
**Please, describe the feature request, making it clear to understand.**

hello

The product list widget is great in its own right. But in contrast to the product grid widget is very weak. Please if possible consider the following to develop this widget.

**Suggested features :**
1- This widget does not have the "Mobile Hover on Touch" option.
2- It also lacks the "Make Product Item Clickable" option.
3- I do not think this option is needed here. https://prnt.sc/26ncbsm  Instead, move it to the Style> product thumbnail tab. Adjusted as follows : https://prnt.sc/26ncdan
4- This widget does not really need the content section in the Style tab. https://prnt.sc/26nce5z    Because it is better to be able to control each section, for example, the price or title of the product separately. Like the product grid widget
5-  In the title section, there is no alignment option. https://prnt.sc/26ncffv
6- Also in the price section, there is no alignment option.
7- Also, the rating section does not have alignment option. https://prnt.sc/26ncjko
8- Please add margin option to products list.

**BUG**

This widget is not full width by default. It is a distance from the left. https://prnt.sc/26ncm9t

**Add an example of where this feature is already implemented. **

It would be great if we could create something like this using this widget : 

![Screenshot_20220202-133905_Digikala](https://user-images.githubusercontent.com/77163248/152137976-ebc7a589-22e1-4563-b782-6533e763a366.jpg)

It will definitely be possible by developing the above.

thank you❤

**Comment by UraraReika** [comment]
1 - This widget doesn’t has any hover effects do this option is pointless.
2, 5, 6, 7 - done.
3 - This option in this case more about layout so it will stay here.
4 - Due to widgets wrapper this style section is useful.
8 - Widget has space between option.

> This widget is not full width by default. It is a distance from the left. https://prnt.sc/26ncm9t

We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please contact our support team. 

> It would be great if we could create something like this using this widget

This widget has some limitations but still you can create something like this. You better use Archive item template or Listing grid from JetEngine to make this view.

Thank you!

**Comment by 79ho3ein** [comment]
thank you @UraraReika
