### ISSUE TITLE
JetWoo is not compatible with 3rd-party product badges plugins. 

### ISSUE THREAD

**Issue by mdesignweb** [CrocoBlock/suggestions#4802]
Jet Woo is not compatible with most 3rd-party Woocommerce plugins. 
The problem is that templates built with JetWoo are missing native WooCommerce hooks and every plugin for Woo is using those hooks. 

I am aware of DevTool for custom badges, but that simply is not enough. We need to go on every product to select the badge. What if someone has a store with 1000 products? I'm currently working on such a store, and we need bulk settings. 
 
Example plugin https://yithemes.com/themes/plugins/yith-woocommerce-badge-management/ - it has free version

Custom code is not working either, because Woocommerce hooks not work. 

I suggest creating some kind of plugin where we can add a helper class to connect your hooks with Woocommerce hooks. I'm not an experienced developer, but this should be possible. 

Please let me know if you need an extra explanation.

**Comment by UraraReika** [comment]
Hello @mdesignweb !

You can contact our support team so they will help you with solution.

**Comment by mdesignweb** [comment]
They told me to submit it here. And how do you solve this? @UraraReika 
If you refer to this https://github.com/UraraReika/jet-woo-builder-custom-product-badges this is not a solution because this is so not user friendly, and doesn't have some basic options like most of the Badges plugins.

**Comment by UraraReika** [comment]
Hello @mdesignweb !

In one of the latest JetWooBuilder release new WooCommerce Action widget was presented https://tppr.me/Vk25h. Basically you can use it whenever you want but for now only Products Loop And Single Products hooks exist https://tppr.me/Rkv09. So it is better to use when you create Archive Item Template or Single Product Template with the help of JetWooBuilder or Product Listing Item with the help of JetEngine. This list will be increased in the future, don't worry about that.

If we taking about widgets such as Products Grid or Products List in this case you always can rewrite some templates inside your child theme and put there whatever you want. 

Although for some our functionalities we use custom methods with specific markup that can replace default WooCommerce functionalities and in this case some hooks will not be included but we have our own hooks that you can use instead.

For example like in this situation with https://yithemes.com/themes/plugins/yith-woocommerce-badge-management/ plugin. It uses this hooks https://tppr.me/nCK2d to implements budges functionalities in all possible variations. But if with Single product there is no problem https://tppr.me/YTdsa and with dynamic tags from JetEngine https://tppr.me/XSMB5, there is some problems here https://tppr.me/cJtfl. Instead of this hook you can use this code in your child theme: 

`add_filter( 'jet-woo-builder/template-functions/product-thumbnail', [ yith_wcbm_frontend(), 'show_badge_on_product'], 999, 1 );`

This code will solve the problem for all loop widgets.

**Comment by UraraReika** [comment]
We haven’t heard from you in a while so I’m going to go ahead and mark this thread as resolved. If you still need help with this issue or have any other questions about our product, please start a new thread.
