### ISSUE TITLE
Ability to disable WooCommerce icons in jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5005]
one option for removing these symbols is great. https://prnt.sc/qrOnuqxxlO7-
Like most users of this plugin, I'm not a coder. So I really need this option. This symbol is in the form of a checkout page coupon.

**Comment by UraraReika** [comment]
Hello. Thanks for the feedback.

Unfortunately we do not plan to introduce such functionality into our plugin since we can't control every aspect of WooCommerce with our plugins. But some of ours widgets have this functionalities. Although in the future we do not exclude the possibility of adding this functionality to the some sort of custom add-on. For now you just can use simple CSS to globally disable this icons:

```
.woocommerce-error::before,
.woocommerce-info::before,
.woocommerce-message::before {
	content: none;
}
```

Thank you for your understanding.
