### ISSUE TITLE
JetEngine - Profile Builder bugs

### ISSUE THREAD

**Issue by edgBlw** [CrocoBlock/suggestions#5079]
I figured to little bug inside the profile builder system:

1. If you set templates that you connecteded to profile pages to canvas mode, it doesnt work. Heade rand footer on the live result still are visible.

2. 404 Errors aren't properly displayed. If you typing in an endpoint that doesnt exist, you don't get a 404 page but just an empty page.
Please fix these two things very soon.

Sincerely :)

**Comment by MjHead** [comment]
1. You can't set Canvas mode only for specific template. For the Content template mode - template of specific profile page rendered inside main page, wich selected as Account or User base page. For the Rewrite template mode - template rendered inside custom template which oriented on base page layout anyway. We can't change this behaviour, because all currently set up profile page will be broken. If you need to hide header and footer only for specific profile pages you can use Is Profile Page visibility condition and hide header and footer content for selected pages
2. We fixed this with redirecting all incorrent pages to main profile page. Will be added with 2.11.9 update
