### ISSUE TITLE
Custom icon for variable selection section in jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5101]
The ability to insert custom icons to select variables is really great as well as essential. https://prnt.sc/hOYFTu9KgAWg
Of course, 2 icons are needed. Icon before and after opening the list.
Similar to the elementor accordion widget : https://prnt.sc/xdYKMDFuRgQ9

**Comment by 79ho3ein** [comment]
+1

**Comment by UraraReika** [comment]
Hello and thanks for the feedback.

Unfortunately, we do not plan to introduce such functionality into our plugin because there is no original functionality for picking icons for this widget. Now our team is working on more priority tasks. But we've checked your request. Such a goal can be reached using a custom solution only. I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/.

Thank you for your understanding.
