### ISSUE TITLE
JetBlocks: link change in breadcrumbs

### ISSUE THREAD

**Issue by artikus11** [Crocoblock/suggestions#527]
Add the ability to change the link to the main page in the breadcrumbs widget

This is necessary so that you can change to an arbitrary name the link to the main one in the breadcrumbs widget. Otherwise, if the main page has a name other than "Home", the page title is displayed. This is terribly inconvenient if the main title is completely different.

Screenshot of what happens

![image](https://user-images.githubusercontent.com/16116688/64860765-24c9cf00-d63f-11e9-8d68-0f4c6785b38c.png)
The main page has an arbitrary title.

Yoast plugin implementation example
![image](https://user-images.githubusercontent.com/16116688/64860873-8722cf80-d63f-11e9-9aaa-bc83ad52abb8.png)

Moreover, in the Yoast plugin it is possible to add an icon or a picture instead of an inscription

**Comment by realstephenzhao** [comment]
Err, My suggestion about breadcrumb widget was ignored. @Floydtm 
[JetBlocks - Add option to customize breadcrumb link text in breadcrumb widget #463](https://github.com/Crocoblock/suggestions/issues/463)

While, you can still hack the breadcrumb content by CSS if you don't want to use Yoast SEO or other similar plugins like me.
See my suggest link above, but I don't suggest to manipulate content using CSS. Because it's not suit for it and you will find you can't select the added texts using your mouse.

**Comment by kaskad88** [comment]
Added to the next version
