### ISSUE TITLE
How can i achive this layout in JetWooBuilder Products Grid Carousel?

### ISSUE THREAD

**Issue by petrovui** [CrocoBlock/suggestions#5319]
Default view / Autoplay - off / Loop - off / Free mode - off / Centered Slides - ON
![products-grid](https://user-images.githubusercontent.com/29761044/167297033-7a379442-aa56-4a89-9163-5937549cdd56.png)

I want this simple view:
![carousel](https://user-images.githubusercontent.com/29761044/167296804-f0ca1cad-558a-451c-944b-d63b4e52d6ac.png)

and i want to control width of centered slide. by default in mobile view if 2 columns is set and centered mode is on the width of centered slide will be 50%, but it's too short. it must be 75% or more.
![products-grid2](https://user-images.githubusercontent.com/29761044/167297476-0523128e-98ee-4b2d-9ea0-95a2569d297e.png)

**Comment by 79ho3ein** [comment]
That's right, I don't think the center mode feature works properly. In fact, the center mode creates an [empty space](https://prnt.sc/VTo9HTe7sSX9) that completely corrupts the ui. I have never seen a website that has used such a carousel.

I think [this](https://prnt.sc/o2TG9sFmeIZg) is a good example of a central mode feature. Therefore, the function of the center mode option should be such that with the help of the overflow option, we can create [such a thing](https://prnt.sc/o2TG9sFmeIZg).
So, if we want to have such a beautiful carousel, it is enough to activate the overflow first, then activate the center mode option so that everything is displayed correctly. The important point here is that the center mode alone has no application, but must be an overflow subset. When we enable the overflow, the center mode option is displayed. I think this is the best way.

**Comment by petrovui** [comment]
The problem is that in Products Grid swiper.j is used. In Advanced Carousel slick,js is used. But the feature we spoke of called 'stage padding' and owl carousel got it (https://owlcarousel2.github.io/OwlCarousel2/demos/stagepadding.html).
The true problem is, that SWIPER.JS which is used in Products Grid widget got decimal slidesPerView e.g slidesPerView: 2.5. But in the widget carousel items cannot be set to 2.5, or 1.2 etc. It only can be set to 1/2/3/4 etc.

**Comment by petrovui** [comment]
https://www.figma.com/file/BoKig8oGLucGciWOmswjIh/Carousel-(Community)?node-id=101%3A83

**Comment by mehdimoradi1500** [comment]
+1

**Comment by UraraReika** [comment]
> The true problem is, that SWIPER.JS which is used in Products Grid widget got decimal slidesPerView e.g slidesPerView: 2.5. But in the widget carousel items cannot be set to 2.5, or 1.2 etc. It only can be set to 1/2/3/4 etc.

You can use option https://tppr.me/iH7jv to make this.

**Comment by petrovui** [comment]
> > The true problem is, that SWIPER.JS which is used in Products Grid widget got decimal slidesPerView e.g slidesPerView: 2.5. But in the widget carousel items cannot be set to 2.5, or 1.2 etc. It only can be set to 1/2/3/4 etc.
> 
> You can use option https://tppr.me/iH7jv to make this.

https://user-images.githubusercontent.com/29761044/167377571-b82f137b-7fd8-44f3-b12c-a274157f9924.mp4

Centered mode creates an empty space at the start and at the end of "stage" (swiper wrapper) if the "loop" is OFF.
Slide Overflow works great but it overflows only on the right side of swiper wrapper. And swiper wrapper becomes not really centered. It makes wrapper align to start. It s not right thing. It must looks like this (like centered):

![screeen](https://user-images.githubusercontent.com/29761044/167378304-971ad230-b587-4ed2-b8a6-f20d02222d4e.png)

Look at this CodePen. I've tried to recreate right view:
https://codepen.io/p3tr0ff/pen/NWyxzzR

**Comment by UraraReika** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.  For now this is not built in to library functionality that is why we avoid to use some custom code.But in the future we do not exclude the possibility of adding this functionality.
