### ISSUE TITLE
[JetWooBuilder] Show Visual Feedback when an item has been added to cart

### ISSUE THREAD

**Issue by antoinelbch** [CrocoBlock/suggestions#5363]
Currently, when using AJAX Add to Cart instead of page reload on the product single page, there is no visual feedback an item has been added to the cart.

Please **add visual feedback when an item has been added to the cart**.

Visual feedback can be:

- **Checkmark** on Add-to-cart-button
- Show **View cart button** once item has been added to the cart

Once an item has been added, the JetWooBuilder returns to the same state as before adding the item.

- Visitor does not know if item has been added
- Visitor might therefore try and add the item again (and again, and again...)

In the image below you can also see how another well-known plugin handles this:
![jetwoobulder-add-to-cart-visual-feedback](https://user-images.githubusercontent.com/1252145/168757526-3e7c4408-f391-41c0-8528-277ab491ec65.jpg)

- Shows loading animation
- Shows checkmark on Add To Cart button
- Shows View Cart button

**Comment by 79ho3ein** [comment]
+1
I think [this](https://prnt.sc/XUSZfTjSVXHu) is the best option. If this feature is to be added, we'd better be able to disable or disable [this option](https://prnt.sc/vOmG_SY9BzsT) (optional). In fact, it is better to display only one tick icon in the add to cart button. This is great visual feedback.
The reason we can disable the view cart option is that some websites use the elementor menu cart widget. In this widget, we can set the menucart to open [automatically](https://prnt.sc/z2Q5k3pb7yIx) after the product is added to the cart. In this case, [this option](https://prnt.sc/nIBFVGrA1He4) will not be needed and just showing a tick in the add to cart button is enough.

#5228

**Comment by tizum** [comment]
Guys, I've been trying to customize this situation for two days, please add the loading functionality by clicking the add button, thanks

I found that after the click activates a .single_add_to_cart_button.button.alt.loading class, I already tried to add the effect with css and font awesome, but I can't, because it applies to the entire button, the most I could do was use a gif as a background , but it was too ugly.

I would like an svg option to be added to choose awesome font icon or also customize, choose the alignment if it is left or right, in my case I would not like the view cart option to be shown

**Comment by 79ho3ein** [comment]
hi @tizum 
If you want to add a custom icon to the Add to Cart button, download [this plugin](https://prnt.sc/IFqhitVZVHUp) at [this link](https://crocoblock.com/freemium/tools/) to add this feature to jet woobuilder.
Anyway, I hope this feature will be officially added to the jet woobuilder core so that all users can use this feature. Many users are not aware of it at all.

**Comment by tizum** [comment]
@79ho3ein Hello, I tried this plugin, however it adds the icon only, in my case I want the icon to appear only when the user adds a product to the cart, thanks anyway :)

**Comment by zahnd** [comment]
+1
