### ISSUE TITLE
Automatically align for to add to cart buttons / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5364]
In the product grid widget, if the items in this widget are not equal, the Add to Cart button in the product grid widget will not be aligned, and this will severely damage ux. So, please add the Automatically align feature for the buttons to add to cart product grid widget. This feature has been added in version elementor pro 3.7 and works great. https://prnt.sc/NDF88Znr4OFY

**Comment by UraraReika** [comment]
Hello @Michaelgimii thanks for the feedback.

Unfortunately due to our specific markup and custom presets there is no possible to add such an option. So you will not see it in the core of our plugin. But you can defiantly do it by rewrite our template like this for example https://monosnap.com/file/aFMGW4Drtf2y7f6pxyQ9GiIXDxOKsJ enable this option https://monosnap.com/file/WuT2kFLzThlkPl2njXYBMrDsFCQDfG and add one line of css:
```
selector .jet-woo-products__inner-box {
    justify-content: space-between;
}
```

Thank you for your understanding.
