### ISSUE TITLE
Twilio Integration (Appointments & Booking)

### ISSUE THREAD

**Issue by JacobWonder** [CrocoBlock/suggestions#5478]
**Before adding a new feature request, please, make sure you’ve checked:**

- if the feature is already added to the backlog or in work;
- if the feature is missing from the products.

**Please, describe the feature request, making it clear to understand.**

Specify the feature, the product to which it should be added, and why it is important to add it. 
Describe what effect or functionality you want to achieve as a result.

**Add an example of where this feature is already implemented. **

Provide a detailed explanation of where this feature should be used, and if there are any alternatives already. 

Feel free to add any videos, links, screenshots to illustrate the requested feature.

Please, note, that the feature requests can be accepted and processed only if they’re written in English.

**Comment by UraraReika** [comment]
We already had this functionality since iCal option, but in the lates release we made this even better please check out our articles about it:
- https://crocoblock.com/knowledge-base/articles/jetbooking-how-to-transfer-bookings-from-google-calendar-via-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-reverse-booking-and-google-calendar-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-two-way-booking-and-google-calendar-ical-synchnization/

Please take a note that you can make such integration with every service that provide iCal functionality.
