### ISSUE TITLE
Custom icon for spinner in add to cart button in jet woobuilder plugin

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5610]
In the jet woobuilder plugin, if the user clicks on the plugin's add to cart button, a spinner will be displayed, after which the product will be added to the cart.
So it would be great if you could add the ability to change the spinner icon to the add to cart button. This feature is already available in elementor https://prnt.sc/4yqjqUb8CsT1

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

Unfortunately, we do not plan to introduce such functionality into our plugin. But you can solve this issue with simple css.

**Example 1**
If you want yo use SVG icons. First of all you need to use this [tool](https://yoksel.github.io/url-encoder/) to transform your SVG icon markup into background image like [this](https://tppr.me/axdKl). You will need Ready for CSS field. Next step is to reset some default styes and add new one instead:

Here we disable standard WooCommerce icons and add some additional styles for SVG background image.

```
selector a.button.loading::after,
selector a.button.added::after {
    content: '';
    display: inline-block;
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
    width: 1em;
    height: 1em;
}
```

Here you need to put your SVG icon background images.

```
selector a.button.loading::after {
    // bg-image of loading icon goes here
}

selector a.button.added::after {
    // bg-image of added icon goes here
}
```

**Example 2**
If you want to use another WooCommerce icon, you can find whole list of this icons [here](https://rawgit.com/woothemes/woocommerce-icons/master/demo.html). In this case you need just pick the icon you like copy their value code and paste it like this:

```
selector a.button.loading::after {
    content: '\e031';
}

selector a.button.added::after {
    content: '\e001';
}
```

**Example 3**
If you want to use font awesome icons.

```
selector a.button.loading::after,
selector a.button.added::after {
    font-family: 'Font Awesome 5 Free'
}

selector a.button.loading::after {
    content: '\f185';
}

selector a.button.added::after {
    content: '\f186';
}
```

P.S. This css was written as custom CSS in additional tab of Elementor editor widget for Products Grid widget but you can fell free to use it where you want. And in case you write it in you child theme or customizer or with some third party plugin remember to remove `selector` selector because this is specific Elementor editor wrapper and replace it with some additional one for your purpose.
