### ISSUE TITLE
Load More Addon for Products Loop

### ISSUE THREAD

**Issue by jimhuds** [CrocoBlock/suggestions#5671]
It would be great if the Products Grid Load More Addon also worked for the products loop, so that I can use it with a custom layout as it is in the Zolden template.

Cheers!

**Comment by Floydtm** [comment]
At the moment, we do not plan to introduce such functionality into our plugin.
Now our team is working on more priority tasks.
But in the future we do not exclude the possibility of adding this functionality to the core of our plugin

**Comment by rtpHarry** [comment]
This is a feature that is required on my current project as well. 

Using a Product Grid is limited because you cannot use custom templates for each item, just ten presets.

Using a 3rd party plugin like Catch Infinite Scroll "works" to provide the infinite scroll, but then when more products are loading in the javascript for those new products don't work, such as a JetPopup trigger to show a quickview style product preview.

I reached out to support and their suggestion was to make changes the core JetPopup plugin code which would be a maintenance nightmare.

So now im faced with saying they can either have their desired layout and a quickview option, or they can have a preset layout and quickview styles, and no infinite scroll :/
