### ISSUE TITLE
Global settings for jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5709]
hello crocoblock team

I use 12 product carousels (product grid) on my website. Every time I decide to edit the style in them, I have to do it for each one. Even for some I forget to do. So this is a big challenge for me and many users.
So it's great if you add a new feature, that we style the product grid or list widget once, and then connect it to all the product grid widgets on the website. If we make a change in the style of one of the widgets, the style of all product grid widgets will change accordingly, and this will greatly increase our work speed.

**Comment by 79ho3ein** [comment]
+1

**Comment by rtpHarry** [comment]
Yeah its a shame that the global widgets feature of Elementor doesn't work like this. It's only useful if you want the exact same copy of the widget site wide. 

You can't even use it as a blueprint and just detach it from the global widgets because that just disconnects all of them. 

Would be good if some solution could be found.

**Comment by UraraReika** [comment]
Hello @Michaelgimii, thanks for the feedback.

In this kind of situations you can use Elementor Global widgets functionality. The only problem you will have in this case is query. But unfortunately we do not plan to introduce such functionality into our plugin. Maybe in the future we do not exclude the possibility of adding this functionality to some sort of add-on.

Thank you for your understanding.
