### ISSUE TITLE
In jet woobuilder plugin, the best sellers query does not work

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#5750]
**Describe the bug**
I use jet woobuilder plugin to display best sellers products. But this query is not working properly. In fact, when I select this query, it displays products that have never been sold.
Crocoblock team, please is there a quick fix to fix this problem? I have only 20 days to deliver project to the client. I am really worried about this. Is there a solution?

**To Reproduce**
1- Add the product grid widget and select the best sellers query.
2- Products are displayed that have never been sold.

I even registered a trial purchase of a product with 8 guest accounts, but the product never showed up on the bestseller list.

**Comment by Michaelgimii** [comment]
I still have this problem. Please fix it in the next version. This is a basic requirement for an online store.

**Comment by UraraReika** [comment]
This issue was discussed few times. Basically the simplest way that WooCommerce uses in their shortcode is to display necessary amount of product in the page with the and order it by `total_sales` with `DESC` order.

In JetWooBuilder using Products Grid widget you can acheave this with this settings https://tppr.me/7f3LL. Here you can see we set 20 products per page although show all products and order them by salles. As I said erlear this works the same as `[ best_selling_products ]` shortcode from WooCommerce.

But if you want to display only products that has ever been sell then you can use `Bestsellers` query. And in this case we use `total_sales` product meta and compare if it more than 0 sales.

We have checked your request and everything seems to be working correctly. For example on my locall instalation I go to WooCommerce > Reports switch to Sales by products tab and select year https://tppr.me/jiaX0. Here I can see list of products that have sales and sales amount. If I setup query like this https://tppr.me/U0X50 then I can see all this products. And only this products https://tppr.me/R70H2.

You can check previous issues about this topic https://github.com/Crocoblock/suggestions/issues/5158 and https://github.com/Crocoblock/suggestions/issues/4473!

If you have some additional question then please contact our support team.

Contact Support Link
https://support.crocoblock.com/support/home/ 

Thank you!
