### ISSUE TITLE
Custom Quantity Selectors plugin for jet woobuilder - DevTools

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#5848]
**in Cart Table widget**

1- [This control](https://prnt.sc/IWGuZE7eRy1j) is for icon size. But only the size is mentioned in the title.

2- A new control to create space between buttons and input fields : https://prnt.sc/PC-xKdDOGCus

3- Ability to control border, border radius and box shadow separately for the +- button. There is a similar feature in the product grid widget and using it we can customize the left and right box arrows [(separately)](https://prnt.sc/VbkIXMf1hW_E). Using this feature we can design something [like this](https://prnt.sc/YsD8Ft5Ji4nn) and so there will be no restrictions.

4- [Absolute width and height](https://prnt.sc/NlLr8p_DNThg) for the +- buttons.

5- disabled mode for +- button : https://prnt.sc/yatfpq8OoHdA

6- On mobile, the title is not centered vertically : https://prnt.sc/I-lDt4MSI9oH (This applies to all titles in this widget)

**in Single Add to Cart**

1- The +- and input buttons are located slightly above the add to cart button : https://prnt.sc/OVCGJb4y5BBK
By changing the amount of [padding](https://prnt.sc/QXBDwRFMT0a-) in the add to cart button, this issue will be more noticeable.
To solve this, a new control for the vertical alignment of the +- button and the input field would be great. (to align with the Add to Cart button.)

**Other items are similar to those listed above.**

**BUG**

1- After reloading the page, the +- buttons appear very late. (Both in the cart table widget and in the add to cart widget)

https://user-images.githubusercontent.com/77163248/187699381-f260fe18-420b-43d4-902e-259d2144491f.mp4

thank you!

**Comment by 79ho3ein** [comment]
**A question about the jet woobuilder development process**

crocoblock support said we probably don't add jet woobuilder (**Custom Quantity Selectors**, **Custom Products Badges** **Products Grid Load More** and **Custom Add to Cart Icon**) plugins to core because it slows down the websites.
So I wanted to ask if it is not better to add these features as a module to the jet woobuilder core? Therefore, users can activate and use any of the required features if they wish. Just like the modules that the jet engine has with it.
Of course, Custom Add to Cart Icon, Custom Quantity Selectors and Products Grid Load More are the main and required features of jet woobuilder And definitely all users will need them.These are all very important features. But features like Products Grid Custom Fields and Custom Products Badges can be added as a module to jet woobuilder.

**Comment by fostira** [comment]
+1

**Comment by Joliamendi** [comment]
Are these important features like Custom Products Badges, Custom Quantity Selectors, Products Grid Load More, Custom Add to Cart Icon really not added in core because it can slow down? This doesn't really make sense.
All these are features that a professional plugin like jet woobuilder can benefit from. Most importantly, users need to install 5 plugins to have these important features in jet woobuilder. This is really painful. I hope the big crocoblock team will abandon this decision. These plugins make sense for jet engine, but not really for jet woobuilder. 
I also hope to know dear @UraraReika opinion about it. thank you in advance

**Comment by UraraReika** [comment]
Hello and thanks for the feedback.

1, 2, 3 - done
4, 5 - we do not plan to introduce such functionality into our plugin, this changes could not work proper in this layouts.
6 - this is normal behaviour for this situation

Positioning in Single Add to Cart widget fixed.

If we are talking about rendering buttons in single and cart page then this is not a bug, this is how this functionality works in this pages because on this pages it renders with the help of JS.

Thank you for your understanding.

**Comment by UraraReika** [comment]
Unfortunately i can't give you and answer right now about adding this addons straight in to the core of our plug in but in the future we do not exclude the possibility.
