### ISSUE TITLE
The current query option in the product grid widget / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#5861]
For a better user interface, wouldn't it be better to [remove this](https://prnt.sc/BIUawQ5t_wa-) from here and add it [here](https://prnt.sc/0dprz7w8A6vJ)?
If this is possible, that would be great. Because we can have more control over archive products. For example, I want to use [this option](https://prnt.sc/Ef-dJK6e-iVf) in product archives.

**tip :** If we enable the current query option in the new section, other queries (other than [this one](https://prnt.sc/YfVa4J-_9wLW) in the future version) will be disabled or hidden.
Overall, I think it would be great in every way if the current query was moved to [this section](https://prnt.sc/0dprz7w8A6vJ).

Here's what's great : https://prnt.sc/862vbKiLIIfF
If we select current query, other queries will be disabled except these two : https://prnt.sc/AiSwE-rdcepm

**Comment by UraraReika** [comment]
Hello @Michaelgimii !

Thanks for the feedback. Unfortunately we do not plan to introduce such functionality into our plugin. The reason of this is backwards compatibility and logic behind this control and functionality that it contains.

The reason why query controls disappear not just because we want so, but because after enabling this control widget grab global wc query that you can control in customizer section https://tppr.me/ide6D. And none of the query control can't make any difference on this query and just skipped. This query type although can't work with any other type of query.

Thank you!
