### ISSUE TITLE
Allow bookings when a booking is pendingure request

### ISSUE THREAD

**Issue by tvalades** [CrocoBlock/suggestions#5951]
Hello. I would like that when a reservation is made and it has not yet been confirmed by the administrator, the dates in the calendar that is shown in the front part are not blocked. That they might have an orange color as requests have been made but still continue to allow reservations until finally the administrator confirms one of them and the dates are blocked. On the other hand, it would be nice if the new reservation part from the panel allowed us to add more information, such as the person we booked for and the additional services that they would choose (additional services that are shown in the form on the front part)

**Comment by UraraReika** [comment]
Hello @tvalades ! Thanks for the feedback.

For the time been our plugin have no notification system and in this case we can provide unblocked pending dates. Because in this case the person who booked second will not informed that this dates were took by some other person after admin approve the first booking. So we will keep it as it is for now. As for your second request you need to create additional db fields for info that you need to store then this fields will be displayed if admin add booking form.

Thank you!
