### ISSUE TITLE
ATTENTION CROCOBLOCK!!! Important

### ISSUE THREAD

**Issue by oncps** [CrocoBlock/suggestions#6093]
ATTENTION CROCOBLOCK!!! I would like to vent here, speak some constructive criticism.. At first, crocoblock is a great plugin, no doubt... But we web developers who use crocoblock plugins miss some features on a daily basis.... There on github, I see so many suggestions that the user asks to add features, let's say 97%, are great suggestions, but often crocoblock doesn't even care about it, or when it does, it takes months to add some functionality that came from user suggestions. I understand that, on the other hand, crocoblock has expenses with code developers to add to the plugin, but see how interesting, it seems like a chain reaction, croboblock has its expenses to add new features, with that it conquers new buyers of this amazing tool "Crocblock plugins ".. "WHAT IS IT LEFT FOR CROCOBLOCK TO BE A PIONEER AND STAY IN FRONT OF OTHER PLUGINS???" THINK ABOUT IT...... I have put so many suggestions myself, on github "crocoblock suggestions" and "jetformbuilder suggestions" on github.... PLEASE TAKE A LOOK AT ALL USERS' SUGGESTIONS ON GITHUB AND ADD NEW FEATURES FOR CROCOBLOCK PLUGINS. Another important point too, they could have teachers from each (country), from each language, for other people to see the video and understand the explanation of the native language. For example, I'm from Brazil, they could hire a Brazilian Youtuber, to make explanatory videos of the crocoblock plugin features... Regarding the plugins/addons that you have on the crocoblock website in "DEV TOOLS", I don't know how it works (if it's third-party or not, but you could UNIFY all this, leaving it in one plugin! Unfortunately, even in WORDPRESS, the admin panel is slow when we install too many plugins!!! what do you think of unify? make me like jetengine, that we only enable what we want to use....it would be much better than having several plugins installed!!!! wouldn't it be better? remember, CROCOBLOCK HAS EVERYTHING TO GET ABOUT OTHER PLUGINS.

**Comment by MjHead** [comment]
1. Please avoid caps syntax in request title and description, really feels like you scream on us for some reason.
2. Thnks for the feedback.
3. Sorry, but I'm closing this issue because its not the feature request or bug report. I understnd your pain with timeframes of implementing some features, but we are trying to do our best - all team working all the time on implementing some features, fixing some bugs etc. This repository is not the only source of our incoming tasks. There is also support tickets, Facebook requests, our internal roadmap etc. But even so - there is 2964 already closed issues. I not mean we work fast ot slow - I just mean we continiusly working on these issues
