### ISSUE TITLE
Improved performance in woobuilder product grid widget

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6109]
**Please, describe the feature request, making it clear to understand.**

Hi

In the product grid widget, which is a large and important widget, most of the time changes are applied slowly. For example, when we determine the number of columns to display products in this widget, applying the number of columns takes about 3 seconds. Especially if there is a lot of content on the page, it can take up to 6 or 7 seconds. This slowness is present in other options such as the number of products, or even activation of the overflow, carousel and in general all the options in this widget.

The reason I decided to submit this request was because of the new version of Elementor Pro. In Elementor Pro Loop Builder, if we change the number of columns, it is applied immediately without any pause. This is really great.

https://user-images.githubusercontent.com/77163248/198911500-ff91c3e0-7e1b-486f-87ac-11833c477022.mp4

So it would be great if the performance speed in this widget options is improved. so that changes are applied immediately after clicking.

thank you.

**Comment by UraraReika** [comment]
Thanks for the feedback.

Unfortunately, we will not be able to accommodate your request. This type of widget rendering in the editor is due to the functionality of the carousel that is present in it. If we remove this type of rendering, everything will work faster in the editor, but if you have the carousel enabled, these changes will not be reflected in the editor until you reload the page. And this type of rendering cannot implement any specific option accordingly.

But if you're willing to sacrifice the visual appeal of your carousel in the editor, you can always use the corresponding ``jet-woo-builder/shortcodes/jet-woo-products/atts'` hook to control the widget options and remove the unwanted rendering type.

Thank you for your understanding.
