### ISSUE TITLE
Full compatibility of jet woobuilder with jet compare & wishlist.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6111]
**Please, describe the feature request, making it clear to understand.**

Hello

In the new version of jet woobuilder, everything works fine, but there is a major problem. The problem is that if the user deletes the product from the wishlist in the product grid widget, it is not deleted by Ajax and the page needs to be reloaded to completely delete the product. So it would be great if you add ajax wishlist removal to this widget. With the addition of this feature, everything will be perfect. thanks

**Comment by UraraReika** [comment]
Hello and thanks for the feedback.

Unfortunately, we are not going to implement this functionality in the plugin, as previously mentioned in other posts, this functionality is only added to display your current wishlist, without any interaction with it.

Thank you for your understanding.

**Comment by Joliamendi** [comment]
Hi @UraraReika 

In the last two versions, you added wishlist display support to the product grid widget. It was a great event. Because the product grid widget has a much better customization option than the native jet CW widget. But if we can't remove the products from the wishlist by Ajax in this widget, wouldn't this be an incomplete way?
It's actually like building a car, but without a steering wheel!
We can now[ remove products from the wishlist in the product grid widget, but it is not done by Ajax](https://prnt.sc/5X7E_W751FVf). The only thing missing is removing products from the wishlist using Ajax.

I request you to please think a little more about this matter, thanks🙏

**Comment by UraraReika** [comment]
> Hi @UraraReika
> 
> In the last two versions, you added wishlist display support to the product grid widget. It was a great event. Because the product grid widget has a much better customization option than the native jet CW widget. But if we can't remove the products from the wishlist by Ajax in this widget, wouldn't this be an incomplete way? It's actually like building a car, but without a steering wheel! We can now[ remove products from the wishlist in the product grid widget, but it is not done by Ajax](https://prnt.sc/5X7E_W751FVf). The only thing missing is removing products from the wishlist using Ajax.
> 
> I request you to please think a little more about this matter, thanks🙏

In such situation I highly recommend you to check our custom service - we take such complex cases, that cannot be implemented globally, and bring them to life https://crocoblock.com/customs/
