### ISSUE TITLE
Integration of JetBooking with MMK

### ISSUE THREAD

**Issue by LaxusCroco** [CrocoBlock/suggestions#6198]
JetBooking has iCal integration with Google Calendar. I would like to request the 2-way synchronization between JetBooking and MMK platform as well. That is, bookings from the JetBooking plugin should go to MMK, and bookings from MMK to JetBooking.

For your convenience, the MMK platform provides an API, which may be accessed via this URL.
https://app.swaggerhub.com/apis-docs/mmksystems/bm-api/2.0.2#/

**Comment by UraraReika** [comment]
We already had this functionality since iCal option, but in the lates release we made this even better please check out our articles about it:
- https://crocoblock.com/knowledge-base/articles/jetbooking-how-to-transfer-bookings-from-google-calendar-via-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-reverse-booking-and-google-calendar-ical-synchronization/
- https://crocoblock.com/knowledge-base/articles/how-to-set-two-way-booking-and-google-calendar-ical-synchnization/

Please take a note that you can make such integration with every service that provide iCal functionality.
