### ISSUE TITLE
Add password field to the checkout billing form of JetWooBuilder

### ISSUE THREAD

**Issue by andre-xavier-berger** [CrocoBlock/suggestions#6206]
There is a woocommerce option in settings / account that allow to define a password during checkout process.

Go to 
1) "Accounts and Privacy Settings" tab 
2) the last option of Account creation section 
"When creating an account, automatically generate an account password" 
![image](https://user-images.githubusercontent.com/78139211/204014616-ff5be5d5-3fe8-4481-be83-cd3fb22e4cd3.png)

Untick this option --> then woocommerce adds the password field in the checkout form.

However this field is not present in the checkout billing form widget of jetWooBuilder so, although it is present in the front end, It is not possible to style it or reorder the columns.

That would be good to integrate it in further updates of the plugin.
Thanks
Best regards

**Comment by UraraReika** [comment]
Hello @andre-xavier-berger! Thanks for the feedback.

Unfortunately, we will not be able to accommodate all of your requests for several reasons:
- First of all, these fields cannot be displayed until you are in editing mode, i.e. you are logged in to the site. In this case, a check in WooCommerce is used, which does not have a hook in order to somehow change the behavior. However, we have implemented alternative selectors and now you can style these fields.
- Secondly, we will also not be able to add customization options, as they are in a different group of fields, and also do not have all the necessary parameters for controlling the position and so on.

Therefore, in this case, everything will remain as it is, but now you will be able to style these fields.

Thank you for your understanding.
