### ISSUE TITLE
Typography option for the filter label of the active tags widget / jet smart filters.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6247]
Hi @SargasTM
In the Active Tags widget, there is no option for filter lable typography.
In this screenshot, you can see that the lable of the filters cannot be controlled : https://prnt.sc/zkdIwQBD0K28

**Please add the typography option for filter labels in active tags widget.** thanks

**Comment by nreljed** [comment]
there are two bugs your capture confirms it 😅
they have been notified since December 2021 and July 2022

[https://github.com/Crocoblock/suggestions/issues/5654](https://github.com/Crocoblock/suggestions/issues/5654)
[https://github.com/Crocoblock/suggestions/issues/4526](https://github.com/Crocoblock/suggestions/issues/4526)

**Comment by SargasTM** [comment]
done, will appear in the next version
