### ISSUE TITLE
Custom position for Categories Grid widget count (jet woobuilder)

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6347]
**Please, describe the feature request, making it clear to understand.**

For better UX, please add [custom position](https://prnt.sc/q_zxc5Z1Gj-X) attribute to Categories Grid widget [count](https://prnt.sc/htHaAUr_Vc-A) if possible. thanks

**Comment by Michaelgimii** [comment]
Hi @UraraReika Is it possible to add this feature to the next version?🙏

**Comment by UraraReika** [comment]
New custom position control was added, but only for vertical alignment, because horizontal - you can control with the help of margin, padding and alignment controls.

Although this controls will be only available for Preset 1, because only in this case we have all necessary default styles.

All this changes will be available in next 2.1.6 release
