### ISSUE TITLE
Add ajax add to cart option to add to cart widget in Jet Woobuilder plugin.

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6355]
**Please, describe the feature request, making it clear to understand.**

Hi team. First of all, thank you for this powerful plugin.

When I first installed the jet woobuilder plugin, when I created the single product page, I thought there was no ajax add to cart option. But then I found out that this option is available in WooCommerce settings > Jet Woobuider.

I wanted to say that it would be great if you put this option directly in the add to cart widget. The current position of this option is very far from reach. The image below is something that would be great.

![ajax](https://user-images.githubusercontent.com/103376243/211204728-f4614641-c67f-4dae-97ea-ab43df910204.png)

kind regards

**Comment by Michaelgimii** [comment]
+1

**Comment by morosmo** [comment]
+1

**Comment by UraraReika** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. The reason why this oprion not in the widget is because it made for all single product templates and single add to cart buttons. And it doesn’t metter if it is defoult template or build with elementor or some other builder. That is why this option in global settings.

Thank you for your understanding.
