### ISSUE TITLE
Thumbnail default link in product list widget (jet woobuilder)

### ISSUE THREAD

**Issue by Joliamendi** [CrocoBlock/suggestions#6356]
**Please, describe the feature request, making it clear to understand.**

When we add the product list widget, the product image does not have a link by default. Because Thumbnail link option is disabled by default.
I think it would be much better if Enable Thumbnail Permalink is enabled by default. Just like the product grid widget.

**Comment by UraraReika** [comment]
Hello @Joliamendi! Thanks for the feedback.

Originally Products List widget didn't has this option and it was added way lated and based on Products Grid widget. And unfortunately in this case we can't make this option on by default because it will damage backwards compatibility.

Thank you for your understanding.
