### ISSUE TITLE
Show jet woobuilder options in wp dashboard

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6390]
**Please, describe the feature request, making it clear to understand.**

Hello crocoblock team.

When we activate some of your plugins such as Jet Engine or Jet Smart Filters, related options will be added to the dashboard. This makes them much easier to access.

![jet](https://user-images.githubusercontent.com/88034902/212404622-6f5ce018-7114-408a-848c-2e388799f446.png)

I think it would be great if you add a similar option for jet woobuilder. This option will have 3 sub-sets in the WordPress dashboard.

- Templates (This option is now under the name of **woo page builder** under crocoblock in the WordPress dashboard)
- widgets 
- General Settings

That would be really great. je woobuilder should be a separate section in the WordPress dashboard. The fact that woo page builder is now located in the crocoblock subcategory of the WordPress dashboard is not really interesting.

**Comment by UraraReika** [comment]
Hello @Michaelgimii! Thanks for the feedback.

Unfortunately we will not add such option to JetWooBuilder plugin and keep it as it is. The reason why such plugins as you mentioned have this is because they have specific functionality and UI that better handle that way.

Thank you for your understanding.
