### ISSUE TITLE
Improved free mode behavior / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6396]
**Please, describe the feature request, making it clear to understand.**

Hi crocoblock team.

There is a free mode feature in the jet woobuilder plugin. But if we try this feature on mobile, it is not user friendly. The problem is that it scrolls unnaturally. Too fluent.
Please view [this website](https://swiperjs.com/demos) on mobile. At the beginning of the page, there is a carousel that has two rows and columns.
This carousel uses free mode and its navigation is very enjoyable. This is a standard example of free mode.

It would be really great if free mode in jet woobuilder works like this. free mode is really unique. I hope you improve it❤

**Comment by UraraReika** [comment]
Hello @Michaelgimii. Thanks for the feedback.

In our widget we use standard settings for this option as well with additional velocity option with used for minimum touchmove-velocity required to trigger free mode momentum.

I have tested your given example and what we have in our widget and didn't se much difference between their work. But strange behaviour can be caused due to different options enabled. Although our widget and layout are more complex and last but not least it that we use old version of Swiper library. We extend this library from Elementor plugin and for the time been it is not up to date. So it can cause extra problems.

Thank you for your understanding.

**Comment by Michaelgimii** [comment]
Hi @UraraReika 

It seems that Elementor plans to update the swiper library to the latest version in the next version (3.11.0). 

https://github.com/elementor/elementor/pull/20947

I hope we will see great new features in jet woobuiidler carousel after that.
