### ISSUE TITLE
Better display of Pagination and Navigation customization options / jet woobuilder

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6431]
**Please, describe the feature request, making it clear to understand.**

Hello

In the product grid widget style settings, the Pagination and Navigation section is as follows : https://prnt.sc/Gnls6Z28gAGU

Therefore, the customization options are displayed as a pop-up in normal and disabled hover mode. But it would be great if you could remove the Pagination and Navigation customization options from the popup and display them directly. In this case, it will be very easy to access them. Just switch between normal and disabled hover mode to instantly access customization settings.

Exactly like the image below. [This option](https://prnt.sc/tV7NZps8u03-) will no longer need to be displayed.

![jet w](https://user-images.githubusercontent.com/88034902/214506569-b524bf92-03e6-4c8f-9d32-ea69ed046dc8.jpg)

**Comment by UraraReika** [comment]
Hello @Michaelgimii!

This is specific Elementor control which we created for box styles and use in specific places. And in this case we can't just simply remove it and replace as you suggest because it will damage backwards compatibility. So for the time being it will stay as it is.

Thank you for your understanding.
