### ISSUE TITLE
[JetSmartFilters & Bricks] - Support Global CSS Classes

### ISSUE THREAD

**Issue by hb81010** [CrocoBlock/suggestions#6441]
It would be great if the individual filter elements would support the global CSS classes of Bricks. This way you could create, style & assign a separate class for each filter element and have a consistent look throughout without having to edit every single element.

Here is an example with the Range filter. Unfortunately the settings I made in the SmartFilter Setting (Slider, Inputs, Label, Grouped Filters) are not saved in the class I created.

![grafik](https://user-images.githubusercontent.com/54399588/215157685-0dde3a9a-224d-4db4-a7ae-6c5ce0a6a133.png)

**Comment by RagnarLodbrok94** [comment]
Hi.

I tried to do it myself and everything worked out for me. Now I can add this class to another element and it accepts these styles.

I tried to apply this for range filter and select filter. And here is the result.
https://prnt.sc/dDFJhmgL0zte
https://prnt.sc/GFOE1MsTpxOz

Watch a video tutorial on how to correctly use global classes in Bricks.

The only point that should be taken into account, when before adding a class to the element, styles were already set through controls (including default ones), then they must be reset first.
Because these styles will be more specific, they are added via the element id.
https://prnt.sc/JTdWCVN0fNDQ
