### ISSUE TITLE
three things about pagination in the product grid widget - jet woobuilder.

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6469]
**Describe the bug**

Hi

There are three issues in the pagination section of the Product grid widget that appear to be bugs.

1- In the pagination position settings, if we set left or right to 0, the pagination will still remain in the center. While it should be moved to the right or left : https://prnt.sc/Wa97NfAMECeK
While if we set the top or bottom position to 0, the pagination will be placed in its correct place : https://prnt.sc/gHqpMYc6MRAD

2- In the pagination settings, there are [two options](https://prnt.sc/tu69JouwqRJb) that seem to have no use. These two options are useful in navigation settings, but they have no use in paginations. So isn't it better to remove these two options from the pagination settings?

3- In the pagination and navigation settings, the Border Type option does not have the default value : https://prnt.sc/Vk9eeG_7rB2G
Rather, **None** is displayed as the default.

thank you

**Comment by UraraReika** [comment]
1. In case with horizontal pagination container has full width style and indent options effect this container. So if you use indent options you should do it in combination with Alignment option. For example: https://tppr.me/JQ7pa -> https://tppr.me/upTgV

2. This is custom made control for such types of containers and this control has native logic to hide some elements but unfortunately in case of backwards compatibility we will keep it as it is because someone can use it for custom purpose.

3. When creating widgets and controls, we prefer not to add predefined values and styles to make our widgets easier to integrate with different themes and plugins. And also in this case it will harm the backward compatibility.
