### ISSUE TITLE
simple bug in Checkout Order Review widget / jet woobuilder.

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6568]
Hi

When the checkout page is updated via Ajax, the Checkout Order Review widget will flicker for a moment. The reason for this problem is that the shipping cost section is added for a moment and then hidden.

In the video below, notice the border above Subtotal. When the page refreshes, the border changes to 2px and then returns to its original state. This makes users feel uncomfortable.

https://user-images.githubusercontent.com/88034902/221403736-14b745e5-2c09-43ae-ab0b-6c5efc9d51dc.mp4

It should be noted that I checked this bug in other plugins and templates and this problem only exists in jet woobuilder.

**Comment by UraraReika** [comment]
Such issue happens because of specific style that take place in our plugin. And this issue occurs only while ajax request is going because in this moments some additional wrappers added `border-collapse: collapse;`. Due to the fact that it is desirable not to add these elements directly to the table, the current problem arises. You can override these styles with plain CSS:
.woocommerce-checkout form .elementor-jet-checkout-order-review #order_review .shop_table {
    border-collapse: separate;
}
