### ISSUE TITLE
[Bricks Builder] Data Store's counter not working for CCT

### ISSUE THREAD

**Issue by sekhsoyebali** [CrocoBlock/suggestions#6587]
**Describe the bug**
Data store's counter is not showing for CCT Listing in Bricks Builder
Enabled: Is Custom Content Type store.

**Video**
https://user-images.githubusercontent.com/68687765/222806120-341ddb2a-4f6f-4b8b-8629-80c79f8b7925.mov

**Desktop (please complete the following information):**
OS: [macOS]
Browser [chrome]
Version [110.0.5481.100]

**Comment by MjHead** [comment]
You using default Bricks Dynamic Data to display JetEngine store count. It may occasionally work, in cases when  storage type is really exists under used meta key. But in most cases it shouldn't - for example when you using CCTs this count stored in CCT itself and can't be retrieved from 'cf_{field_name}' dynamic tag. This problem will be resolved when we'll register own Dynamic Tags for Bricks which are intended to retrieve JetEngine-specific data. At the moment I can't give ETA on this, because Bricks dynamic tags to different from Elementor in UI/UX part (unfortunately not into the better side), so we need to resolve couple of issues related to moving additional settings of our Dynamic Tags
