### ISSUE TITLE
JetSmartFilter makes Elemntor crash every time I try to edit a page

### ISSUE THREAD

**Issue by Picrold** [CrocoBlock/suggestions#6693]
Hello Crocoblock Team,

JetSmartFilter makes Elemntor crash every time I try to edit a page; once I delete the JetSmartFilter plugin, Elementor starts working; I installed JetSmartFilter again it causes the same issue keeps Elementor crashing, and I can't edit a page.

![Screenshot 2023-04-04 153614](https://user-images.githubusercontent.com/117189621/229901623-f6e50c0c-3cc0-47dc-b8e6-9fb1295becdf.png)

Please help

Many thanks,

Picrold Canada
picrold.ca

**Comment by Floydtm** [comment]
Contact our support team so we can investigate and resolve this issue.

**Comment by Picrold** [comment]
Hello,

They can't do anything the Support team. I reverted to version 3.0.4 it's working; this issue with 3.1.0

![Screenshot 2023-04-09 13334411](https://user-images.githubusercontent.com/117189621/230787628-10092741-a52e-4d4f-8d31-a76d5cb92335.png)

![image](https://user-images.githubusercontent.com/117189621/230787974-bba72c87-f67e-4cda-a333-6572cffdab5c.png)

It keeps loading with no end

Picrold Canada
picrold.ca

**Comment by dislokacia** [comment]
Hi, @Picrold !
We checked all your chats and tickets and didn't find the requests related to the topic. Our support team will be happy to help you, please, contact us via the acceptable channel like chats or tickets and please, describe in more details your issue. I see, you have the issue with the Elementor Editor and the JetSmartfilters plugin with the version above 3.0.4, haven't you? Do you have the latest versions of the Elementor and Elementor PRO on your site? Could you, please, try to disable all plugins on your site except the Elementor, Elementor PRO and JetSmartFilters plugin and check if the issue remains?
If the issue is related to the loader in the Elementor editor, I highly recommend you to check this [troubleshoot article](https://crocoblock.com/troubleshooting/articles/elementor-not-loading/) too
If nothing helps, please, contact our support team and share all the details of the issue. We'll do our best to help you!

**Comment by Picrold** [comment]
Hello Team,

The issue is resolved with the new version, 3.1.1

Thank you so much for following up

Picrold Canada
picrold.ca

**Comment by Picrold** [comment]
Thank you
