### ISSUE TITLE
Issue of Lazy load for listings grid inside a listing grid

### ISSUE THREAD

**Issue by satomiao** [CrocoBlock/suggestions#6770]
I'm using the Gutenberg Editor for the Jetengine Profile Builder Account Page and its subpages, which were created as a listing grid item. This approach is suggested and recommended by the Crocoblock team. (the template created in JetThemeCore is not supported, which is strange.)

One issue I've encountered is that the lazy load feature for other listing grids inside the subpage listing grid item isn't functioning correctly, despite setting a custom query. This needs to be addressed to ensure proper functionality.

**Comment by SolunaCG** [comment]
+1

I´m having similar problems with Elementor and Crocoblock. With the help of the Crocoblock support I was able to build a (for me) pretty complex setup of nested listings and queries and all that and what I wanted was to set the first listing to lazy load so that the page initially isn´t as long as it currently is but the lazy load doesn´t work here so I reverted everything again.

https://www.xn--almhtte-schanze-2vb.de/almhuette/

As you can see the menu (it´s a German restaurant) is pretty long...

**Comment by kaskad88** [comment]
Fix will be in JetEngine v3.2.7
