### ISSUE TITLE
JetEngine Grid Listing "Load more [archive]" button don't work

### ISSUE THREAD

**Issue by Biblothecaire** [Crocoblock/suggestions#682]
I see the post JetEngine Grid Listing "Load more [posts]" button #304
It work fine !
But it don't work in archive mode

I read your tuto 
"https://crocoblock.com/knowledge-base/articles/jetengine-listing-functionality-how-to-create-a-new-listing-to-apply-for-the-certain-post-type/"
 but i don't uderstand how to fixe it ?

The probleme i think is the fact that i can't chose a "post number" when i have "use as archive mode", so my 400 post load same time, more than 2 min to charge the site ...

thanks for your help

**Comment by Floydtm** [comment]
@Biblothecaire, Hi! Thank you for the message. Once again we checked the operation of the load more button on the archive of posts. Everything is working correctly. Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help
