### ISSUE TITLE
Ability to clear UR (URL Aliases) for Jet search plugin

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#6883]
Hi crocoblock team.

When we search in website using the jet search plugin, the url on the search results page is very long and inappropriate. The following url was generated after searching for the term "Samsung". 

https://domain.com/??s=samsung%5D&jet_ajax_search_settings=%7B"search_source"%3A"product"%2C"results_order_by"%3A"relevance"%2C"results_order"%3A"asc"%7D&post_type=product

**The following url is for another website where the term "samsung" was searched.**

https://domain.com/?s=samsung&post_type=product

It would be great if you could add URL Aliases to the jet search plugin like the jet samrt filters plugin.

**Comment by MjHead** [comment]
In 3.3.0 was added global search options, which allows reduce the URL. Unfortunately at the moment we can't reduce it to ?s=samsung&post_type=product, because JetSearch still requires some additional parameters to make itself to works, but new functionality will strip the most of the string in your example

**Comment by 79ho3ein** [comment]
Hi @MjHead, Thanks for the great update.

How should this feature be set? I failed to do so on initial inspection.
