### ISSUE TITLE
Interference of jet engine data stores with wp-rocket plugin

### ISSUE THREAD

**Issue by Michaelgimii** [CrocoBlock/suggestions#6974]
Hi team,

When the wp-rocket plugin is active, the performance of jet engine data stores is disrupted. For example, I like a post as a guest user. In this case, the like count will not be updated for other users. Until the admin clears the wp-rocket plugin cache. Is there any quick fix for this problem?

**Comment by Michaelgimii** [comment]
Hi @MjHead, This is the answer given by someone from wp-rocket.

https://github.com/wp-media/wp-rocket/issues/6073#issuecomment-1659634137

**Comment by Crocoblock** [comment]
Hi, this was added in version 3.2.7

**Comment by Joliamendi** [comment]
Hi @Crocoblock, @kaskad88. This problem is now fixed but there is still a major problem. The problem is that in bricks, I have added the datastore widget inside a single portfolio (custom post type). On the front end, when the user likes the Portfolio by clicking the like icon, the counter is not updated until the user reloads the page. Actually, the counter is not updated as Ajax. This theme works well in Elementor.

**Comment by kaskad88** [comment]
> Hi @Crocoblock, @kaskad88. This problem is now fixed but there is still a major problem. The problem is that in bricks, I have added the datastore widget inside a single portfolio (custom post type). On the front end, when the user likes the Portfolio by clicking the like icon, the counter is not updated until the user reloads the page. Actually, the counter is not updated as Ajax. This theme works well in Elementor.

Hi @Joliamendi. Create a new issue for this problem

**Comment by Joliamendi** [comment]
Hi @kaskad88, Done [Here](https://github.com/Crocoblock/suggestions/issues/7169). Please also check [this item](https://github.com/Crocoblock/suggestions/issues/7162) on the same topic. thanks
