### ISSUE TITLE
Jetengine's widgets need to be improved!

### ISSUE THREAD

**Issue by mehdimoradi1500** [CrocoBlock/suggestions#7017]
Hi
1- At the moment when i add a widget like dynamic field and want to show a dynamic tag like h3, it warps it into the extra div! 
If i use 4 dynamic fields in a post card and have 20 posts in a page! it makes 80 extra div or Dom!
Note: Let users decide to wrap things or not! if we need an extra div we can simply add a div element. 

2- In bricks builder we can use several dynamic fields in one widget! but with Jetengine fields its not possible! 

@Floydtm Please watch this [video](https://drive.google.com/file/d/18ILTm7ol1dRLjUJrqK-21ioBv_7n9nVo/view), its an important topic to improve the performance of Jetegine!

**Comment by 79ho3ein** [comment]
+1

**Comment by sekhsoyebali** [comment]
+1

**Comment by MjHead** [comment]
1. You can use Optimized DOM performance tweak in JetEngine. In this case Dynamic Field generates 1 tag for itself and 1 more tag - it's root wrapper for Bricks, which is added for any Bricks element - https://tppr.me/ESYJK. At the moment we can't reduce this structure more, because we need at least 1 tag to ensure consistency of Dynamic Field between different builders. In future this may change.
2. If you speak about Dynamic Field widget itself - yes, you can't, because Dynamic Field is a widget and you can't use 2 widgets in single widget. If about combining data, similar to Dynamic Field widget returns - you can use [jet_engine_data] shortcode - https://tppr.me/dAfNf. It has the same possibilities as Dynamic Field widget itself, but you can combine any number of these shortcodes in any Bricks widget which supports shortcodes.

**Comment by mehdimoradi1500** [comment]
> 1. At the moment we can't reduce this structure more, because we need at least 1 tag to ensure consistency of Dynamic Field between different builders. In future this may change.

Well this is not the answer i was looking for after few weeks! First we (users) are trying to help you guys, make your plugins improved.
Second the bug/improvement i just reported has been talked alot between users in Facebook! So simply it should be improved Without any discussion. Also i mentioned in the first of video that i used the optimized tweak but we still have extra dom! 

Every bug or improvements we asked for, you explain in so many lines to not do that. Or it just take months to be considered!
