### ISSUE TITLE
URL v for JetSearch Search Page

### ISSUE THREAD

**Issue by engr-amir-hamza** [CrocoBlock/suggestions#7067]
The url generated by jetsearch plugin  for the search archive is too long and looks ugly.
There is a feature for url aliasing in jetsmartfilters which works very well at shortening the filters or search filter url. Such a feature is not available in JetSearch.

**Comment by huush** [comment]
Actually, I think it may be even worse than that. 

We have a client that previously, the web designer had setup JetSearch to also search through about 10 Taxonomies. Product base about 5k, Taxonomy terms over 1000 all up. These searches would regularly timeout and get stuck in the db queue. 

We removed the "search in taxonomies" from the JetSearch configuration and the searches were much better and coming back in seconds. But since then, at random intervals, there would be queries stuck in the DB queue using the old JetSearch URL query string. This has been going on for months and I've only just been able to fully confirm that old query component detail in the stuck queries yesterday. 

I'm yet to confirm my suspicion, but I suspect that search engines may have scraped the result page URL in the past with the URL effectively holding the full old query instruction at that point in time. Then when the search engines are trying to refresh their held URLs - since that URL will bypass the initial search widget which will build the query from configuration - the old BAD URL then is allowed through and attempts to pull results. Again causing the issue of stuck queries in the client database. 

I came here today hoping to find a means to find that there was a configuration to have that result URL be simply something short and safe like [host]/search?s=[searchstring] and prevent this insecure query injection by URL.

**Comment by huush** [comment]
@MjHead Any chance of an update on this one, please? This stuck query issue is regularly blocking our customer's site. Definitely being caused by the JetSearch query joins. Query gets stuck for days. 

I'm discussing with our host to change the SQL tables from MyISAM to InnoDB. As the issue is your query when run on MyISAM tables does a full table lock. So nothing else can make changes to the posts and term_relationships tables while your query is stuck. 

Have you encountered this before?

**Comment by Crocoblock** [comment]
Hi @huush @engr-amir-hamza 
Custom Search Results URL control in the Ajax Search widget for page link where search results will be displayed - was added in version 3.3.0. Please, update the plugin

**Comment by huush** [comment]
Thanks for the update. Will look to do that first to see if it has an effect.
