### ISSUE TITLE
SQL query that works as a POST type

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7269]
If in an SQL type query we use a calculated column, even if we indicate that it behaves like a post, it will not work. The ID is not included in the query since it gives it the alias post.ID
![Captura de pantalla 2023-12-29 135305](https://github.com/Crocoblock/suggestions/assets/90837626/89bff6b4-71ea-41ab-9356-18aefded0ec7)

**Comment by MjHead** [comment]
In this case it will be better to use Advanced query, because it will require to much UI changes and complicated logic. Here is an example how to reproduce this case with Advanced Query

<img width="1270" alt="image" src="https://github.com/Crocoblock/suggestions/assets/4987981/07b9de02-88ef-4e1a-b2b2-40787a7239d4">
