### ISSUE TITLE
availability booking calendar for jetsmartfilter

### ISSUE THREAD

**Issue by Nordiccraftmedia** [CrocoBlock/suggestions#7307]
Its boring using too many different calendars for booking and it confuses the clients.. 

Is it possible to add an filter based with availability booking calendar.. 

This will make an perfection of jetbooking plugin and jetsmartfilter.

Right now do you any temporary solution, how can i get availability calendar date to an daterange input of jetsmartfilter

**Comment by UraraReika** [comment]
Hello @Nordiccraftmedia! Thank you for your feedback!

Unfortunately this is not possible, because plugins use different libraries for date picker and library that JetSmartFilter uses cant accept and handle some parameters for availability calendar. On the other hand library in JetBookign plugin for availability calendar can only work individually with single post or AJAX loaded post, but not fir the list of the posts. 

So in this case we will not add this to the core of our plugins.

Thank you for understanding.
