### ISSUE TITLE
Query builder ,  Query Type WC product Query , Order by two or more meta value

### ISSUE THREAD

**Issue by moradi-arash** [CrocoBlock/suggestions#7356]
I suggest adding option to order product in WC product Query , Be able to do with more than one value 

Currently in jetengine , this option exists for posts and term Query , but not for WC product Query

in WC product Query Only one value can be order

**Comment by UraraReika** [comment]
Hello @moradi-arash! Thanks for the feedback.

Unfortunately, this is not possible for WC Product Query due to it does not support ordering by multiple columns simultaneously. If we have a closer look at documentation - https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query we can see that ordering parameters can accept strings only - https://tppr.me/MIZ8CE so this is not possible to made it the same as in Post or Term Queries. Post query - https://developer.wordpress.org/reference/classes/wp_query/#order-orderby-parameters as you can see accepts both data types and it helps to add multiple parameters.

Thank you for your understanding.
