### ISSUE TITLE
Jetengine query builder macro query result count. bug?

### ISSUE THREAD

**Issue by JuanCar29** [CrocoBlock/suggestions#7381]
In a SQL query, I try to use the results macro of another query for the result limit and it does not work.
![Captura de pantalla 2024-02-26 193955](https://github.com/Crocoblock/suggestions/assets/90837626/54ecab41-f40d-45bd-b9b3-0aa4d21a60bd)

**Comment by Crocoblock** [comment]
Hi @JuanCar29 

This is not a bug because this macro returns html, but this field requires a number. To solve this issue, you can use [this snippet](https://gist.github.com/Crocoblock/f2d836264db3f7694f559c93bb0cbe19) by adding this code to the function.php of your child theme or code snippet plugin and then [use this macro](https://github.com/Crocoblock/suggestions/assets/47778274/bfbd9c28-65a0-4a4a-bde3-b95338654fd8)

**Comment by JuanCar29** [comment]
Thank you very much, it works well and it will be very useful to me. They can integrate it into new versions.
