### ISSUE TITLE
offset posts in the Smart Posts List

### ISSUE THREAD

**Issue by Eybogy** [Crocoblock/suggestions#744]
Please, Add offset posts in the Smart Posts List like in Smart Posts Tiles

**Comment by tf5bassist** [comment]
Seconded.  This is a critical missed option, I would really like to see this added sooner rather than later.

## Smart tiles example:
![image](https://user-images.githubusercontent.com/2079716/72410645-bd6f7900-371d-11ea-8057-8c99e68fd7fa.png)

## Smart posts example:
![image](https://user-images.githubusercontent.com/2079716/72410679-d8da8400-371d-11ea-9cee-dc29c8e94039.png)

**Comment by kaskad88** [comment]
Added for the next version (2.2.5).
Thanks for your report!
