### ISSUE TITLE
Make register user action compatible with gateway.sucess event

### ISSUE THREAD

**Issue by clemjam** [CrocoBlock/suggestions#7450]
Hi,

Can you make it possible to trigger a user registration only after successful payment ? Currently, there is an error if I choose register user action with gateway.sucess event ("empty password").

It seems to be an important feature in a membership website. 

Best regards,
ClemJam

**Comment by Crocoblock** [comment]
Hi @clemjam!

Well, the register user action can not work with the gateway statuses because the JetFormBuilder does not save the passwords entered by users, so the conditional logic can not be considered complete in this case https://prnt.sc/jymezPkDey58

Nevertheless, our developer created a workaround that helps you set the Register User action to be performed on Gateway success (or other statuses) only https://prnt.sc/vWV0HqMJfPeb

1. You need to add this custom code to your website  https://gist.github.com/girafffee/cb7d9721e707a70045b96d53efed5d75

The code can be added to the Code Snippets plugin or the functions.php file of your child theme.

This snippet creates a new option in the hidden field- Generated Password. This field is saved with the value '1' which does not affect anything in the form but only adds this option which allows working with the gateway statuses.

After the successful gateway, the form will find a field that should contain a password. And before performing the post-submit actions, a unique token will be generated and inserted as a password to the field where the password should be.



2. Then you need to add a hidden field with the custom option Generated Password selected https://prnt.sc/vYXkRKH6g9_r

3. In the Register User action, you need to select the hidden field for both Password and Confirm Password fields https://prnt.sc/f1Sj28kirto5

4. Then you need to add the GATEWAY.SUCCESS to the  Register User action's conditional logic https://prnt.sc/vWV0HqMJfPeb

5. This message https://prnt.sc/afmxGhxvlURj will still be there for information but it is not relevant with the added snippet :)

6. Then you need to include the generated password into the Send Email action, so the user can know the generated password https://prnt.sc/9wqGmevtrznm

**Comment by clemjam** [comment]
Hi ! Thanks for reply.

I've tried and it seems to work BUT if there is an error in the form (exemple : already existing id) the error is not shown before payment, the visitor is redirected to the payment page and after he paid, he is redirected to my website and see the error. So he has paid, but his account hasn't been created 😱 

<img width="285" alt="Capture d’écran 2024-04-02 à 12 36 50" src="https://github.com/Crocoblock/suggestions/assets/147487042/99d67e0b-0514-44cd-a701-5fdce62ce30b">

**Comment by clemjam** [comment]
No solution about that issue ? 🙏

**Comment by clemjam** [comment]
And also, is there a difference between the solution you suggested and the "Secure token" that is integrated into JFB ? 
<img width="1055" alt="Capture d’écran 2024-04-02 à 12 20 33" src="https://github.com/Crocoblock/suggestions/assets/147487042/086ddf8b-c036-4092-ada6-9141ab0ee086">
