### ISSUE TITLE
JetProduct Gallery: Vertical Slider Thumbnails Lose Proportion

### ISSUE THREAD

**Issue by ricardoaraujo330** [CrocoBlock/suggestions#7567]
**Description:**

I'm experiencing an issue with the JetProduct Gallery widget when the slider direction is set to vertical and pagination is set to "thumbnails." The thumbnails lose their proportion, and it's not intuitive how to set their height. The width is adjustable in the style tab, but height-related elements are scattered between the edit and design tabs, making the plugin very confusing.

**Steps to Reproduce:**

Set the JetProduct Gallery widget slider direction to vertical.
Set pagination to "thumbnails."
Adjust the width of the thumbnails in the style tab.
Notice the disproportion of the thumbnails and the scattered height settings.
Expected Behavior:
Thumbnails on the left side of the main product image should occupy the full height, matching the height of the main product image.

**Actual Behavior:**
Thumbnails on the left side of the main product image do not occupy the full height and do not match the height of the main product image.

**Support Response:**
I reached out to support, and here’s the response:

```
As a rule, to have the images of the same size inside the slider, we need to choose the needed option in the dropdown https://prnt.sc/O1OcMko54mV-
But if you have images that have different aspect ratios - this would not work.
After investigating this issue, we reached the conclusion that it would be great to create our own size, which will suit all of us, and additionally, it will have the crop functionality so that the size corresponds to the set value. Here's documentation with the method of how to create it https://developer.wordpress.org/reference/functions/add_image_size/
Here's how the size of the crop is managed https://prnt.sc/S-DZ06kvld-- - the 3rd parameter is very important. Here's the example of how you can create it in the child theme https://prnt.sc/E-Tg6PwSNu0- with such verification https://prnt.sc/Bh5cXBWkRKk
When it's done, we need to elaborate on the next step. We need to regenerate the images if they're already uploaded to the website - as an example, you can use this plugin https://wordpress.org/plugins/regenerate-thumbnails/
Note please, that you need to regenerate the images which are already uploaded to the website only. All images which will be uploaded to your website AFTER creating a custom size will have this adjusted size.
```

**Attachments:**

Desired Outcome: 
<img width="1103" alt="2" src="https://github.com/Crocoblock/suggestions/assets/29624839/2bc4d019-5f50-4131-934c-df6e8241c048">

Example of What I Get:
<img width="977" alt="1" src="https://github.com/Crocoblock/suggestions/assets/29624839/434925ab-b40c-43ac-8c7f-c89c4829e365">

**Example of What I Want to Achieve:**

**Additional Context:**
The current configuration options are not sufficient to achieve a uniform thumbnail display. The settings need to be more streamlined and centralized, particularly for height adjustments in vertical slider configurations.

**Suggestions:**

Consolidate height and width settings for thumbnails in the style tab.
Ensure thumbnails maintain their aspect ratio.
Provide more intuitive controls for thumbnail dimensions.

Thank you for your attention to this matter. I look forward to a resolution that enhances the usability and functionality of the JetProduct Gallery widget.

**Comment by UraraReika** [comment]
This type of displaying vertical pagination thumbnails is the way how Swiper Slider library works. There is nothing we can do about it but we can adjust some parameters to look pagination nice. The overall look of pagination depends on several parameters: first one is pagination height - https://tppr.me/l9MMkn, second - slides per view - https://tppr.me/AhR9mw, third is space between - https://tppr.me/na4kRY, pagination width - https://tppr.me/Ffnkvu gutter - https://tppr.me/vn9CDI and finally width of container of widget. You also want to make you images similar size to display it properly.

For example we want to display 5 images in pagination. First of all we take a look at images that we use. They all have the same size and they are square - https://tppr.me/ViF6Jc. And you should take a note about it, if you want your slider looks nice please use same sized images or at least same aspect ratio for all images that you use in gallery.

We set pagination width to 100px and add right gutter to create space between pagination and main image - https://tppr.me/So4sKx and set space between to 5px - https://tppr.me/NJSIPQ that mean that our images now look like this - https://tppr.me/H7ma54 good but not perfect because initially they are square. 

Now we can inspect image and see its height - https://tppr.me/7yXFKF we also know space between them so we can calculate proper height. 95 times 5 plus 5 times 4 (4 spaces count between images) equal 495 so lets set this height - https://tppr.me/R7kljF. This is final result - https://tppr.me/dvnRmf.

If we want to adjust pagination size to main image we need to make some different settings to set proper height and spaces between images. Like this for example - https://tppr.me/FH6nvY.

Unfortunately, there is no easier way to configure the vertical gallery slider, so if you have any problems, please contact our support team.
