### ISSUE TITLE
Bug on Components Feature JetEngine 3.5.0

### ISSUE THREAD

**Issue by dantetesta** [CrocoBlock/suggestions#7585]
The new component creation feature in JetEngine has a bug.

When creating a component with its text and style resources, and then applying the component to the page, attempting to edit the colors results in the same color being applied to both components in distinct scopes. This issue occurs both on static pages and in listing grids.

Please test this feature.

**Comment by MjHead** [comment]
@dantetesta Could you please add more detailed description, with the screenshots of where and how you apply color settings and how you add component to the page? Because by such description I could only answer that we tested exactly such cases and all worked fine:

<img width="652" alt="image" src="https://github.com/Crocoblock/suggestions/assets/4987981/c4783c7e-a39d-4d05-b8cf-af8f2e95886d">
