### ISSUE TITLE
Unable to Resize Account Downloads Widget Width in JetWooBuilder

### ISSUE THREAD

**Issue by jenko-code** [CrocoBlock/suggestions#7742]
Describe the bug
The "Account Downloads" widget in the JetWooBuilder plugin does not respond correctly to width adjustments. Even though the width is being set to a custom value (as shown in the screenshots), the widget on the front end does not change in appearance. Attempts to adjust the width of the container surrounding the widget also have no effect.

To Reproduce

Go to the Elementor editor.
Select the "Account Downloads" widget in JetWooBuilder.
Set a custom width for the widget (as shown in the screenshots).
Preview the page on the front end, and observe that the widget width does not change.
Expected behavior
The width of the "Account Downloads" widget should adjust according to the custom width set in the editor. The widget should become narrower as specified in the settings.

Screenshots
See the attached screenshots for clarification:
![Posnetek zaslona 2024-09-12 204536](https://github.com/user-attachments/assets/5ec89e7d-24ef-48c3-9385-345a5479cd04)
![Posnetek zaslona 2024-09-12 204600](https://github.com/user-attachments/assets/3ead451f-0bbd-4ee5-b3af-9ff8849208a5)

Screenshot showing the custom width setting in the editor (453px).
Screenshot showing the front-end appearance, where the widget width remains unaffected despite the custom settings.
Desktop (please complete the following information):

OS: Windows 11
Browser: Chrome and Edge
Version: Latest version of both browsers at the time of the issue
Smartphone (please complete the following information):

Device: Samsung Galaxy A series (Exact model unknown, possibly A71 or A75)
OS: Android
Browser: Chrome
Version: Latest version available
Additional context
The problem seems to persist regardless of attempts to adjust the width in the container surrounding the widget. It would be ideal if the widget's width could be properly controlled via the custom settings to improve the front-end appearance.

**Comment by UraraReika** [comment]
Account Downloads widget is a table in JetWooBuilder plugin and this element works exactly like this. So you of course can set custom width for this element but this is doesn't mean it will apply this way, because you need to take a note about different attributes of this kind of element. Basically this will happened to all table elements and how styles works on this elements will be different based of fonts, gaps settings and text itself.  

That is why you need to be more precisely and specific on how you style the element and use additional custom styles because default controls will not help you with this.
