### ISSUE TITLE
Why not add Conditional Logic at WooCommerce Product Variation (Metabox feature)

### ISSUE THREAD

**Issue by vishal19121981** [CrocoBlock/suggestions#7753]
The Conditional Logic feature is missing at WooCommerce Product Variation section
I think it should be there to select the correct option if we introduce the Radio button there

Example:
If we add location as a radio button in WooCommerce Product Variation tab
and based on previous selection of radio button for Location, we need to select sub-location, where we can erroneously select wrong field. or by mistake.

1st Radio button
Location: America, Japan etc

2nd Radio button
Sub-Location: North America, South America etc
3rd Radio button
Sub-Location: Hirosima, Nagasaki etc

Based on Location radio button the 2nd or 3rd radio button should appear or hide based on selection

Here we cannot apply conditional logic in sub-location radio button, and one can select wrong field either accidentally or mistakenly

I request you to please introduce conditional logic here

**Comment by UraraReika** [comment]
Hello @vishal19121981! Thanks for the feedback.

Unfortunately, structure of the metabox fields doesn't allow us implement conditional logic in this area. That's why this kind of controls unavailable while setting fields. Maybe use different field type to prevent accidentally choose incorrect info.

Thank you for your understanding.
