### ISSUE TITLE
Signature field in Jegengine

### ISSUE THREAD

**Issue by IsraPaya** [CrocoBlock/suggestions#7785]
It would be great if Jetengine had a 'signature' field. I can see that many people is requesting it. I had two projects I could not make for this reason.

Do you think you could add it soon? 

Thank you very much.

Tatiana Roxana Vélez

**Comment by Crocoblock** [comment]
Unfortunately, we do not plan to introduce such functionality into our plugin. Now our team is working on more priority tasks. However, in the future, we will not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for being so understanding.

I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/6238)
