### ISSUE TITLE
2.7.1 update breaks button icon alignment position

### ISSUE THREAD

**Issue by portrayaloflife** [CrocoBlock/suggestions#7836]
**Describe the bug**
After update to 2.7.1 the alignment option for icon in the buttons element only displays icons on the "left", regardless if it's set to "right". So all our buttons with arrows on the right were moved to the left

**To Reproduce**
1. Go to a page and add a jet element button
2. Click on settings, turn "use icon" on and set alignment to "right"
3. View button
4. See error of icon on left

**Expected behavior**
Icon should be on the right when the icon position is set to "right"

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser: chrome, safari

**Comment by mdashsh** [comment]
+1 https://support.crocoblock.com/a/tickets/195591

**Comment by marowi85** [comment]
+1

I think I have the same problem with the post widget. The carousel navigation is set so that the arrows are aligned to the right, but they are still positioned to the left.

Before:
![before](https://github.com/user-attachments/assets/20e89c2c-af41-41f0-8077-e54ea8fa7bfb)

After:
![after](https://github.com/user-attachments/assets/f10d7916-7507-4684-b36a-40fd0ec0eb67)

Settings:
![settings](https://github.com/user-attachments/assets/94e95bd7-c2e2-4991-83f1-3326071aa546)

**Comment by Crocoblock** [comment]
Hi @portrayaloflife  

This issue was fixed and released in JetElements 2.7.1.1
Thank you for reporting!

@marowi85 Please, update the plugin. if the issue still exists, contact our support team regarding this case - https://crocoblock.com/help-center/ create a ticket including access details for your site where the issue occurred to make sure we can help you.
