### ISSUE TITLE
 I hope each piece of content within the map listing will have a unique URL generated.

### ISSUE THREAD

**Issue by SwenHong** [CrocoBlock/suggestions#7870]
I am writing to request a feature enhancement for the Map Listing module that involves assigning unique URLs to each location. This feature would bring several benefits:

1. Users can easily share specific locations via unique URLs, making it easier to convey precise information.
Improved User Experience:

2. Linking unique addresses with single posts allows for a seamless transition between map views and detailed post views, providing a continuous user experience.

Uploading map listing.mp4…

**Comment by Crocoblock** [comment]
Now our team is working on more priority tasks. But in the future we do not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for your understanding.

I am closing this issue because it is a copy
Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/7610)
