### ISSUE TITLE
JetSmartFilters - Hide filters - Show number of posts or products

### ISSUE THREAD

**Issue by aldaronn5** [Crocoblock/suggestions#79]
1. After choosing filters there should be function that hide filfter with no products or posts, to prevent showing blank page without any results screenshot: http://prntscr.com/mtexke

2. There should be option to allo show how many products posts are in filter screenshot: http://prntscr.com/mtexx0

**Comment by MjHead** [comment]
Hi @aldaronn5 Thanks for your suggestion. We planning to add something like this in future releases. Unfortunately at this moment there is no ETA on this feature, because our filters works bit different way and we need to make huge changes in plugin API to implement such functionality. But we definitely start to work on this in nearly future

**Comment by Biblothecaire** [comment]
+1 for this suggestions :)

**Comment by davidk82** [comment]
really need this function ... thanks!

**Comment by Floydtm** [comment]
This has been implemented since plugin version 1.5.0
