### ISSUE TITLE
Jet Listing Grid Slider Vertical

### ISSUE THREAD

**Issue by Amirsadan** [CrocoBlock/suggestions#7917]
i can see that there its not possible to make my listing grid slider vertical.

its such a requested feature and it make sense that the feature should be built in the jet listing slider.

please add this feature or try to give a solution to this because its so usefull in so many ways.

thank you!

**Comment by Crocoblock** [comment]
Now our team is working on more priority tasks. However, in the future, we will not exclude the possibility of adding this functionality to the core of our plugin.

Thank you for being so understanding.

I am closing this issue because it is a copy

Please keep an eye on [it](https://github.com/Crocoblock/suggestions/issues/418)
