### ISSUE TITLE
JetSmartFilters - Sliding Panel for Filters - Related to #855

### ISSUE THREAD

**Issue by secondsky** [Crocoblock/suggestions#948]
The mentioned solution in suggestion 855 (Hamburger Panel) doesnt work. 
The filters dont get applied to the listing grid widget of JetEngine. 
I use AJAX method.

Therefor i still see the suggestion open....
https://github.com/Crocoblock/suggestions/issues/855

**Comment by Floydtm** [comment]
@secondsky, we checked again and everything works. 
[example.zip](https://github.com/Crocoblock/suggestions/files/4260764/example.zip)
Please, submit a ticket https://support.crocoblock.com describe your case in details and provide your WP details so that we could take a closer look from the back-end.
Our tech support will gladly help you
