### ISSUE TITLE
Smart Filters - add additional widget support

### ISSUE THREAD

**Issue by slamdive** [Crocoblock/suggestions#990]
Hi,

Using Smart Filters - would it be possible to add the ability to filter the posts widgets from other popular addon packs:
Elementor Extras - Posts Extra 
Ultimate Addons for Elementor - Posts 
PowerPack Elements - Posts

I also notice that Smart Filters does not work with the Posts Module in Jet Elements or JetBlog.
Why does Smart Filters not support your own posts modules?

Thanks!

**Comment by stasonua0** [comment]
Why do you filter posts?
Elementor Extras - Posts Extra
Ultimate Addons for Elementor - Posts
PowerPack Elements - Posts

While there is a Jet Engine, and by installing plugins that duplicate the Crocoblock functionality, you will make an old turtle from your site.

Regarding Jet Elements or Jet Blog
Created more than 100 sites on Crocoblock and never thought of filtering anything in the plugins mentioned above.

And all because there is a Jet engine and this is a universal solution for all your tasks

**Comment by slamdive** [comment]
@stasonua0 
I don't want to build anything from scratch using Jet Engine.

Only asking for Smart Filter to have some additional post widget options added.
At the moment only Elementor Pro posts widget is an option.

Maybe you misunderstood my question.

**Comment by Floydtm** [comment]
@slamdive, hi! We do not plan to do this. You can solve your request with the jetengine plugin. Thanks you!

**Comment by slamdive** [comment]
Cheers @Floydtm 

No problem.

Would be great if you could consider adding functionality for your own post widgets however. ;-)
Seems a bit strange to have a post widget in JetElements and also JetBlog and yet SmartFilters doesn't work with any of them.

Will take a deeper look at JetEngine. Thanks.
